#include "codegen/gen_api.h"
#include "codegen/gen_server.h"
#include "copy_pipeline.h"
#include "cuda_server.h"
#include "rpc_server.h"

#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// Custom CUDA handlers are looked up before generated CUDA handlers, so these
// entries retain precedence for overlapping operations.
static const std::unordered_map<int, rpc_handler> &cuda_custom_handlers() {
  static const std::unordered_map<int, rpc_handler> handlers = {
      {RPC_cuGetErrorName,
       {handle_manual_cuGetErrorName, "cuGetErrorName",
        rpc_handler_error_style::manual}},
      {RPC_cuGetErrorString,
       {handle_manual_cuGetErrorString, "cuGetErrorString",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuGetExportTableMetadata,
       {handle_manual_cuGetExportTableMetadata, "cuGetExportTable metadata",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuPrivateGetModuleNode,
       {handle_manual_cuPrivateGetModuleNode, "private module node",
        rpc_handler_error_style::manual}},
      {RPC_cuModuleLoad,
       {handle_manual_cuModuleLoad, "cuModuleLoad",
        rpc_handler_error_style::manual}},
      {RPC_cuModuleLoadData,
       {handle_manual_cuModuleLoadData, "cuModuleLoadData",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineFunctionParamLayoutSnapshot,
       {handle_manual_lupineFunctionParamLayoutSnapshot,
        "lupineFunctionParamLayoutSnapshot", rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineFunctionAttributeSnapshot,
       {handle_manual_lupineFunctionAttributeSnapshot,
        "lupineFunctionAttributeSnapshot", rpc_handler_error_style::manual}},
      {RPC_cuLibraryLoadData,
       {handle_manual_cuLibraryLoadData, "cuLibraryLoadData",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineLibrarySnapshot,
       {handle_manual_lupineLibrarySnapshot, "lupineLibrarySnapshot",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineLibraryAttributeSnapshot,
       {handle_manual_lupineLibraryAttributeSnapshot,
        "lupineLibraryAttributeSnapshot", rpc_handler_error_style::manual}},
      {RPC_cuCtxCreate_v2,
       {handle_manual_cuCtxCreate_v2, "cuCtxCreate_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuDevicePrimaryCtxRetain,
       {handle_manual_cuDevicePrimaryCtxRetain, "cuDevicePrimaryCtxRetain",
        rpc_handler_error_style::manual}},
      {RPC_cuDevicePrimaryCtxRelease_v2,
       {handle_manual_cuDevicePrimaryCtxRelease_v2,
        "cuDevicePrimaryCtxRelease_v2", rpc_handler_error_style::manual}},
      {RPC_cuDevicePrimaryCtxReset_v2,
       {handle_manual_cuDevicePrimaryCtxReset_v2, "cuDevicePrimaryCtxReset_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuCtxAttach,
       {handle_manual_cuCtxAttach, "cuCtxAttach",
        rpc_handler_error_style::manual}},
      {RPC_cuCtxDestroy_v2,
       {handle_manual_cuCtxDestroy_v2, "cuCtxDestroy_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuCtxDetach,
       {handle_manual_cuCtxDetach, "cuCtxDetach",
        rpc_handler_error_style::manual}},
      {RPC_cuMemPoolSetAttribute,
       {handle_manual_cuMemPoolSetAttribute, "cuMemPoolSetAttribute",
        rpc_handler_error_style::manual}},
      {RPC_cuMemPoolGetAttribute,
       {handle_manual_cuMemPoolGetAttribute, "cuMemPoolGetAttribute",
        rpc_handler_error_style::manual}},
      {RPC_cuMemExportToShareableHandle,
       {handle_manual_cuMemExportToShareableHandle,
        "cuMemExportToShareableHandle", rpc_handler_error_style::manual}},
      {RPC_cuMemImportFromShareableHandle,
       {handle_manual_cuMemImportFromShareableHandle,
        "cuMemImportFromShareableHandle", rpc_handler_error_style::manual}},
      {RPC_cuMemPoolExportToShareableHandle,
       {handle_manual_cuMemPoolExportToShareableHandle,
        "cuMemPoolExportToShareableHandle", rpc_handler_error_style::manual}},
      {RPC_cuMemPoolImportFromShareableHandle,
       {handle_manual_cuMemPoolImportFromShareableHandle,
        "cuMemPoolImportFromShareableHandle", rpc_handler_error_style::manual}},
      {RPC_cuPointerGetAttribute,
       {handle_manual_cuPointerGetAttribute, "cuPointerGetAttribute",
        rpc_handler_error_style::manual}},
      {RPC_cuPointerSetAttribute,
       {handle_manual_cuPointerSetAttribute, "cuPointerSetAttribute",
        rpc_handler_error_style::manual}},
      {RPC_cuPointerGetAttributes,
       {handle_manual_cuPointerGetAttributes, "cuPointerGetAttributes",
        rpc_handler_error_style::manual}},
      {RPC_cuLinkCreate_v2,
       {handle_manual_cuLinkCreate_v2, "cuLinkCreate_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuLinkAddData_v2,
       {handle_manual_cuLinkAddData_v2, "cuLinkAddData_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuLinkAddFile_v2,
       {handle_manual_cuLinkAddFile_v2, "cuLinkAddFile_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuLinkComplete,
       {handle_manual_cuLinkComplete, "cuLinkComplete",
        rpc_handler_error_style::manual}},
      {RPC_cuLinkDestroy,
       {handle_manual_cuLinkDestroy, "cuLinkDestroy",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpy3D_v2,
       {handle_manual_cuMemcpy3D_v2, "cuMemcpy3D_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpy2D_v2,
       {handle_manual_cuMemcpy2D_v2, "cuMemcpy2D_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpy2DUnaligned_v2,
       {handle_manual_cuMemcpy2DUnaligned_v2, "cuMemcpy2DUnaligned_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpy2DAsync_v2,
       {handle_manual_cuMemcpy2DAsync_v2, "cuMemcpy2DAsync_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpyDtoH_v2,
       {handle_manual_cuMemcpyDtoH_v2, "cuMemcpyDtoH_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpyAtoH_v2,
       {handle_manual_cuMemcpyAtoH_v2, "cuMemcpyAtoH_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemHostAlloc,
       {handle_manual_cuMemHostAlloc, "cuMemHostAlloc",
        rpc_handler_error_style::manual}},
      {RPC_cuMemHostGetFlags,
       {handle_manual_cuMemHostGetFlags, "cuMemHostGetFlags",
        rpc_handler_error_style::manual}},
      {RPC_cuDeviceGetGraphMemAttribute,
       {handle_manual_cuDeviceGetGraphMemAttribute,
        "cuDeviceGetGraphMemAttribute", rpc_handler_error_style::manual}},
      {RPC_cuDeviceSetGraphMemAttribute,
       {handle_manual_cuDeviceSetGraphMemAttribute,
        "cuDeviceSetGraphMemAttribute", rpc_handler_error_style::manual}},
      {RPC_cuLibraryGetModule,
       {handle_manual_cuLibraryGetModule, "cuLibraryGetModule",
        rpc_handler_error_style::manual}},
      {RPC_cuLibraryUnload,
       {handle_manual_cuLibraryUnload, "cuLibraryUnload",
        rpc_handler_error_style::manual}},
      {RPC_cuModuleGetGlobal_v2,
       {handle_manual_cuModuleGetGlobal_v2, "cuModuleGetGlobal_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuOccupancyMaxPotentialBlockSize,
       {[](conn_t *conn) {
          return handle_manual_cuOccupancyMaxPotentialBlockSize(conn, false);
        },
        "cuOccupancyMaxPotentialBlockSize", rpc_handler_error_style::manual}},
      {RPC_cuOccupancyMaxPotentialBlockSizeWithFlags,
       {[](conn_t *conn) {
          return handle_manual_cuOccupancyMaxPotentialBlockSize(conn, true);
        },
        "cuOccupancyMaxPotentialBlockSizeWithFlags",
        rpc_handler_error_style::manual}},
      {RPC_cuLaunchKernel,
       {handle_manual_cuLaunchKernel, "cuLaunchKernel",
        rpc_handler_error_style::manual}},
      {RPC_cuLaunchKernelEx,
       {handle_manual_cuLaunchKernelEx, "cuLaunchKernelEx",
        rpc_handler_error_style::manual}},
      {RPC_cuLaunchCooperativeKernel,
       {handle_manual_cuLaunchCooperativeKernel, "cuLaunchCooperativeKernel",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphAddKernelNode_v2,
       {handle_manual_cuGraphAddKernelNode, "cuGraphAddKernelNode",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphKernelNodeGetParams_v2,
       {handle_manual_cuGraphKernelNodeGetParams,
        "cuGraphKernelNodeGetParams_v2", rpc_handler_error_style::manual}},
      {RPC_cuGraphKernelNodeSetParams_v2,
       {handle_manual_cuGraphKernelNodeSetParams,
        "cuGraphKernelNodeSetParams_v2", rpc_handler_error_style::manual}},
      {RPC_cuGraphAddMemcpyNode,
       {handle_manual_cuGraphAddMemcpyNode, "cuGraphAddMemcpyNode",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphAddMemsetNode,
       {handle_manual_cuGraphAddMemsetNode, "cuGraphAddMemsetNode",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphAddHostNode,
       {handle_manual_cuGraphAddHostNode, "cuGraphAddHostNode",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphExecKernelNodeSetParams_v2,
       {handle_manual_cuGraphExecKernelNodeSetParams,
        "cuGraphExecKernelNodeSetParams_v2", rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuGraphConditionalHandleCreate,
       {handle_manual_cuGraphConditionalHandleCreate,
        "cuGraphConditionalHandleCreate", rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuGraphAddNode_v2,
       {handle_manual_cuGraphAddNode, "cuGraphAddNode",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphLaunch,
       {handle_manual_cuGraphLaunch, "cuGraphLaunch",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphGetEdges_v2,
       {handle_manual_cuGraphGetEdges, "cuGraphGetEdges",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphNodeGetDependencies_v2,
       {handle_manual_cuGraphNodeGetDependencies, "cuGraphNodeGetDependencies",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphNodeGetDependentNodes_v2,
       {handle_manual_cuGraphNodeGetDependentNodes,
        "cuGraphNodeGetDependentNodes", rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuMemPrefetchAsync,
       {handle_manual_cuMemPrefetchAsync, "cuMemPrefetchAsync",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphHostNodeGetParams,
       {handle_manual_cuGraphHostNodeGetParams, "cuGraphHostNodeGetParams",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphHostNodeSetParams,
       {handle_manual_cuGraphHostNodeSetParams, "cuGraphHostNodeSetParams",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphExecHostNodeSetParams,
       {handle_manual_cuGraphExecHostNodeSetParams,
        "cuGraphExecHostNodeSetParams", rpc_handler_error_style::manual}},
      {RPC_cuLaunchHostFunc,
       {handle_manual_cuLaunchHostFunc, "cuLaunchHostFunc",
        rpc_handler_error_style::manual}},
      {RPC_cuStreamAddCallback,
       {handle_manual_cuStreamAddCallback, "cuStreamAddCallback",
        rpc_handler_error_style::manual}},
      {RPC_cuEventRecord,
       {[](conn_t *conn) { return handle_manual_cuEventRecord(conn, false); },
        "cuEventRecord", rpc_handler_error_style::manual}},
      {RPC_cuEventRecordWithFlags,
       {[](conn_t *conn) { return handle_manual_cuEventRecord(conn, true); },
        "cuEventRecordWithFlags", rpc_handler_error_style::manual}},
      {RPC_cuEventQuery,
       {handle_manual_cuEventQuery, "cuEventQuery",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineEventQueryBatch,
       {handle_manual_lupineEventQueryBatch, "lupineEventQueryBatch",
        rpc_handler_error_style::manual}},
      {RPC_cuStreamWaitEvent,
       {handle_manual_cuStreamWaitEvent, "cuStreamWaitEvent",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuStreamBeginCaptureToGraph,
       {handle_manual_cuStreamBeginCaptureToGraph,
        "cuStreamBeginCaptureToGraph", rpc_handler_error_style::manual}},
      {RPC_cuStreamUpdateCaptureDependencies_v2,
       {handle_manual_cuStreamUpdateCaptureDependencies,
        "cuStreamUpdateCaptureDependencies", rpc_handler_error_style::manual}},
      {LUPINE_RPC_cuStreamGetCaptureInfo_v3,
       {handle_manual_cuStreamGetCaptureInfo, "cuStreamGetCaptureInfo",
        rpc_handler_error_style::manual}},
      {RPC_cuStreamBeginCapture_v2,
       {handle_manual_cuStreamBeginCapture, "cuStreamBeginCapture",
        rpc_handler_error_style::manual}},
      {RPC_cuStreamEndCapture,
       {handle_manual_cuStreamEndCapture, "cuStreamEndCapture",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphClone,
       {handle_manual_cuGraphClone, "cuGraphClone",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphInstantiateWithFlags,
       {handle_manual_cuGraphInstantiateWithFlags,
        "cuGraphInstantiateWithFlags", rpc_handler_error_style::manual}},
      {RPC_cuGraphInstantiateWithParams,
       {handle_manual_cuGraphInstantiateWithParams,
        "cuGraphInstantiateWithParams", rpc_handler_error_style::manual}},
      {RPC_cuGraphExecDestroy,
       {handle_manual_cuGraphExecDestroy, "cuGraphExecDestroy",
        rpc_handler_error_style::manual}},
      {RPC_cuGraphDestroy,
       {handle_manual_cuGraphDestroy, "cuGraphDestroy",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpyHtoD_v2,
       {handle_manual_cuMemcpyHtoD_v2, "cuMemcpyHtoD_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpyHtoDAsync_v2,
       {handle_manual_cuMemcpyHtoDAsync_v2, "cuMemcpyHtoDAsync_v2",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineManagedHostFlush,
       {handle_manual_lupineManagedHostFlush, "lupineManagedHostFlush",
        rpc_handler_error_style::manual}},
      {LUPINE_RPC_lupineDeviceSnapshot,
       {handle_manual_lupineDeviceSnapshot, "lupineDeviceSnapshot",
        rpc_handler_error_style::manual}},
      {RPC_cuMemcpyDtoHAsync_v2,
       {handle_manual_cuMemcpyDtoHAsync_v2, "cuMemcpyDtoHAsync_v2",
        rpc_handler_error_style::manual}},
      {RPC_cuCtxSynchronize,
       {handle_manual_cuCtxSynchronize, "cuCtxSynchronize",
        rpc_handler_error_style::manual}},
      {RPC_cuStreamSynchronize,
       {handle_manual_cuStreamSynchronize, "cuStreamSynchronize",
        rpc_handler_error_style::manual}},
      {RPC_cuEventSynchronize,
       {handle_manual_cuEventSynchronize, "cuEventSynchronize",
        rpc_handler_error_style::manual}},
#if CUDA_VERSION >= 12000
      {RPC_cuTensorMapEncodeTiled,
       {handle_manual_cuTensorMapEncodeTiled, "cuTensorMapEncodeTiled",
        rpc_handler_error_style::manual}},
#endif
  };
  return handlers;
}

rpc_handler lupine_cuda_server_handler(int op) {
  const auto &custom = cuda_custom_handlers();
  auto it = custom.find(op);
  return it == custom.end() ? get_cuda_handler(op) : it->second;
}

const int *lupine_cuda_server_operations(size_t *count) {
  static const std::vector<int> operations = [] {
    size_t generated_count = 0;
    const int *generated = get_cuda_handler_operations(&generated_count);
    std::unordered_set<int> unique(generated, generated + generated_count);
    for (const auto &entry : cuda_custom_handlers()) {
      unique.insert(entry.first);
    }
    std::vector<int> result(unique.begin(), unique.end());
    std::sort(result.begin(), result.end());
    return result;
  }();
  *count = operations.size();
  return operations.data();
}
