"""Generate CUDA's stream variants from the SDK's own alias declarations.

Explicit-stream variants normalize stream zero before entering a shared wrapper.
Implicit-stream variants retain the synchronous API and its native host-blocking
behavior. Their RPC ids select a scope on the *same* server lane, so nested copies
and staging use that lane's per-thread default stream too.
"""

import re
from pathlib import Path
from cxxheaderparser.simple import parse_string
from emit import format_call_args, format_function_params

CLIENT_DECLARATIONS = """
typedef int CUresult;
CUresult cuMemPrefetchAsync(CUdeviceptr devPtr, size_t count, CUdevice dstDevice, CUstream hStream);
CUresult cuStreamBeginCapture(CUstream hStream);
CUresult cuStreamBeginCaptureToGraph(CUstream hStream, CUgraph hGraph, const CUgraphNode *dependencies, const CUgraphEdgeData *dependencyData, size_t numDependencies, CUstreamCaptureMode mode);
CUresult cuStreamGetCaptureInfo_v3(CUstream hStream, CUstreamCaptureStatus *captureStatus_out, cuuint64_t *id_out, CUgraph *graph_out, const CUgraphNode **dependencies_out, const CUgraphEdgeData **edgeData_out, size_t *numDependencies_out);
CUresult cuStreamGetCaptureInfo(CUstream hStream, CUstreamCaptureStatus *captureStatus_out, cuuint64_t *id_out);
CUresult cuStreamGetCaptureInfo_v2(CUstream hStream, CUstreamCaptureStatus *captureStatus_out, cuuint64_t *id_out, CUgraph *graph_out, const CUgraphNode **dependencies_out, size_t *numDependencies_out);
CUresult cuStreamUpdateCaptureDependencies(CUstream hStream, CUgraphNode *dependencies, size_t numDependencies, unsigned int flags);
CUresult cuStreamUpdateCaptureDependencies_v2(CUstream hStream, CUgraphNode *dependencies, const CUgraphEdgeData *dependencyData, size_t numDependencies, unsigned int flags);
"""


# The CUDA typedef catalog records these ABI changes independently of the
# compilation toolkit. Unversioned dlsym exports keep their literal old ABI.
STREAM_VERSIONS = {
    "cuStreamBeginCapture": [
        (0, "cuStreamBeginCapture"),
        (10010, "cuStreamBeginCapture_v2"),
    ],
    "cuStreamGetCaptureInfo": [
        (0, "cuStreamGetCaptureInfo"),
        (11030, "cuStreamGetCaptureInfo_v2"),
        (12030, "cuStreamGetCaptureInfo_v3"),
    ],
    "cuStreamUpdateCaptureDependencies": [
        (0, "cuStreamUpdateCaptureDependencies"),
        (12030, "cuStreamUpdateCaptureDependencies_v2"),
    ],
    "cuMemPrefetchAsync": [(0, "cuMemPrefetchAsync"), (12020, "cuMemPrefetchAsync_v2")],
}


class StreamRegistry:
    def __init__(self, header, sdk_functions, annotations, supported):
        annotated = {f.name.format(): f for f in annotations}
        functions = dict(annotated)
        functions.update({f.name.format(): f for f in sdk_functions})
        legacy = {
            f.name.format(): f
            for f in parse_string(CLIENT_DECLARATIONS).namespace.functions
        }
        functions.update(legacy)
        # The SDK supplies the current ABI spellings and stream semantics.
        variants = {
            name: kind.lower()
            for kind, name in re.findall(
                r"#define\s+\w+\s+__CUDA_API_(PTDS|PTSZ)\((\w+)\)",
                Path(header).read_text(),
            )
        }
        for name in (
            "cuMemPrefetchAsync",
            "cuStreamBeginCapture",
            "cuStreamGetCaptureInfo",
            "cuStreamGetCaptureInfo_v2",
            "cuStreamUpdateCaptureDependencies",
        ):
            variants[name] = "ptsz"
        self.entries = []
        for name, kind in sorted(variants.items()):
            if name not in annotated and name not in legacy:
                continue
            if name not in supported and name not in legacy:
                continue
            fn = functions[name]
            if fn.return_type.format() != "CUresult":
                continue
            doc = annotated[name].doxygen if name in annotated else ""
            guard = re.search(r"@guard ([^\n]+)", doc or "")
            self.entries.append(
                (name, kind, fn, guard.group(1).strip() if guard else None)
            )
        # cuMemcpy itself decomposes into routed HtoD/DtoH/DtoD operations.
        self.implicit = [
            e for e in self.entries if e[1] == "ptds" and e[0] != "cuMemcpy"
        ]

    def guarded(self, f, entry, emit):
        if entry[3]:
            f.write(f"#if {entry[3]}\n")
        emit()
        if entry[3]:
            f.write("#endif\n")

    def write_headers(self):
        with open("gen_cuda_streams.h", "w") as f:
            f.write(
                '// Generated by codegen.py. Do not edit.\n#pragma once\n#include <cuda.h>\n#include <cstring>\n#include "gen_rpc_ids.h"\n#include "cuda_stream_semantics.h"\n'
            )
            for e in self.entries:
                name, kind, fn, _ = e
                self.guarded(
                    f,
                    e,
                    lambda: f.write(
                        f'extern "C" CUresult CUDAAPI {name}_{kind}({", ".join(format_function_params(fn))});\n'
                    ),
                )
            f.write(
                "inline int lupine_implicit_stream_rpc(int operation) {\nif (!lupine_per_thread_default_stream) return operation;\nswitch (operation) {\n"
            )
            for e in self.implicit:
                self.guarded(
                    f, e, lambda: f.write(f"case RPC_{e[0]}: return RPC_{e[0]}_ptds;\n")
                )
            f.write("default: return operation;\n}\n}\n")
            f.write(
                "inline const char *lupine_implicit_stream_symbol(const char *name) {\nif (!lupine_per_thread_default_stream) return name;\n"
            )
            for e in self.entries:
                if e[1] == "ptds":
                    self.guarded(
                        f,
                        e,
                        lambda: f.write(
                            f'if (strcmp(name, "{e[0]}") == 0) return "{e[0]}_ptds";\n'
                        ),
                    )
            f.write("return name;\n}\n")
            f.write(
                "void *lupine_stream_function(const char *name, int version, bool per_thread);\n"
                "CUresult lupine_stream_add_callback_per_thread(CUstream stream, CUstreamCallback callback, void *user_data, unsigned int flags);\n"
            )
        with open("gen_cuda_streams_server.h", "w") as f:
            f.write(
                '// Generated by codegen.py. Do not edit.\n#pragma once\n#include "cuda_stream_semantics.h"\n'
            )
            for e in self.entries:
                if e[1] != "ptds":
                    continue
                name, _, fn, _ = e
                params = ", ".join(format_function_params(fn))
                args = ", ".join(format_call_args(fn))
                self.guarded(
                    f,
                    e,
                    lambda: f.write(
                        f'extern "C" CUresult CUDAAPI {name}_ptds({params});\n'
                        f"inline CUresult lupine_implicit_{name}({params}) {{\nreturn lupine_per_thread_default_stream ? {name}_ptds({args}) : {name}({args});\n}}\n"
                    ),
                )

    def write_client_wrappers(self, f):
        for fn in parse_string(CLIENT_DECLARATIONS).namespace.functions:
            name = fn.name.format()
            f.write(
                f'#ifdef {name}\n#undef {name}\n#endif\nextern "C" CUresult CUDAAPI {name}({", ".join(format_function_params(fn))});\n'
            )
        for e in self.entries:
            name, kind, fn, _ = e
            params = ", ".join(format_function_params(fn))

            def emit():
                f.write(f'extern "C" CUresult CUDAAPI {name}_{kind}({params}) {{\n')
                if name == "cuStreamAddCallback":
                    f.write(
                        "return lupine_stream_add_callback_per_thread(hStream, callback, userData, flags);\n}\n"
                    )
                    return
                if kind == "ptds":
                    f.write("lupine_per_thread_stream_scope scope;\n")
                for p in fn.parameters:
                    if p.type.format() == "CUstream":
                        f.write(f"{p.name} = lupine_per_thread_stream({p.name});\n")
                    elif p.type.format().replace(" ", "") in (
                        "constCUlaunchConfig*",
                        "CUDA_GRAPH_INSTANTIATE_PARAMS*",
                    ):
                        field = (
                            "hStream"
                            if "CUlaunchConfig" in p.type.format()
                            else "hUploadStream"
                        )
                        typ = (
                            "CUlaunchConfig"
                            if "CUlaunchConfig" in p.type.format()
                            else "CUDA_GRAPH_INSTANTIATE_PARAMS"
                        )
                        if typ == "CUDA_GRAPH_INSTANTIATE_PARAMS":
                            f.write(f"auto *original_{p.name} = {p.name};\n")
                        f.write(
                            f"{typ} adjusted;\nif ({p.name}) {{ adjusted = *{p.name}; adjusted.{field} = lupine_per_thread_stream(adjusted.{field}); {p.name} = &adjusted; }}\n"
                        )
                args = ", ".join(format_call_args(fn))
                target = name
                if name == "cuStreamBeginCapture":
                    target = "cuStreamBeginCapture_v2"
                    args += ", CU_STREAM_CAPTURE_MODE_GLOBAL"
                elif name == "cuStreamUpdateCaptureDependencies":
                    target = "cuStreamUpdateCaptureDependencies_v2"
                    args = "hStream, dependencies, nullptr, numDependencies, flags"
                if name == "cuGraphInstantiateWithParams":
                    f.write(
                        f"CUresult result = {target}({args});\nif (original_instantiateParams) {{\nadjusted.hUploadStream = original_instantiateParams->hUploadStream;\n*original_instantiateParams = adjusted;\n}}\nreturn result;\n}}\n"
                    )
                else:
                    f.write(f"return {target}({args});\n}}\n")

            self.guarded(f, e, emit)

        self.write_resolver(f)

    def write_resolver(self, f):
        f.write(
            "void *lupine_stream_function(const char *name, int version, bool per_thread) {\n"
        )
        entries = {e[0]: e for e in self.entries}
        for public, choices in STREAM_VERSIONS.items():
            f.write(f'if (strcmp(name, "{public}") == 0) {{\n')
            for since, target in reversed(choices):
                if target not in entries:
                    continue
                e = entries[target]
                self.guarded(
                    f,
                    e,
                    lambda: f.write(
                        f"if (version >= {since}) return per_thread ? (void *)&{target}_{e[1]} : (void *)&{target};\n"
                    ),
                )
            f.write("}\n")
        for e in self.entries:
            name, kind, _, _ = e
            public = re.sub(r"_v[0-9]+$", "", name)
            names = (
                [name]
                if public in STREAM_VERSIONS
                else list(dict.fromkeys([name, public]))
            )
            if name == public and public in STREAM_VERSIONS:
                continue
            condition = " || ".join(f'strcmp(name, "{key}") == 0' for key in names)
            self.guarded(
                f,
                e,
                lambda: f.write(
                    f"if ({condition}) return per_thread ? (void *)&{name}_{kind} : (void *)&{name};\n"
                ),
            )
        f.write("return nullptr;\n}\n")

    def write_map_entries(self, f):
        for e in self.entries:
            alias = e[0] + "_" + e[1]
            self.guarded(f, e, lambda: f.write(f'{{"{alias}", (void *){alias}}},\n'))

    def write_server_wrappers(self, f):
        for e in self.implicit:
            name = e[0]
            self.guarded(
                f,
                e,
                lambda: f.write(
                    f"int handle_{name}(conn_t *conn);\nint handle_{name}_ptds(conn_t *conn) {{\nlupine_per_thread_stream_scope scope;\nreturn handle_{name}(conn);\n}}\n"
                ),
            )

    def add_server_bindings(self, bindings, binding_type):
        for name, _, _, guard in self.implicit:
            bindings.append(
                binding_type(name + "_ptds", "CUDA", "handle_" + name + "_ptds", guard)
            )

    def rewrite_generated_calls(self):
        path = Path("gen_cuda_client.cpp")
        source = path.read_text()
        for name, _, _, _ in self.implicit:
            source = re.sub(
                r"\bRPC_" + name + r"\b",
                f"lupine_implicit_stream_rpc(RPC_{name})",
                source,
            )
        path.write_text(source)
        path = Path("gen_cuda_server.cpp")
        source = path.read_text()
        for name, _, _, _ in self.implicit:
            source = re.sub(
                r"(?<!\w)" + name + r"\(", "lupine_implicit_" + name + "(", source
            )
        path.write_text(source)
