// Generated by codegen.py. Do not edit by hand.

int handle_cufftCreate(conn_t *conn);
int handle_cufftDestroy(conn_t *conn);
int handle_cufftEstimate1d(conn_t *conn);
int handle_cufftEstimate2d(conn_t *conn);
int handle_cufftEstimate3d(conn_t *conn);
int handle_cufftEstimateMany(conn_t *conn);
int handle_cufftExecC2C(conn_t *conn);
int handle_cufftExecC2R(conn_t *conn);
int handle_cufftExecD2Z(conn_t *conn);
int handle_cufftExecR2C(conn_t *conn);
int handle_cufftExecZ2D(conn_t *conn);
int handle_cufftExecZ2Z(conn_t *conn);
#if CUFFT_VERSION >= 11200
int handle_cufftGetPlanPropertyInt64(conn_t *conn);
#endif

int handle_cufftGetProperty(conn_t *conn);
int handle_cufftGetSize(conn_t *conn);
int handle_cufftGetSize1d(conn_t *conn);
int handle_cufftGetSize2d(conn_t *conn);
int handle_cufftGetSize3d(conn_t *conn);
int handle_cufftGetSizeMany(conn_t *conn);
int handle_cufftGetSizeMany64(conn_t *conn);
int handle_cufftGetVersion(conn_t *conn);
int handle_cufftMakePlan1d(conn_t *conn);
int handle_cufftMakePlan2d(conn_t *conn);
int handle_cufftMakePlan3d(conn_t *conn);
int handle_cufftMakePlanMany(conn_t *conn);
int handle_cufftMakePlanMany64(conn_t *conn);
int handle_cufftPlan1d(conn_t *conn);
int handle_cufftPlan2d(conn_t *conn);
int handle_cufftPlan3d(conn_t *conn);
int handle_cufftPlanMany(conn_t *conn);
#if CUFFT_VERSION >= 11200
int handle_cufftResetPlanProperty(conn_t *conn);
#endif

int handle_cufftSetAutoAllocation(conn_t *conn);
#if CUFFT_VERSION >= 11200
int handle_cufftSetPlanPropertyInt64(conn_t *conn);
#endif

int handle_cufftSetStream(conn_t *conn);
int handle_cufftSetWorkArea(conn_t *conn);
int handle_cufftXtClearCallback(conn_t *conn);
int handle_cufftXtExec(conn_t *conn);
int handle_cufftXtExecDescriptor(conn_t *conn);
int handle_cufftXtExecDescriptorC2C(conn_t *conn);
int handle_cufftXtExecDescriptorC2R(conn_t *conn);
int handle_cufftXtExecDescriptorD2Z(conn_t *conn);
int handle_cufftXtExecDescriptorR2C(conn_t *conn);
int handle_cufftXtExecDescriptorZ2D(conn_t *conn);
int handle_cufftXtExecDescriptorZ2Z(conn_t *conn);
int handle_cufftXtGetSizeMany(conn_t *conn);
int handle_cufftXtMakePlanMany(conn_t *conn);
int handle_cufftXtQueryPlan(conn_t *conn);
int handle_cufftXtSetCallbackSharedSize(conn_t *conn);
int handle_cufftXtSetGPUs(conn_t *conn);
int handle_cufftXtSetWorkAreaPolicy(conn_t *conn);
