// Generated by codegen.py. Do not edit by hand.

int handle_nppiRGBToYUV_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToYUV_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV_8u_AC4R(conn_t *conn);
#endif
int handle_nppiRGBToYUV_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYUV_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYUV_8u_AC4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV_8u_AC4P4R(conn_t *conn);
#endif
int handle_nppiBGRToYUV_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYUV_8u_C3R(conn_t *conn);
#endif
int handle_nppiBGRToYUV_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYUV_8u_AC4R(conn_t *conn);
#endif
int handle_nppiBGRToYUV_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYUV_8u_P3R(conn_t *conn);
#endif
int handle_nppiBGRToYUV_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYUV_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYUV_8u_AC4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYUV_8u_AC4P4R(conn_t *conn);
#endif
int handle_nppiYUVToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiYUVToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiYUVToRGB_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGB_8u_P3R(conn_t *conn);
#endif
int handle_nppiYUVToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUVToRGBBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGBBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiYUVToRGBBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGBBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUVToRGBBatch_8u_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGBBatch_8u_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYUVToRGBBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToRGBBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYUVToBGR_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGR_8u_C3R(conn_t *conn);
#endif
int handle_nppiYUVToBGR_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGR_8u_AC4R(conn_t *conn);
#endif
int handle_nppiYUVToBGR_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGR_8u_P3R(conn_t *conn);
#endif
int handle_nppiYUVToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUVToBGRBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGRBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiYUVToBGRBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGRBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUVToBGRBatch_8u_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGRBatch_8u_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYUVToBGRBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUVToBGRBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiRGBToYUV422_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV422_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiRGBToYUV422_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV422_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYUV422_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV422_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiYUV422ToRGB_8u_C2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToRGB_8u_C2C3R(conn_t *conn);
#endif
int handle_nppiYUV422ToRGB_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToRGB_8u_P3R(conn_t *conn);
#endif
int handle_nppiYUV422ToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV422ToRGB_8u_P3AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToRGB_8u_P3AC4R(conn_t *conn);
#endif
int handle_nppiYUV422ToRGBBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToRGBBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV422ToRGBBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToRGBBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYUV422ToBGRBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToBGRBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV422ToBGRBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV422ToBGRBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiRGBToYUV420_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV420_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYUV420_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYUV420_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiYUV420ToRGB_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToRGB_8u_P3R(conn_t *conn);
#endif
int handle_nppiYUV420ToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV420ToRGB_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToRGB_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiYUV420ToRGB_8u_P3AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToRGB_8u_P3AC4R(conn_t *conn);
#endif
int handle_nppiYUV420ToRGBBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToRGBBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV420ToRGBBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToRGBBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiNV12ToRGB_8u_P2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToRGB_8u_P2C3R(conn_t *conn);
#endif
int handle_nppiNV12ToRGB_709HDTV_8u_P2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToRGB_709HDTV_8u_P2C3R(conn_t *conn);
#endif
int handle_nppiNV12ToRGB_709CSC_8u_P2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToRGB_709CSC_8u_P2C3R(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiNV12ToRGB_601_8u_P2C3R_Ctx(conn_t *conn);
#endif
int handle_nppiNV21ToRGB_8u_P2C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV21ToRGB_8u_P2C4R(conn_t *conn);
#endif
int handle_nppiBGRToYUV420_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYUV420_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiYUV420ToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV420ToBGR_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToBGR_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiYUV420ToBGRBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToBGRBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYUV420ToBGRBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYUV420ToBGRBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiNV12ToBGR_8u_P2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToBGR_8u_P2C3R(conn_t *conn);
#endif
int handle_nppiNV12ToBGR_709HDTV_8u_P2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToBGR_709HDTV_8u_P2C3R(conn_t *conn);
#endif
int handle_nppiNV12ToBGR_709CSC_8u_P2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToBGR_709CSC_8u_P2C3R(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiNV12ToBGR_601_8u_P2C3R_Ctx(conn_t *conn);
#endif
int handle_nppiNV21ToBGR_8u_P2C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV21ToBGR_8u_P2C4R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr_8u_AC4R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGB_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGB_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGB_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGB_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGBBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGBBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGBBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGBBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToRGBBatch_8u_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGBBatch_8u_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYCbCrToRGBBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToRGBBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYCbCrToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToBGR_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGR_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiYCbCrToBGRBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGRBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToBGRBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGRBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToBGRBatch_8u_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGRBatch_8u_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYCbCrToBGRBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGRBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYCbCrToBGR_709CSC_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGR_709CSC_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCrToBGR_709CSC_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCrToBGR_709CSC_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr422_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr422_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr422_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr422_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGB_8u_C2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGB_8u_C2C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGB_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGB_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGBBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGBBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGBBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGBBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiRGBToYCrCb422_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCrCb422_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiRGBToYCrCb422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCrCb422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCrCb422ToRGB_8u_C2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb422ToRGB_8u_C2C3R(conn_t *conn);
#endif
int handle_nppiYCrCb422ToRGB_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb422ToRGB_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr422_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr422_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr422_8u_AC4C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr422_8u_AC4C2R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr422_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr422_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr422_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr422_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGR_8u_C2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGR_8u_C2C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGR_8u_C2C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGR_8u_C2C4R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGRBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGRBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGRBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGRBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiRGBToCbYCr422_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToCbYCr422_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiRGBToCbYCr422Gamma_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToCbYCr422Gamma_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToRGB_8u_C2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToRGB_8u_C2C3R(conn_t *conn);
#endif
int handle_nppiBGRToCbYCr422_8u_AC4C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToCbYCr422_8u_AC4C2R(conn_t *conn);
#endif
int handle_nppiBGRToCbYCr422_709HDTV_8u_C3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToCbYCr422_709HDTV_8u_C3C2R(conn_t *conn);
#endif
int handle_nppiBGRToCbYCr422_709HDTV_8u_AC4C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToCbYCr422_709HDTV_8u_AC4C2R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToBGR_8u_C2C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToBGR_8u_C2C4R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToBGR_709HDTV_8u_C2C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToBGR_709HDTV_8u_C2C3R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToBGR_709HDTV_8u_C2C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToBGR_709HDTV_8u_C2C4R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr420_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr420_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToRGBBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToRGBBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToRGBBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToRGBBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiRGBToYCrCb420_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCrCb420_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiYCrCb420ToRGB_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb420ToRGB_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_709CSC_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_709CSC_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_709CSC_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_709CSC_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_709HDTV_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_709HDTV_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCrCb420_709CSC_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCrCb420_709CSC_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCrCb420_709CSC_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCrCb420_709CSC_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGR_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGR_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGRBatch_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGRBatch_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGRBatch_8u_P3C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGRBatch_8u_P3C3R_Advanced(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGR_709CSC_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGR_709CSC_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGR_709HDTV_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGR_709HDTV_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiBGRToYCrCb420_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCrCb420_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCrCb420_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCrCb420_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr411_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr411_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr411_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr411_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr411_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr411_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr411_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr411_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr_8u_AC4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr_8u_AC4P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr_8u_AC4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr_8u_AC4P4R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToBGR_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToBGR_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToRGB_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToRGB_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToRGB_8u_P3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToRGB_8u_P3C4R(conn_t *conn);
#endif
int handle_nppiRGBToXYZ_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToXYZ_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToXYZ_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToXYZ_8u_AC4R(conn_t *conn);
#endif
int handle_nppiXYZToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiXYZToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiXYZToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiXYZToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiRGBToLUV_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToLUV_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToLUV_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToLUV_8u_AC4R(conn_t *conn);
#endif
int handle_nppiLUVToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUVToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiLUVToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUVToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiBGRToLab_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToLab_8u_C3R(conn_t *conn);
#endif
int handle_nppiLabToBGR_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLabToBGR_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToYCC_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCC_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToYCC_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCC_8u_AC4R(conn_t *conn);
#endif
int handle_nppiYCCToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCCToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiYCCToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCCToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiYCCKToCMYK_JPEG_601_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCCKToCMYK_JPEG_601_8u_P4R(conn_t *conn);
#endif
int handle_nppiCMYKOrYCCKToRGB_JPEG_8u_P4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCMYKOrYCCKToRGB_JPEG_8u_P4P3R(conn_t *conn);
#endif
int handle_nppiCMYKOrYCCKToRGB_JPEG_8u_P4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCMYKOrYCCKToRGB_JPEG_8u_P4C3R(conn_t *conn);
#endif
int handle_nppiCMYKOrYCCKToBGR_JPEG_8u_P4P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCMYKOrYCCKToBGR_JPEG_8u_P4P3R(conn_t *conn);
#endif
int handle_nppiCMYKOrYCCKToBGR_JPEG_8u_P4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCMYKOrYCCKToBGR_JPEG_8u_P4C3R(conn_t *conn);
#endif
int handle_nppiRGBToHLS_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToHLS_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToHLS_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToHLS_8u_AC4R(conn_t *conn);
#endif
int handle_nppiHLSToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiHLSToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_AC4R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_AC4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_AC4P4R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_AP4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_AP4C4R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_P3R(conn_t *conn);
#endif
int handle_nppiBGRToHLS_8u_AP4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToHLS_8u_AP4R(conn_t *conn);
#endif
int handle_nppiHLSToBGR_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToBGR_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiHLSToBGR_8u_AC4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToBGR_8u_AC4P4R(conn_t *conn);
#endif
int handle_nppiHLSToBGR_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToBGR_8u_P3R(conn_t *conn);
#endif
int handle_nppiHLSToBGR_8u_AP4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToBGR_8u_AP4R(conn_t *conn);
#endif
int handle_nppiHLSToBGR_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToBGR_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiHLSToBGR_8u_AP4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHLSToBGR_8u_AP4C4R(conn_t *conn);
#endif
int handle_nppiRGBToHSV_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToHSV_8u_C3R(conn_t *conn);
#endif
int handle_nppiRGBToHSV_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToHSV_8u_AC4R(conn_t *conn);
#endif
int handle_nppiHSVToRGB_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHSVToRGB_8u_C3R(conn_t *conn);
#endif
int handle_nppiHSVToRGB_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiHSVToRGB_8u_AC4R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr420_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr420_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr422_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr422_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr411_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr411_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr444_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr444_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr422_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr422_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr411_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr411_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr444_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr444_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToRGB_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToRGB_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGB_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGB_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToRGB_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToRGB_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr444ToRGB_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr444ToRGB_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGR_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGR_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGR_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGR_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToBGR_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToBGR_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr444ToBGR_JPEG_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr444ToBGR_JPEG_8u_P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr420_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr420_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr422_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr422_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr411_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr411_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiRGBToYCbCr444_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToYCbCr444_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr420_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr420_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr422_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr422_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr411_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr411_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiBGRToYCbCr444_JPEG_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiBGRToYCbCr444_JPEG_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToRGB_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToRGB_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToRGB_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToRGB_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToRGB_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToRGB_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr444ToRGB_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr444ToRGB_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToBGR_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToBGR_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToBGR_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToBGR_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToBGR_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToBGR_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiYCbCr444ToBGR_JPEG_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr444ToBGR_JPEG_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiRGBToGray_8u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_8u_C3C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_8u_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_8u_AC4C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_16u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_16u_C3C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_16u_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_16u_AC4C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_16s_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_16s_C3C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_16s_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_16s_AC4C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_32f_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_32f_C3C1R(conn_t *conn);
#endif
int handle_nppiRGBToGray_32f_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRGBToGray_32f_AC4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_8u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_8u_C3C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_8u_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_8u_AC4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_8u_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_8u_C4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_16u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_16u_C3C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_16u_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_16u_AC4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_16u_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_16u_C4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_16s_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_16s_C3C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_16s_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_16s_AC4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_16s_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_16s_C4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_32f_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_32f_C3C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_32f_AC4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_32f_AC4C1R(conn_t *conn);
#endif
int handle_nppiColorToGray_32f_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorToGray_32f_C4C1R(conn_t *conn);
#endif
int handle_nppiGradientColorToGray_8u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGradientColorToGray_8u_C3C1R(conn_t *conn);
#endif
int handle_nppiGradientColorToGray_16u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGradientColorToGray_16u_C3C1R(conn_t *conn);
#endif
int handle_nppiGradientColorToGray_16s_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGradientColorToGray_16s_C3C1R(conn_t *conn);
#endif
int handle_nppiGradientColorToGray_32f_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGradientColorToGray_32f_C3C1R(conn_t *conn);
#endif
int handle_nppiCFAToRGB_8u_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCFAToRGB_8u_C1C3R(conn_t *conn);
#endif
int handle_nppiCFAToRGBA_8u_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCFAToRGBA_8u_C1AC4R(conn_t *conn);
#endif
int handle_nppiCFAToRGB_16u_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCFAToRGB_16u_C1C3R(conn_t *conn);
#endif
int handle_nppiCFAToRGBA_16u_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCFAToRGBA_16u_C1AC4R(conn_t *conn);
#endif
#if NPP_VERSION >= 12300
int handle_nppiCFAToRGB_32u_C1C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12300
int handle_nppiCFAToRGBA_32u_C1AC4R_Ctx(conn_t *conn);
#endif
int handle_nppiYCbCr420ToYCbCr411_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToYCbCr411_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToYCbCr411_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToYCbCr411_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCrCb422_8u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCrCb422_8u_C2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCrCb422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCrCb422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToCbYCr422_8u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToCbYCr422_8u_C2R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToYCbCr411_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToYCbCr411_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr420_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr420_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr420_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr420_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr420_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr420_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr420_8u_C2P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr420_8u_C2P2R(conn_t *conn);
#endif
int handle_nppiYCrCb420ToYCbCr422_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb420ToYCbCr422_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCrCb420ToYCbCr422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb420ToYCbCr422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCrCb420_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCrCb420_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr411_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr411_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr411_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr411_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr411_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr411_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr422ToYCbCr411_8u_C2P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr422ToYCbCr411_8u_C2P2R(conn_t *conn);
#endif
int handle_nppiYCrCb422ToYCbCr422_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb422ToYCbCr422_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCrCb422ToYCbCr420_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb422ToYCbCr420_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCrCb422ToYCbCr411_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb422ToYCbCr411_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToYCbCr422_8u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToYCbCr422_8u_C2R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToYCbCr422_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToYCbCr422_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToYCbCr420_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToYCbCr420_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToYCbCr420_8u_C2P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToYCbCr420_8u_C2P2R(conn_t *conn);
#endif
int handle_nppiCbYCr422ToYCrCb420_8u_C2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCbYCr422ToYCrCb420_8u_C2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr420_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToYCbCr422_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToYCbCr422_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToYCbCr422_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToYCbCr422_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToYCbCr422_8u_P2C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToYCbCr422_8u_P2C2R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToCbYCr422_8u_P2C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToCbYCr422_8u_P2C2R(conn_t *conn);
#endif
int handle_nppiYCbCr420ToYCrCb420_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr420ToYCrCb420_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCrCb420ToCbYCr422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb420ToCbYCr422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCrCb420ToYCbCr420_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb420ToYCbCr420_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCrCb420ToYCbCr411_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCrCb420ToYCbCr411_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr411_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr411_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr422_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr422_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr422_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr422_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr422_8u_P2C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr422_8u_P2C2R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCrCb422_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCrCb422_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCrCb422_8u_P3C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCrCb422_8u_P3C2R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr420_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr420_8u_P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr420_8u_P3P2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr420_8u_P3P2R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCbCr420_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCbCr420_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiYCbCr411ToYCrCb420_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiYCbCr411ToYCrCb420_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiNV12ToYUV420_8u_P2P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiNV12ToYUV420_8u_P2P3R(conn_t *conn);
#endif
int handle_nppiGammaFwd_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaFwd_8u_C3R(conn_t *conn);
#endif
int handle_nppiGammaFwd_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaFwd_8u_C3IR(conn_t *conn);
#endif
int handle_nppiGammaFwd_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaFwd_8u_AC4R(conn_t *conn);
#endif
int handle_nppiGammaFwd_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaFwd_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiGammaFwd_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaFwd_8u_P3R(conn_t *conn);
#endif
int handle_nppiGammaFwd_8u_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaFwd_8u_IP3R(conn_t *conn);
#endif
int handle_nppiGammaInv_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaInv_8u_C3R(conn_t *conn);
#endif
int handle_nppiGammaInv_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaInv_8u_C3IR(conn_t *conn);
#endif
int handle_nppiGammaInv_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaInv_8u_AC4R(conn_t *conn);
#endif
int handle_nppiGammaInv_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaInv_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiGammaInv_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaInv_8u_P3R(conn_t *conn);
#endif
int handle_nppiGammaInv_8u_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGammaInv_8u_IP3R(conn_t *conn);
#endif
int handle_nppiCompColorKey_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompColorKey_8u_C1R(conn_t *conn);
#endif
int handle_nppiCompColorKey_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompColorKey_8u_C3R(conn_t *conn);
#endif
int handle_nppiCompColorKey_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompColorKey_8u_C4R(conn_t *conn);
#endif
int handle_nppiAlphaCompColorKey_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiAlphaCompColorKey_8u_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C1R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C2R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C2IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C2IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32fC_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32fC_8u_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist32fC_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32fC_8u_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_P3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8u_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8u_IP3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C1R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C2R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C2IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C2IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_P3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_8s_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_8s_IP3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_C1R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_C2R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_C2IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_C2IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_C3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_P3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16u_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16u_IP3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_C1R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_C2R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_C2IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_C2IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_C3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_P3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16s_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16s_IP3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C1R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C2R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C2IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C2IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C3R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist32f_16f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32f_16f_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist32fC_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32fC_16f_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist32fC_16f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist32fC_16f_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C1R(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C2R(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C2IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C2IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C3R(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32fC_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32fC_C4R(conn_t *conn);
#endif
int handle_nppiColorTwist_32fC_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32fC_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_P3R(conn_t *conn);
#endif
int handle_nppiColorTwist_32f_IP3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwist_32f_IP3R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_C1R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_C3R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_C4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32fC_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32fC_8u_C4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32fC_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32fC_8u_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_C1R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_C3R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_C4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_AC4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32fC_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32fC_C4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch_32fC_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch_32fC_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_16f_C1R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_16f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_16f_C1IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_16f_C3R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_16f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_16f_C3IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_16f_C4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32f_16f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32f_16f_C4IR(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32fC_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32fC_16f_C4R(conn_t *conn);
#endif
int handle_nppiColorTwistBatch32fC_16f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiColorTwistBatch32fC_16f_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_C1R(conn_t *conn);
#endif
int handle_nppiLUT_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_C3R(conn_t *conn);
#endif
int handle_nppiLUT_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_C1R(conn_t *conn);
#endif
int handle_nppiLUT_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_C3R(conn_t *conn);
#endif
int handle_nppiLUT_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_16u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_C1R(conn_t *conn);
#endif
int handle_nppiLUT_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_C3R(conn_t *conn);
#endif
int handle_nppiLUT_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_C4R(conn_t *conn);
#endif
int handle_nppiLUT_16s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_C1R(conn_t *conn);
#endif
int handle_nppiLUT_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_C3R(conn_t *conn);
#endif
int handle_nppiLUT_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_C4R(conn_t *conn);
#endif
int handle_nppiLUT_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Linear_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Linear_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_C1R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_C1IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_C3R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_C3IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_C4IR(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Cubic_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Cubic_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiLUT_Trilinear_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Trilinear_8u_C4R(conn_t *conn);
#endif
int handle_nppiLUT_Trilinear_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Trilinear_8u_AC4R(conn_t *conn);
#endif
int handle_nppiLUT_Trilinear_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUT_Trilinear_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiLUTPalette_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_8u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_8u24u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_8u24u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_8u32u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_8u32u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_8u_C3R(conn_t *conn);
#endif
int handle_nppiLUTPalette_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_8u_C4R(conn_t *conn);
#endif
int handle_nppiLUTPalette_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_8u_AC4R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u8u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u24u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u24u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u32u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u32u_C1R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u_C3R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u_C4R(conn_t *conn);
#endif
int handle_nppiLUTPalette_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPalette_16u_AC4R(conn_t *conn);
#endif
int handle_nppiLUTPaletteSwap_8u_C3A0C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPaletteSwap_8u_C3A0C4R(conn_t *conn);
#endif
int handle_nppiLUTPaletteSwap_16u_C3A0C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiLUTPaletteSwap_16u_C3A0C4R(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV420_8u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV420_16u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV420_8u_ColorTwist32f_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV420_16u_ColorTwist32f_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV422_8u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV422_16u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV422_8u_ColorTwist32f_C3C2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV422_16u_ColorTwist32f_C3C2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV422_8u_ColorTwist32f_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToYUV422_16u_ColorTwist32f_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToNV12_8u_ColorTwist32f_C3P2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToNV12_16u_ColorTwist32f_C3P2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToNV12_8u_ColorTwist32f_P3P2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiRGBToNV12_16u_ColorTwist32f_P3P2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_8u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_16u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_8u_ColorTwist32f_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_16u_ColorTwist32f_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_8u_ColorTwist32f_P3C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_16u_ColorTwist32f_P3C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_8u_ColorTwist32f_P3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV420ToRGB_16u_ColorTwist32f_P3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_8u_ColorTwist32f_C2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_16u_ColorTwist32f_C2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_8u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_16u_ColorTwist32f_P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_8u_ColorTwist32f_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_16u_ColorTwist32f_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_8u_ColorTwist32f_P3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiYUV422ToRGB_16u_ColorTwist32f_P3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiNV12ToRGB_8u_ColorTwist32f_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12200
int handle_nppiNV12ToRGB_16u_ColorTwist32f_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiRGB_8u_ToUYVP_10u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiRGB_8u_ToUYVP_10u_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_8u_ToUYVP_10u_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiRGBA_8u_ToUYVP_10u_AC4C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiRGB_16u_ToUYVP_10u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiRGB_16u_ToUYVP_10u_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiRGBA_16u_ToUYVP_10u_AC4C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_16f_ToUYVP_10u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_16f_ToUYVP_10u_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGBA_16f_ToUYVP_10u_AC4C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiUYVP_10u_ToRGB_8u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVP_10u_ToRGB_8u_C3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVP_10u_ToRGB_8u_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiUYVP_10u_ToRGB_16u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13003
int handle_nppiUYVP_10u_ToRGB_16u_C3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVP_10u_ToRGB_16u_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVP_10u_ToRGB_16f_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVP_10u_ToRGBA_16f_C3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVP_10u_ToRGB_16f_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_8u_ToUYVY_8u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_8u_ToUYVY_8u_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGBA_8u_ToUYVY_8u_AC4C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_16u_ToUYVY16_16u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGB_16u_ToUYVY16_16u_P3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGBA_16u_ToUYVY16_16u_AC4C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVY_8u_ToRGB_8u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVY_8u_ToRGB_8u_C3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVY_8u_ToRGB_8u_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVY16_16u_ToRGB_16u_C3C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVY16_16u_ToRGB_16u_C3AC4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiUYVY16_16u_ToRGB_16u_C3P3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiNV12ToRGB_8u_P2C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiNV12ToBGR_8u_P2C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiNV12ToRGB_BT2020_8u_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiNV12ToBGR_BT2020_8u_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiP010ToRGB_8u_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiP010ToRGB_8u_P2C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiP010ToRGB_16u_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiP010ToRGB_16u_P2C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiP016ToRGB_16u_P2C3R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiP016ToRGB_16u_P2C4R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGBToNV12_8u_C3P2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiRGBToNV12_8u_P3P2R_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 13200
int handle_nppiYUV420ToNV12_8u_P3P2R_Ctx(conn_t *conn);
#endif
