// Generated by codegen.py. Do not edit by hand.

int handle_curandCreateGenerator(conn_t *conn);
int handle_curandCreateGeneratorHost(conn_t *conn);
int handle_curandDestroyGenerator(conn_t *conn);
int handle_curandGetVersion(conn_t *conn);
int handle_curandGetProperty(conn_t *conn);
int handle_curandSetStream(conn_t *conn);
int handle_curandSetPseudoRandomGeneratorSeed(conn_t *conn);
int handle_curandSetGeneratorOffset(conn_t *conn);
int handle_curandSetGeneratorOrdering(conn_t *conn);
int handle_curandSetQuasiRandomGeneratorDimensions(conn_t *conn);
int handle_curandGenerate(conn_t *conn);
int handle_curandGenerateLongLong(conn_t *conn);
int handle_curandGenerateUniform(conn_t *conn);
int handle_curandGenerateUniformDouble(conn_t *conn);
int handle_curandGenerateNormal(conn_t *conn);
int handle_curandGenerateNormalDouble(conn_t *conn);
int handle_curandGenerateLogNormal(conn_t *conn);
int handle_curandGenerateLogNormalDouble(conn_t *conn);
int handle_curandCreatePoissonDistribution(conn_t *conn);
int handle_curandDestroyDistribution(conn_t *conn);
int handle_curandGeneratePoisson(conn_t *conn);
int handle_curandGeneratePoissonMethod(conn_t *conn);
int handle_curandGenerateSeeds(conn_t *conn);
