// Generated by codegen.py. Do not edit by hand.

int handle_nppiSet_8s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8s_C1R(conn_t *conn);
#endif
int handle_nppiSet_8s_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8s_C2R(conn_t *conn);
#endif
int handle_nppiSet_8s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8s_C3R(conn_t *conn);
#endif
int handle_nppiSet_8s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8s_C4R(conn_t *conn);
#endif
int handle_nppiSet_8s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8s_AC4R(conn_t *conn);
#endif
int handle_nppiSet_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C1R(conn_t *conn);
#endif
int handle_nppiSet_8u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C2R(conn_t *conn);
#endif
int handle_nppiSet_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C3R(conn_t *conn);
#endif
int handle_nppiSet_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C4R(conn_t *conn);
#endif
int handle_nppiSet_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_AC4R(conn_t *conn);
#endif
int handle_nppiSet_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C1R(conn_t *conn);
#endif
int handle_nppiSet_16u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C2R(conn_t *conn);
#endif
int handle_nppiSet_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C3R(conn_t *conn);
#endif
int handle_nppiSet_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C4R(conn_t *conn);
#endif
int handle_nppiSet_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_AC4R(conn_t *conn);
#endif
int handle_nppiSet_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C1R(conn_t *conn);
#endif
int handle_nppiSet_16s_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C2R(conn_t *conn);
#endif
int handle_nppiSet_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C3R(conn_t *conn);
#endif
int handle_nppiSet_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C4R(conn_t *conn);
#endif
int handle_nppiSet_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_AC4R(conn_t *conn);
#endif
int handle_nppiSet_16sc_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16sc_C1R(conn_t *conn);
#endif
int handle_nppiSet_16sc_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16sc_C2R(conn_t *conn);
#endif
int handle_nppiSet_16sc_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16sc_C3R(conn_t *conn);
#endif
int handle_nppiSet_16sc_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16sc_C4R(conn_t *conn);
#endif
int handle_nppiSet_16sc_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16sc_AC4R(conn_t *conn);
#endif
int handle_nppiSet_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C1R(conn_t *conn);
#endif
int handle_nppiSet_32s_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C2R(conn_t *conn);
#endif
int handle_nppiSet_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C3R(conn_t *conn);
#endif
int handle_nppiSet_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C4R(conn_t *conn);
#endif
int handle_nppiSet_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_AC4R(conn_t *conn);
#endif
int handle_nppiSet_32u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32u_C1R(conn_t *conn);
#endif
int handle_nppiSet_32u_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32u_C2R(conn_t *conn);
#endif
int handle_nppiSet_32u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32u_C3R(conn_t *conn);
#endif
int handle_nppiSet_32u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32u_C4R(conn_t *conn);
#endif
int handle_nppiSet_32u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32u_AC4R(conn_t *conn);
#endif
int handle_nppiSet_32sc_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32sc_C1R(conn_t *conn);
#endif
int handle_nppiSet_32sc_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32sc_C2R(conn_t *conn);
#endif
int handle_nppiSet_32sc_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32sc_C3R(conn_t *conn);
#endif
int handle_nppiSet_32sc_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32sc_C4R(conn_t *conn);
#endif
int handle_nppiSet_32sc_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32sc_AC4R(conn_t *conn);
#endif
int handle_nppiSet_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16f_C1R(conn_t *conn);
#endif
int handle_nppiSet_16f_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16f_C2R(conn_t *conn);
#endif
int handle_nppiSet_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16f_C3R(conn_t *conn);
#endif
int handle_nppiSet_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16f_C4R(conn_t *conn);
#endif
int handle_nppiSet_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C1R(conn_t *conn);
#endif
int handle_nppiSet_32f_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C2R(conn_t *conn);
#endif
int handle_nppiSet_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C3R(conn_t *conn);
#endif
int handle_nppiSet_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C4R(conn_t *conn);
#endif
int handle_nppiSet_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_AC4R(conn_t *conn);
#endif
int handle_nppiSet_32fc_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32fc_C1R(conn_t *conn);
#endif
int handle_nppiSet_32fc_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32fc_C2R(conn_t *conn);
#endif
int handle_nppiSet_32fc_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32fc_C3R(conn_t *conn);
#endif
int handle_nppiSet_32fc_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32fc_C4R(conn_t *conn);
#endif
int handle_nppiSet_32fc_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32fc_AC4R(conn_t *conn);
#endif
int handle_nppiSet_8u_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C1MR(conn_t *conn);
#endif
int handle_nppiSet_8u_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C3MR(conn_t *conn);
#endif
int handle_nppiSet_8u_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C4MR(conn_t *conn);
#endif
int handle_nppiSet_8u_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_AC4MR(conn_t *conn);
#endif
int handle_nppiSet_16u_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C1MR(conn_t *conn);
#endif
int handle_nppiSet_16u_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C3MR(conn_t *conn);
#endif
int handle_nppiSet_16u_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C4MR(conn_t *conn);
#endif
int handle_nppiSet_16u_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_AC4MR(conn_t *conn);
#endif
int handle_nppiSet_16s_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C1MR(conn_t *conn);
#endif
int handle_nppiSet_16s_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C3MR(conn_t *conn);
#endif
int handle_nppiSet_16s_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C4MR(conn_t *conn);
#endif
int handle_nppiSet_16s_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_AC4MR(conn_t *conn);
#endif
int handle_nppiSet_32s_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C1MR(conn_t *conn);
#endif
int handle_nppiSet_32s_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C3MR(conn_t *conn);
#endif
int handle_nppiSet_32s_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C4MR(conn_t *conn);
#endif
int handle_nppiSet_32s_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_AC4MR(conn_t *conn);
#endif
int handle_nppiSet_32f_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C1MR(conn_t *conn);
#endif
int handle_nppiSet_32f_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C3MR(conn_t *conn);
#endif
int handle_nppiSet_32f_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C4MR(conn_t *conn);
#endif
int handle_nppiSet_32f_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_AC4MR(conn_t *conn);
#endif
int handle_nppiSet_8u_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C3CR(conn_t *conn);
#endif
int handle_nppiSet_8u_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_8u_C4CR(conn_t *conn);
#endif
int handle_nppiSet_16u_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C3CR(conn_t *conn);
#endif
int handle_nppiSet_16u_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16u_C4CR(conn_t *conn);
#endif
int handle_nppiSet_16s_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C3CR(conn_t *conn);
#endif
int handle_nppiSet_16s_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_16s_C4CR(conn_t *conn);
#endif
int handle_nppiSet_32s_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C3CR(conn_t *conn);
#endif
int handle_nppiSet_32s_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32s_C4CR(conn_t *conn);
#endif
int handle_nppiSet_32f_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C3CR(conn_t *conn);
#endif
int handle_nppiSet_32f_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSet_32f_C4CR(conn_t *conn);
#endif
int handle_nppiCopy_8s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8s_C1R(conn_t *conn);
#endif
int handle_nppiCopy_8s_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8s_C2R(conn_t *conn);
#endif
int handle_nppiCopy_8s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8s_C3R(conn_t *conn);
#endif
int handle_nppiCopy_8s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8s_C4R(conn_t *conn);
#endif
int handle_nppiCopy_8s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8s_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C1R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C3R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C4R(conn_t *conn);
#endif
int handle_nppiCopy_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C1R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C3R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C4R(conn_t *conn);
#endif
int handle_nppiCopy_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C1R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C3R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C4R(conn_t *conn);
#endif
int handle_nppiCopy_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_16sc_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16sc_C1R(conn_t *conn);
#endif
int handle_nppiCopy_16sc_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16sc_C2R(conn_t *conn);
#endif
int handle_nppiCopy_16sc_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16sc_C3R(conn_t *conn);
#endif
int handle_nppiCopy_16sc_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16sc_C4R(conn_t *conn);
#endif
int handle_nppiCopy_16sc_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16sc_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C1R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C3R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C4R(conn_t *conn);
#endif
int handle_nppiCopy_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_32sc_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32sc_C1R(conn_t *conn);
#endif
int handle_nppiCopy_32sc_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32sc_C2R(conn_t *conn);
#endif
int handle_nppiCopy_32sc_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32sc_C3R(conn_t *conn);
#endif
int handle_nppiCopy_32sc_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32sc_C4R(conn_t *conn);
#endif
int handle_nppiCopy_32sc_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32sc_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16f_C1R(conn_t *conn);
#endif
int handle_nppiCopy_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16f_C3R(conn_t *conn);
#endif
int handle_nppiCopy_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16f_C4R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C1R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C3R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C4R(conn_t *conn);
#endif
int handle_nppiCopy_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_32fc_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32fc_C1R(conn_t *conn);
#endif
int handle_nppiCopy_32fc_C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32fc_C2R(conn_t *conn);
#endif
int handle_nppiCopy_32fc_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32fc_C3R(conn_t *conn);
#endif
int handle_nppiCopy_32fc_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32fc_C4R(conn_t *conn);
#endif
int handle_nppiCopy_32fc_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32fc_AC4R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C1MR(conn_t *conn);
#endif
int handle_nppiCopy_8u_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C3MR(conn_t *conn);
#endif
int handle_nppiCopy_8u_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C4MR(conn_t *conn);
#endif
int handle_nppiCopy_8u_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_AC4MR(conn_t *conn);
#endif
int handle_nppiCopy_16u_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C1MR(conn_t *conn);
#endif
int handle_nppiCopy_16u_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C3MR(conn_t *conn);
#endif
int handle_nppiCopy_16u_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C4MR(conn_t *conn);
#endif
int handle_nppiCopy_16u_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_AC4MR(conn_t *conn);
#endif
int handle_nppiCopy_16s_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C1MR(conn_t *conn);
#endif
int handle_nppiCopy_16s_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C3MR(conn_t *conn);
#endif
int handle_nppiCopy_16s_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C4MR(conn_t *conn);
#endif
int handle_nppiCopy_16s_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_AC4MR(conn_t *conn);
#endif
int handle_nppiCopy_32s_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C1MR(conn_t *conn);
#endif
int handle_nppiCopy_32s_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C3MR(conn_t *conn);
#endif
int handle_nppiCopy_32s_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C4MR(conn_t *conn);
#endif
int handle_nppiCopy_32s_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_AC4MR(conn_t *conn);
#endif
int handle_nppiCopy_32f_C1MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C1MR(conn_t *conn);
#endif
int handle_nppiCopy_32f_C3MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C3MR(conn_t *conn);
#endif
int handle_nppiCopy_32f_C4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C4MR(conn_t *conn);
#endif
int handle_nppiCopy_32f_AC4MR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_AC4MR(conn_t *conn);
#endif
int handle_nppiCopy_8u_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C3CR(conn_t *conn);
#endif
int handle_nppiCopy_8u_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C4CR(conn_t *conn);
#endif
int handle_nppiCopy_16s_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C3CR(conn_t *conn);
#endif
int handle_nppiCopy_16s_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C4CR(conn_t *conn);
#endif
int handle_nppiCopy_16u_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C3CR(conn_t *conn);
#endif
int handle_nppiCopy_16u_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C4CR(conn_t *conn);
#endif
int handle_nppiCopy_32s_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C3CR(conn_t *conn);
#endif
int handle_nppiCopy_32s_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C4CR(conn_t *conn);
#endif
int handle_nppiCopy_32f_C3CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C3CR(conn_t *conn);
#endif
int handle_nppiCopy_32f_C4CR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C4CR(conn_t *conn);
#endif
int handle_nppiCopy_8u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C3C1R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C4C1R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C3C1R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C4C1R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C3C1R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C4C1R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C3C1R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C4C1R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C2C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C2C1R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C3C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C3C1R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C4C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C4C1R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C1C3R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C1C4R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C1C3R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C1C4R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C1C3R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C1C4R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C1C3R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C1C4R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C1C2R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C1C2R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C1C3R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C1C4R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C3P3R(conn_t *conn);
#endif
int handle_nppiCopy_8u_C4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_C4P4R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C3P3R(conn_t *conn);
#endif
int handle_nppiCopy_16s_C4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_C4P4R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C3P3R(conn_t *conn);
#endif
int handle_nppiCopy_16u_C4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_C4P4R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C3P3R(conn_t *conn);
#endif
int handle_nppiCopy_32s_C4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_C4P4R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C3P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C3P3R(conn_t *conn);
#endif
int handle_nppiCopy_32f_C4P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_C4P4R(conn_t *conn);
#endif
int handle_nppiCopy_8u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_P3C3R(conn_t *conn);
#endif
int handle_nppiCopy_8u_P4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_8u_P4C4R(conn_t *conn);
#endif
int handle_nppiCopy_16u_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_P3C3R(conn_t *conn);
#endif
int handle_nppiCopy_16u_P4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16u_P4C4R(conn_t *conn);
#endif
int handle_nppiCopy_16s_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_P3C3R(conn_t *conn);
#endif
int handle_nppiCopy_16s_P4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_16s_P4C4R(conn_t *conn);
#endif
int handle_nppiCopy_32s_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_P3C3R(conn_t *conn);
#endif
int handle_nppiCopy_32s_P4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32s_P4C4R(conn_t *conn);
#endif
int handle_nppiCopy_32f_P3C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_P3C3R(conn_t *conn);
#endif
int handle_nppiCopy_32f_P4C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopy_32f_P4C4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16u_C3R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16u_C4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16s_C3R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16s_C4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32s_C1R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32s_C3R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32s_C4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32s_AC4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiCopyConstBorder_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyConstBorder_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16u_C3R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16u_C4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16s_C3R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16s_C4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32s_C1R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32s_C3R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32s_C4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32s_AC4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiCopyReplicateBorder_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyReplicateBorder_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16u_C3R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16u_C4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16s_C3R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16s_C4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32s_C1R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32s_C3R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32s_C4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32s_AC4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiCopyWrapBorder_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopyWrapBorder_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_8u_C1R(conn_t *conn);
#endif
int handle_nppiCopySubpix_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_8u_C3R(conn_t *conn);
#endif
int handle_nppiCopySubpix_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_8u_C4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16u_C1R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16u_C3R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16u_C4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16s_C1R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16s_C3R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16s_C4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32s_C1R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32s_C3R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32s_C4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32s_AC4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32f_C1R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32f_C3R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32f_C4R(conn_t *conn);
#endif
int handle_nppiCopySubpix_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCopySubpix_32f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8u16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8u16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16u_C3R(conn_t *conn);
#endif
int handle_nppiConvert_8u16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16u_C4R(conn_t *conn);
#endif
int handle_nppiConvert_8u16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16u_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8u16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8u16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_8u16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_8u16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u16s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8u32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8u32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_8u32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_8u32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8u32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8u32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32f_C3R(conn_t *conn);
#endif
int handle_nppiConvert_8u32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32f_C4R(conn_t *conn);
#endif
int handle_nppiConvert_8u32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u32f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8s32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8s32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_8s32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_8s32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8s32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8s32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32f_C3R(conn_t *conn);
#endif
int handle_nppiConvert_8s32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32f_C4R(conn_t *conn);
#endif
int handle_nppiConvert_8s32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_16u32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16u32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16u32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16u32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_16u32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16u32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32f_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16u32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32f_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16u32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_16s32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16s32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16s32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16s32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_16s32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16s32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32f_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16s32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32f_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16s32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_16f32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16f32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16f32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16f32f_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16f32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16f32f_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16f32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16f32f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8s8u_C1Rs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s8u_C1Rs(conn_t *conn);
#endif
int handle_nppiConvert_8s16u_C1Rs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s16u_C1Rs(conn_t *conn);
#endif
int handle_nppiConvert_8s16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s16s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_8s32u_C1Rs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8s32u_C1Rs(conn_t *conn);
#endif
int handle_nppiConvert_16s16u_C1Rs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s16u_C1Rs(conn_t *conn);
#endif
int handle_nppiConvert_16s32u_C1Rs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s32u_C1Rs(conn_t *conn);
#endif
int handle_nppiConvert_16u32u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u32u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32s32u_C1Rs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s32u_C1Rs(conn_t *conn);
#endif
int handle_nppiConvert_32s32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32u32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32u32f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16u8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u8u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16u8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u8u_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16u8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u8u_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16u8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u8u_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_16s8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s8u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_16s8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s8u_C3R(conn_t *conn);
#endif
int handle_nppiConvert_16s8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s8u_C4R(conn_t *conn);
#endif
int handle_nppiConvert_16s8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s8u_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32s8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32s8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8u_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32s8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8u_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32s8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8u_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32s8s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32s8s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32s8s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32s8s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s8s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_8u8s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_8u8s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_16u8s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u8s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_16s8s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16s8s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_16u16s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_16u16s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32u8u_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32u8u_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32u8s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32u8s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32u16u_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32u16u_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32u16s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32u16s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32u32s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32u32s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32s16u_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s16u_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32s16s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32s16s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32f8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32f8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8u_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32f8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8u_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32f8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8u_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32f8s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32f8s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32f8s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32f8s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32f16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16u_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32f16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16u_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32f16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16u_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32f16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16u_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32f16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16s_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32f16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16s_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32f16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16s_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32f16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16s_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32f16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16f_C1R(conn_t *conn);
#endif
int handle_nppiConvert_32f16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16f_C3R(conn_t *conn);
#endif
int handle_nppiConvert_32f16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16f_C4R(conn_t *conn);
#endif
int handle_nppiConvert_32f16f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16f_AC4R(conn_t *conn);
#endif
int handle_nppiConvert_32f8u_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8u_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32f8s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f8s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32f16u_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16u_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32f16s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f16s_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32f32u_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f32u_C1RSfs(conn_t *conn);
#endif
int handle_nppiConvert_32f32s_C1RSfs_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiConvert_32f32s_C1RSfs(conn_t *conn);
#endif
int handle_nppiScale_8u16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16u_C1R(conn_t *conn);
#endif
int handle_nppiScale_8u16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16u_C3R(conn_t *conn);
#endif
int handle_nppiScale_8u16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16u_C4R(conn_t *conn);
#endif
int handle_nppiScale_8u16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16u_AC4R(conn_t *conn);
#endif
int handle_nppiScale_8u16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16s_C1R(conn_t *conn);
#endif
int handle_nppiScale_8u16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16s_C3R(conn_t *conn);
#endif
int handle_nppiScale_8u16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16s_C4R(conn_t *conn);
#endif
int handle_nppiScale_8u16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u16s_AC4R(conn_t *conn);
#endif
int handle_nppiScale_8u32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32s_C1R(conn_t *conn);
#endif
int handle_nppiScale_8u32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32s_C3R(conn_t *conn);
#endif
int handle_nppiScale_8u32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32s_C4R(conn_t *conn);
#endif
int handle_nppiScale_8u32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32s_AC4R(conn_t *conn);
#endif
int handle_nppiScale_8u32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32f_C1R(conn_t *conn);
#endif
int handle_nppiScale_8u32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32f_C3R(conn_t *conn);
#endif
int handle_nppiScale_8u32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32f_C4R(conn_t *conn);
#endif
int handle_nppiScale_8u32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_8u32f_AC4R(conn_t *conn);
#endif
int handle_nppiScale_16u8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16u8u_C1R(conn_t *conn);
#endif
int handle_nppiScale_16u8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16u8u_C3R(conn_t *conn);
#endif
int handle_nppiScale_16u8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16u8u_C4R(conn_t *conn);
#endif
int handle_nppiScale_16u8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16u8u_AC4R(conn_t *conn);
#endif
int handle_nppiScale_16s8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16s8u_C1R(conn_t *conn);
#endif
int handle_nppiScale_16s8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16s8u_C3R(conn_t *conn);
#endif
int handle_nppiScale_16s8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16s8u_C4R(conn_t *conn);
#endif
int handle_nppiScale_16s8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_16s8u_AC4R(conn_t *conn);
#endif
int handle_nppiScale_32s8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32s8u_C1R(conn_t *conn);
#endif
int handle_nppiScale_32s8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32s8u_C3R(conn_t *conn);
#endif
int handle_nppiScale_32s8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32s8u_C4R(conn_t *conn);
#endif
int handle_nppiScale_32s8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32s8u_AC4R(conn_t *conn);
#endif
int handle_nppiScale_32f8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32f8u_C1R(conn_t *conn);
#endif
int handle_nppiScale_32f8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32f8u_C3R(conn_t *conn);
#endif
int handle_nppiScale_32f8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32f8u_C4R(conn_t *conn);
#endif
int handle_nppiScale_32f8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiScale_32f8u_AC4R(conn_t *conn);
#endif
int handle_nppiDup_8u_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_8u_C1C3R(conn_t *conn);
#endif
int handle_nppiDup_8u_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_8u_C1C4R(conn_t *conn);
#endif
int handle_nppiDup_8u_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_8u_C1AC4R(conn_t *conn);
#endif
int handle_nppiDup_16u_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_16u_C1C3R(conn_t *conn);
#endif
int handle_nppiDup_16u_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_16u_C1C4R(conn_t *conn);
#endif
int handle_nppiDup_16u_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_16u_C1AC4R(conn_t *conn);
#endif
int handle_nppiDup_16s_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_16s_C1C3R(conn_t *conn);
#endif
int handle_nppiDup_16s_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_16s_C1C4R(conn_t *conn);
#endif
int handle_nppiDup_16s_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_16s_C1AC4R(conn_t *conn);
#endif
int handle_nppiDup_32s_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_32s_C1C3R(conn_t *conn);
#endif
int handle_nppiDup_32s_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_32s_C1C4R(conn_t *conn);
#endif
int handle_nppiDup_32s_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_32s_C1AC4R(conn_t *conn);
#endif
int handle_nppiDup_32f_C1C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_32f_C1C3R(conn_t *conn);
#endif
int handle_nppiDup_32f_C1C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_32f_C1C4R(conn_t *conn);
#endif
int handle_nppiDup_32f_C1AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDup_32f_C1AC4R(conn_t *conn);
#endif
int handle_nppiTranspose_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_8u_C1R(conn_t *conn);
#endif
int handle_nppiTranspose_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_8u_C3R(conn_t *conn);
#endif
int handle_nppiTranspose_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_8u_C4R(conn_t *conn);
#endif
int handle_nppiTranspose_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_16u_C1R(conn_t *conn);
#endif
int handle_nppiTranspose_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_16u_C3R(conn_t *conn);
#endif
int handle_nppiTranspose_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_16u_C4R(conn_t *conn);
#endif
int handle_nppiTranspose_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_16s_C1R(conn_t *conn);
#endif
int handle_nppiTranspose_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_16s_C3R(conn_t *conn);
#endif
int handle_nppiTranspose_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_16s_C4R(conn_t *conn);
#endif
int handle_nppiTranspose_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_32s_C1R(conn_t *conn);
#endif
int handle_nppiTranspose_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_32s_C3R(conn_t *conn);
#endif
int handle_nppiTranspose_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_32s_C4R(conn_t *conn);
#endif
int handle_nppiTranspose_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_32f_C1R(conn_t *conn);
#endif
int handle_nppiTranspose_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_32f_C3R(conn_t *conn);
#endif
int handle_nppiTranspose_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiTranspose_32f_C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_C3IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_C4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_C4C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_C4IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_C3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_C3C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_8u_AC4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_C3IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_C4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_C4C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_C4IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_C3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_C3C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16u_AC4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_C3IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_C4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_C4C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_C4IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_C3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_C3C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_16s_AC4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_C3IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_C4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_C4C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_C4IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_C3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_C3C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32s_AC4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_C3IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_C4C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_C4C3R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_C4IR(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_C3C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_C3C4R(conn_t *conn);
#endif
int handle_nppiSwapChannels_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiSwapChannels_32f_AC4R(conn_t *conn);
#endif
