// Generated by codegen.py. Do not edit by hand.

int handle_nvJitLinkDestroy(conn_t *conn);
int handle_nvJitLinkComplete(conn_t *conn);
int handle_nvJitLinkGetLinkedCubinSize(conn_t *conn);
int handle_nvJitLinkGetLinkedPtxSize(conn_t *conn);
#if LUPINE_NVJITLINK_HAS_LTOIR
int handle_nvJitLinkGetLinkedLTOIRSize(conn_t *conn);
#endif
int handle_nvJitLinkGetErrorLogSize(conn_t *conn);
int handle_nvJitLinkGetInfoLogSize(conn_t *conn);
int handle_nvJitLinkVersion(conn_t *conn);
