// Generated by codegen.py. Do not edit by hand.

int handle_hipInit(conn_t *conn);
int handle_hipGetDeviceCount(conn_t *conn);
int handle_hipDeviceGet(conn_t *conn);
int handle_hipGetDevicePropertiesR0600(conn_t *conn);
int handle_hipDeviceGetName(conn_t *conn);
int handle_hipDeviceTotalMem(conn_t *conn);
int handle_hipDeviceGetAttribute(conn_t *conn);
int handle_hipDriverGetVersion(conn_t *conn);
int handle_hipRuntimeGetVersion(conn_t *conn);
