// Generated by codegen.py. Do not edit by hand.

int handle_cusparseCreate(conn_t *conn);
int handle_cusparseDestroy(conn_t *conn);
int handle_cusparseGetVersion(conn_t *conn);
int handle_cusparseGetProperty(conn_t *conn);
int handle_cusparseSetStream(conn_t *conn);
int handle_cusparseGetStream(conn_t *conn);
int handle_cusparseGetPointerMode(conn_t *conn);
int handle_cusparseSetPointerMode(conn_t *conn);
int handle_cusparseLoggerOpenFile(conn_t *conn);
int handle_cusparseLoggerSetLevel(conn_t *conn);
int handle_cusparseLoggerSetMask(conn_t *conn);
int handle_cusparseLoggerForceDisable(conn_t *conn);
int handle_cusparseCreateMatDescr(conn_t *conn);
int handle_cusparseDestroyMatDescr(conn_t *conn);
int handle_cusparseSetMatType(conn_t *conn);
int handle_cusparseGetMatType(conn_t *conn);
int handle_cusparseSetMatFillMode(conn_t *conn);
int handle_cusparseGetMatFillMode(conn_t *conn);
int handle_cusparseSetMatDiagType(conn_t *conn);
int handle_cusparseGetMatDiagType(conn_t *conn);
int handle_cusparseSetMatIndexBase(conn_t *conn);
int handle_cusparseGetMatIndexBase(conn_t *conn);
int handle_cusparseCreateCsric02Info(conn_t *conn);
int handle_cusparseDestroyCsric02Info(conn_t *conn);
int handle_cusparseCreateBsric02Info(conn_t *conn);
int handle_cusparseDestroyBsric02Info(conn_t *conn);
int handle_cusparseCreateCsrilu02Info(conn_t *conn);
int handle_cusparseDestroyCsrilu02Info(conn_t *conn);
int handle_cusparseCreateBsrilu02Info(conn_t *conn);
int handle_cusparseDestroyBsrilu02Info(conn_t *conn);
int handle_cusparseCreateBsrsv2Info(conn_t *conn);
int handle_cusparseDestroyBsrsv2Info(conn_t *conn);
int handle_cusparseCreateBsrsm2Info(conn_t *conn);
int handle_cusparseDestroyBsrsm2Info(conn_t *conn);
int handle_cusparseCreateCsru2csrInfo(conn_t *conn);
int handle_cusparseDestroyCsru2csrInfo(conn_t *conn);
int handle_cusparseCreateColorInfo(conn_t *conn);
int handle_cusparseDestroyColorInfo(conn_t *conn);
int handle_cusparseCreatePruneInfo(conn_t *conn);
int handle_cusparseDestroyPruneInfo(conn_t *conn);
int handle_cusparseSgemvi(conn_t *conn);
int handle_cusparseSgemvi_bufferSize(conn_t *conn);
int handle_cusparseDgemvi(conn_t *conn);
int handle_cusparseDgemvi_bufferSize(conn_t *conn);
int handle_cusparseCgemvi(conn_t *conn);
int handle_cusparseCgemvi_bufferSize(conn_t *conn);
int handle_cusparseZgemvi(conn_t *conn);
int handle_cusparseZgemvi_bufferSize(conn_t *conn);
int handle_cusparseSbsrmv(conn_t *conn);
int handle_cusparseDbsrmv(conn_t *conn);
int handle_cusparseCbsrmv(conn_t *conn);
int handle_cusparseZbsrmv(conn_t *conn);
int handle_cusparseSbsrxmv(conn_t *conn);
int handle_cusparseDbsrxmv(conn_t *conn);
int handle_cusparseCbsrxmv(conn_t *conn);
int handle_cusparseZbsrxmv(conn_t *conn);
int handle_cusparseXbsrsv2_zeroPivot(conn_t *conn);
int handle_cusparseSbsrsv2_bufferSize(conn_t *conn);
int handle_cusparseDbsrsv2_bufferSize(conn_t *conn);
int handle_cusparseCbsrsv2_bufferSize(conn_t *conn);
int handle_cusparseZbsrsv2_bufferSize(conn_t *conn);
int handle_cusparseSbsrsv2_analysis(conn_t *conn);
int handle_cusparseDbsrsv2_analysis(conn_t *conn);
int handle_cusparseCbsrsv2_analysis(conn_t *conn);
int handle_cusparseZbsrsv2_analysis(conn_t *conn);
int handle_cusparseSbsrsv2_solve(conn_t *conn);
int handle_cusparseDbsrsv2_solve(conn_t *conn);
int handle_cusparseCbsrsv2_solve(conn_t *conn);
int handle_cusparseZbsrsv2_solve(conn_t *conn);
int handle_cusparseSbsrmm(conn_t *conn);
int handle_cusparseDbsrmm(conn_t *conn);
int handle_cusparseCbsrmm(conn_t *conn);
int handle_cusparseZbsrmm(conn_t *conn);
int handle_cusparseXbsrsm2_zeroPivot(conn_t *conn);
int handle_cusparseSbsrsm2_bufferSize(conn_t *conn);
int handle_cusparseDbsrsm2_bufferSize(conn_t *conn);
int handle_cusparseCbsrsm2_bufferSize(conn_t *conn);
int handle_cusparseZbsrsm2_bufferSize(conn_t *conn);
int handle_cusparseSbsrsm2_analysis(conn_t *conn);
int handle_cusparseDbsrsm2_analysis(conn_t *conn);
int handle_cusparseCbsrsm2_analysis(conn_t *conn);
int handle_cusparseZbsrsm2_analysis(conn_t *conn);
int handle_cusparseSbsrsm2_solve(conn_t *conn);
int handle_cusparseDbsrsm2_solve(conn_t *conn);
int handle_cusparseCbsrsm2_solve(conn_t *conn);
int handle_cusparseZbsrsm2_solve(conn_t *conn);
int handle_cusparseScsrilu02_numericBoost(conn_t *conn);
int handle_cusparseDcsrilu02_numericBoost(conn_t *conn);
int handle_cusparseCcsrilu02_numericBoost(conn_t *conn);
int handle_cusparseZcsrilu02_numericBoost(conn_t *conn);
int handle_cusparseXcsrilu02_zeroPivot(conn_t *conn);
int handle_cusparseScsrilu02_bufferSize(conn_t *conn);
int handle_cusparseDcsrilu02_bufferSize(conn_t *conn);
int handle_cusparseCcsrilu02_bufferSize(conn_t *conn);
int handle_cusparseZcsrilu02_bufferSize(conn_t *conn);
int handle_cusparseScsrilu02_analysis(conn_t *conn);
int handle_cusparseDcsrilu02_analysis(conn_t *conn);
int handle_cusparseCcsrilu02_analysis(conn_t *conn);
int handle_cusparseZcsrilu02_analysis(conn_t *conn);
int handle_cusparseScsrilu02(conn_t *conn);
int handle_cusparseDcsrilu02(conn_t *conn);
int handle_cusparseCcsrilu02(conn_t *conn);
int handle_cusparseZcsrilu02(conn_t *conn);
int handle_cusparseSbsrilu02_numericBoost(conn_t *conn);
int handle_cusparseDbsrilu02_numericBoost(conn_t *conn);
int handle_cusparseCbsrilu02_numericBoost(conn_t *conn);
int handle_cusparseZbsrilu02_numericBoost(conn_t *conn);
int handle_cusparseXbsrilu02_zeroPivot(conn_t *conn);
int handle_cusparseSbsrilu02_bufferSize(conn_t *conn);
int handle_cusparseDbsrilu02_bufferSize(conn_t *conn);
int handle_cusparseCbsrilu02_bufferSize(conn_t *conn);
int handle_cusparseZbsrilu02_bufferSize(conn_t *conn);
int handle_cusparseSbsrilu02_analysis(conn_t *conn);
int handle_cusparseDbsrilu02_analysis(conn_t *conn);
int handle_cusparseCbsrilu02_analysis(conn_t *conn);
int handle_cusparseZbsrilu02_analysis(conn_t *conn);
int handle_cusparseSbsrilu02(conn_t *conn);
int handle_cusparseDbsrilu02(conn_t *conn);
int handle_cusparseCbsrilu02(conn_t *conn);
int handle_cusparseZbsrilu02(conn_t *conn);
int handle_cusparseXcsric02_zeroPivot(conn_t *conn);
int handle_cusparseScsric02_bufferSize(conn_t *conn);
int handle_cusparseDcsric02_bufferSize(conn_t *conn);
int handle_cusparseCcsric02_bufferSize(conn_t *conn);
int handle_cusparseZcsric02_bufferSize(conn_t *conn);
int handle_cusparseScsric02_analysis(conn_t *conn);
int handle_cusparseDcsric02_analysis(conn_t *conn);
int handle_cusparseCcsric02_analysis(conn_t *conn);
int handle_cusparseZcsric02_analysis(conn_t *conn);
int handle_cusparseScsric02(conn_t *conn);
int handle_cusparseDcsric02(conn_t *conn);
int handle_cusparseCcsric02(conn_t *conn);
int handle_cusparseZcsric02(conn_t *conn);
int handle_cusparseXbsric02_zeroPivot(conn_t *conn);
int handle_cusparseSbsric02_bufferSize(conn_t *conn);
int handle_cusparseDbsric02_bufferSize(conn_t *conn);
int handle_cusparseCbsric02_bufferSize(conn_t *conn);
int handle_cusparseZbsric02_bufferSize(conn_t *conn);
int handle_cusparseSbsric02_analysis(conn_t *conn);
int handle_cusparseDbsric02_analysis(conn_t *conn);
int handle_cusparseCbsric02_analysis(conn_t *conn);
int handle_cusparseZbsric02_analysis(conn_t *conn);
int handle_cusparseSbsric02(conn_t *conn);
int handle_cusparseDbsric02(conn_t *conn);
int handle_cusparseCbsric02(conn_t *conn);
int handle_cusparseZbsric02(conn_t *conn);
int handle_cusparseSgtsv2_bufferSizeExt(conn_t *conn);
int handle_cusparseDgtsv2_bufferSizeExt(conn_t *conn);
int handle_cusparseCgtsv2_bufferSizeExt(conn_t *conn);
int handle_cusparseZgtsv2_bufferSizeExt(conn_t *conn);
int handle_cusparseSgtsv2(conn_t *conn);
int handle_cusparseDgtsv2(conn_t *conn);
int handle_cusparseCgtsv2(conn_t *conn);
int handle_cusparseZgtsv2(conn_t *conn);
int handle_cusparseSgtsv2_nopivot_bufferSizeExt(conn_t *conn);
int handle_cusparseDgtsv2_nopivot_bufferSizeExt(conn_t *conn);
int handle_cusparseCgtsv2_nopivot_bufferSizeExt(conn_t *conn);
int handle_cusparseZgtsv2_nopivot_bufferSizeExt(conn_t *conn);
int handle_cusparseSgtsv2_nopivot(conn_t *conn);
int handle_cusparseDgtsv2_nopivot(conn_t *conn);
int handle_cusparseCgtsv2_nopivot(conn_t *conn);
int handle_cusparseZgtsv2_nopivot(conn_t *conn);
int handle_cusparseSgtsv2StridedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseDgtsv2StridedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseCgtsv2StridedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseZgtsv2StridedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseSgtsv2StridedBatch(conn_t *conn);
int handle_cusparseDgtsv2StridedBatch(conn_t *conn);
int handle_cusparseCgtsv2StridedBatch(conn_t *conn);
int handle_cusparseZgtsv2StridedBatch(conn_t *conn);
int handle_cusparseSgtsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseDgtsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseCgtsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseZgtsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseSgtsvInterleavedBatch(conn_t *conn);
int handle_cusparseDgtsvInterleavedBatch(conn_t *conn);
int handle_cusparseCgtsvInterleavedBatch(conn_t *conn);
int handle_cusparseZgtsvInterleavedBatch(conn_t *conn);
int handle_cusparseSgpsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseDgpsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseCgpsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseZgpsvInterleavedBatch_bufferSizeExt(conn_t *conn);
int handle_cusparseSgpsvInterleavedBatch(conn_t *conn);
int handle_cusparseDgpsvInterleavedBatch(conn_t *conn);
int handle_cusparseCgpsvInterleavedBatch(conn_t *conn);
int handle_cusparseZgpsvInterleavedBatch(conn_t *conn);
int handle_cusparseScsrgeam2_bufferSizeExt(conn_t *conn);
int handle_cusparseDcsrgeam2_bufferSizeExt(conn_t *conn);
int handle_cusparseCcsrgeam2_bufferSizeExt(conn_t *conn);
int handle_cusparseZcsrgeam2_bufferSizeExt(conn_t *conn);
int handle_cusparseXcsrgeam2Nnz(conn_t *conn);
int handle_cusparseScsrgeam2(conn_t *conn);
int handle_cusparseDcsrgeam2(conn_t *conn);
int handle_cusparseCcsrgeam2(conn_t *conn);
int handle_cusparseZcsrgeam2(conn_t *conn);
int handle_cusparseScsrcolor(conn_t *conn);
int handle_cusparseDcsrcolor(conn_t *conn);
int handle_cusparseCcsrcolor(conn_t *conn);
int handle_cusparseZcsrcolor(conn_t *conn);
int handle_cusparseSnnz(conn_t *conn);
int handle_cusparseDnnz(conn_t *conn);
int handle_cusparseCnnz(conn_t *conn);
int handle_cusparseZnnz(conn_t *conn);
int handle_cusparseSnnz_compress(conn_t *conn);
int handle_cusparseDnnz_compress(conn_t *conn);
int handle_cusparseCnnz_compress(conn_t *conn);
int handle_cusparseZnnz_compress(conn_t *conn);
int handle_cusparseScsr2csr_compress(conn_t *conn);
int handle_cusparseDcsr2csr_compress(conn_t *conn);
int handle_cusparseCcsr2csr_compress(conn_t *conn);
int handle_cusparseZcsr2csr_compress(conn_t *conn);
int handle_cusparseXcoo2csr(conn_t *conn);
int handle_cusparseXcsr2coo(conn_t *conn);
int handle_cusparseXcsr2bsrNnz(conn_t *conn);
int handle_cusparseScsr2bsr(conn_t *conn);
int handle_cusparseDcsr2bsr(conn_t *conn);
int handle_cusparseCcsr2bsr(conn_t *conn);
int handle_cusparseZcsr2bsr(conn_t *conn);
int handle_cusparseSbsr2csr(conn_t *conn);
int handle_cusparseDbsr2csr(conn_t *conn);
int handle_cusparseCbsr2csr(conn_t *conn);
int handle_cusparseZbsr2csr(conn_t *conn);
int handle_cusparseSgebsr2gebsc_bufferSize(conn_t *conn);
int handle_cusparseDgebsr2gebsc_bufferSize(conn_t *conn);
int handle_cusparseCgebsr2gebsc_bufferSize(conn_t *conn);
int handle_cusparseZgebsr2gebsc_bufferSize(conn_t *conn);
int handle_cusparseSgebsr2gebsc(conn_t *conn);
int handle_cusparseDgebsr2gebsc(conn_t *conn);
int handle_cusparseCgebsr2gebsc(conn_t *conn);
int handle_cusparseZgebsr2gebsc(conn_t *conn);
int handle_cusparseSgebsr2csr(conn_t *conn);
int handle_cusparseDgebsr2csr(conn_t *conn);
int handle_cusparseCgebsr2csr(conn_t *conn);
int handle_cusparseZgebsr2csr(conn_t *conn);
int handle_cusparseScsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseDcsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseCcsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseZcsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseXcsr2gebsrNnz(conn_t *conn);
int handle_cusparseScsr2gebsr(conn_t *conn);
int handle_cusparseDcsr2gebsr(conn_t *conn);
int handle_cusparseCcsr2gebsr(conn_t *conn);
int handle_cusparseZcsr2gebsr(conn_t *conn);
int handle_cusparseSgebsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseDgebsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseCgebsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseZgebsr2gebsr_bufferSize(conn_t *conn);
int handle_cusparseXgebsr2gebsrNnz(conn_t *conn);
int handle_cusparseSgebsr2gebsr(conn_t *conn);
int handle_cusparseDgebsr2gebsr(conn_t *conn);
int handle_cusparseCgebsr2gebsr(conn_t *conn);
int handle_cusparseZgebsr2gebsr(conn_t *conn);
int handle_cusparseCreateIdentityPermutation(conn_t *conn);
int handle_cusparseXcoosort_bufferSizeExt(conn_t *conn);
int handle_cusparseXcoosortByRow(conn_t *conn);
int handle_cusparseXcoosortByColumn(conn_t *conn);
int handle_cusparseXcsrsort_bufferSizeExt(conn_t *conn);
int handle_cusparseXcsrsort(conn_t *conn);
int handle_cusparseXcscsort_bufferSizeExt(conn_t *conn);
int handle_cusparseXcscsort(conn_t *conn);
int handle_cusparseScsru2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseDcsru2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseCcsru2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseZcsru2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseScsru2csr(conn_t *conn);
int handle_cusparseDcsru2csr(conn_t *conn);
int handle_cusparseCcsru2csr(conn_t *conn);
int handle_cusparseZcsru2csr(conn_t *conn);
int handle_cusparseScsr2csru(conn_t *conn);
int handle_cusparseDcsr2csru(conn_t *conn);
int handle_cusparseCcsr2csru(conn_t *conn);
int handle_cusparseZcsr2csru(conn_t *conn);
int handle_cusparseHpruneDense2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseSpruneDense2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseDpruneDense2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseHpruneDense2csrNnz(conn_t *conn);
int handle_cusparseSpruneDense2csrNnz(conn_t *conn);
int handle_cusparseDpruneDense2csrNnz(conn_t *conn);
int handle_cusparseHpruneDense2csr(conn_t *conn);
int handle_cusparseSpruneDense2csr(conn_t *conn);
int handle_cusparseDpruneDense2csr(conn_t *conn);
int handle_cusparseHpruneCsr2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseSpruneCsr2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseDpruneCsr2csr_bufferSizeExt(conn_t *conn);
int handle_cusparseHpruneCsr2csrNnz(conn_t *conn);
int handle_cusparseSpruneCsr2csrNnz(conn_t *conn);
int handle_cusparseDpruneCsr2csrNnz(conn_t *conn);
int handle_cusparseHpruneCsr2csr(conn_t *conn);
int handle_cusparseSpruneCsr2csr(conn_t *conn);
int handle_cusparseDpruneCsr2csr(conn_t *conn);
int handle_cusparseHpruneDense2csrByPercentage_bufferSizeExt(conn_t *conn);
int handle_cusparseSpruneDense2csrByPercentage_bufferSizeExt(conn_t *conn);
int handle_cusparseDpruneDense2csrByPercentage_bufferSizeExt(conn_t *conn);
int handle_cusparseHpruneDense2csrNnzByPercentage(conn_t *conn);
int handle_cusparseSpruneDense2csrNnzByPercentage(conn_t *conn);
int handle_cusparseDpruneDense2csrNnzByPercentage(conn_t *conn);
int handle_cusparseHpruneDense2csrByPercentage(conn_t *conn);
int handle_cusparseSpruneDense2csrByPercentage(conn_t *conn);
int handle_cusparseDpruneDense2csrByPercentage(conn_t *conn);
int handle_cusparseHpruneCsr2csrByPercentage_bufferSizeExt(conn_t *conn);
int handle_cusparseSpruneCsr2csrByPercentage_bufferSizeExt(conn_t *conn);
int handle_cusparseDpruneCsr2csrByPercentage_bufferSizeExt(conn_t *conn);
int handle_cusparseHpruneCsr2csrNnzByPercentage(conn_t *conn);
int handle_cusparseSpruneCsr2csrNnzByPercentage(conn_t *conn);
int handle_cusparseDpruneCsr2csrNnzByPercentage(conn_t *conn);
int handle_cusparseHpruneCsr2csrByPercentage(conn_t *conn);
int handle_cusparseSpruneCsr2csrByPercentage(conn_t *conn);
int handle_cusparseDpruneCsr2csrByPercentage(conn_t *conn);
int handle_cusparseCsr2cscEx2(conn_t *conn);
int handle_cusparseCsr2cscEx2_bufferSize(conn_t *conn);
int handle_cusparseCreateSpVec(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstSpVec(conn_t *conn);
#endif
int handle_cusparseDestroySpVec(conn_t *conn);
int handle_cusparseSpVecGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstSpVecGet(conn_t *conn);
#endif
int handle_cusparseSpVecGetIndexBase(conn_t *conn);
int handle_cusparseSpVecGetValues(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstSpVecGetValues(conn_t *conn);
#endif
int handle_cusparseSpVecSetValues(conn_t *conn);
int handle_cusparseCreateDnVec(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstDnVec(conn_t *conn);
#endif
int handle_cusparseDestroyDnVec(conn_t *conn);
int handle_cusparseDnVecGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstDnVecGet(conn_t *conn);
#endif
int handle_cusparseDnVecGetValues(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstDnVecGetValues(conn_t *conn);
#endif
int handle_cusparseDnVecSetValues(conn_t *conn);
int handle_cusparseDestroySpMat(conn_t *conn);
int handle_cusparseSpMatGetFormat(conn_t *conn);
int handle_cusparseSpMatGetIndexBase(conn_t *conn);
int handle_cusparseSpMatGetValues(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstSpMatGetValues(conn_t *conn);
#endif
int handle_cusparseSpMatSetValues(conn_t *conn);
int handle_cusparseSpMatGetSize(conn_t *conn);
int handle_cusparseSpMatGetStridedBatch(conn_t *conn);
int handle_cusparseCooSetStridedBatch(conn_t *conn);
int handle_cusparseCsrSetStridedBatch(conn_t *conn);
#if CUSPARSE_VERSION >= 12100
int handle_cusparseBsrSetStridedBatch(conn_t *conn);
#endif
int handle_cusparseSpMatGetAttribute(conn_t *conn);
int handle_cusparseSpMatSetAttribute(conn_t *conn);
int handle_cusparseCreateCsr(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstCsr(conn_t *conn);
#endif
int handle_cusparseCreateCsc(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstCsc(conn_t *conn);
#endif
int handle_cusparseCsrGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstCsrGet(conn_t *conn);
#endif
int handle_cusparseCscGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstCscGet(conn_t *conn);
#endif
int handle_cusparseCsrSetPointers(conn_t *conn);
int handle_cusparseCscSetPointers(conn_t *conn);
#if CUSPARSE_VERSION >= 12100
int handle_cusparseCreateBsr(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12100
int handle_cusparseCreateConstBsr(conn_t *conn);
#endif
int handle_cusparseCreateCoo(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstCoo(conn_t *conn);
#endif
int handle_cusparseCooGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstCooGet(conn_t *conn);
#endif
int handle_cusparseCooSetPointers(conn_t *conn);
int handle_cusparseCreateBlockedEll(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstBlockedEll(conn_t *conn);
#endif
int handle_cusparseBlockedEllGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstBlockedEllGet(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12100
int handle_cusparseCreateSlicedEll(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12102
int handle_cusparseCreateConstSlicedEll(conn_t *conn);
#endif
int handle_cusparseCreateDnMat(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseCreateConstDnMat(conn_t *conn);
#endif
int handle_cusparseDestroyDnMat(conn_t *conn);
int handle_cusparseDnMatGet(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstDnMatGet(conn_t *conn);
#endif
int handle_cusparseDnMatGetValues(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseConstDnMatGetValues(conn_t *conn);
#endif
int handle_cusparseDnMatSetValues(conn_t *conn);
int handle_cusparseDnMatSetStridedBatch(conn_t *conn);
int handle_cusparseDnMatGetStridedBatch(conn_t *conn);
int handle_cusparseAxpby(conn_t *conn);
int handle_cusparseGather(conn_t *conn);
int handle_cusparseScatter(conn_t *conn);
int handle_cusparseRot(conn_t *conn);
int handle_cusparseSpVV_bufferSize(conn_t *conn);
int handle_cusparseSpVV(conn_t *conn);
int handle_cusparseSparseToDense_bufferSize(conn_t *conn);
int handle_cusparseSparseToDense(conn_t *conn);
int handle_cusparseDenseToSparse_bufferSize(conn_t *conn);
int handle_cusparseDenseToSparse_analysis(conn_t *conn);
int handle_cusparseDenseToSparse_convert(conn_t *conn);
int handle_cusparseSpMV(conn_t *conn);
int handle_cusparseSpMV_bufferSize(conn_t *conn);
#if CUSPARSE_VERSION >= 12300
int handle_cusparseSpMV_preprocess(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpMVOp_bufferSize(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpMVOp_createDescr(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12702
int handle_cusparseSpMVOp_destroyDescr(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12702
int handle_cusparseSpMVOp_createPlan(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12702
int handle_cusparseSpMVOp_destroyPlan(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12702
int handle_cusparseSpMVOp_setGlobalUserData(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12702
int handle_cusparseSpMVOp(conn_t *conn);
#endif
int handle_cusparseSpSV_createDescr(conn_t *conn);
int handle_cusparseSpSV_destroyDescr(conn_t *conn);
int handle_cusparseSpSV_bufferSize(conn_t *conn);
int handle_cusparseSpSV_analysis(conn_t *conn);
int handle_cusparseSpSV_solve(conn_t *conn);
#if CUSPARSE_VERSION >= 12100
int handle_cusparseSpSV_updateMatrix(conn_t *conn);
#endif
int handle_cusparseSpSM_createDescr(conn_t *conn);
int handle_cusparseSpSM_destroyDescr(conn_t *conn);
int handle_cusparseSpSM_bufferSize(conn_t *conn);
int handle_cusparseSpSM_analysis(conn_t *conn);
int handle_cusparseSpSM_solve(conn_t *conn);
#if CUSPARSE_VERSION >= 12300
int handle_cusparseSpSM_updateMatrix(conn_t *conn);
#endif
int handle_cusparseSpMM_bufferSize(conn_t *conn);
int handle_cusparseSpMM_preprocess(conn_t *conn);
int handle_cusparseSpMM(conn_t *conn);
int handle_cusparseSpGEMM_createDescr(conn_t *conn);
int handle_cusparseSpGEMM_destroyDescr(conn_t *conn);
int handle_cusparseSpGEMM_workEstimation(conn_t *conn);
#if CUSPARSE_VERSION >= 12000
int handle_cusparseSpGEMM_getNumProducts(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12000
int handle_cusparseSpGEMM_estimateMemory(conn_t *conn);
#endif
int handle_cusparseSpGEMM_compute(conn_t *conn);
int handle_cusparseSpGEMM_copy(conn_t *conn);
int handle_cusparseSpGEMMreuse_workEstimation(conn_t *conn);
int handle_cusparseSpGEMMreuse_nnz(conn_t *conn);
int handle_cusparseSpGEMMreuse_copy(conn_t *conn);
int handle_cusparseSpGEMMreuse_compute(conn_t *conn);
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpGEAM_createDescr(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpGEAM_destroyDescr(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpGEAM_bufferSize(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpGEAM_nnz(conn_t *conn);
#endif
#if CUSPARSE_VERSION >= 12801
int handle_cusparseSpGEAM(conn_t *conn);
#endif
int handle_cusparseSDDMM_bufferSize(conn_t *conn);
int handle_cusparseSDDMM_preprocess(conn_t *conn);
int handle_cusparseSDDMM(conn_t *conn);
int handle_cusparseSpMMOp_createPlan(conn_t *conn);
int handle_cusparseSpMMOp(conn_t *conn);
int handle_cusparseSpMMOp_destroyPlan(conn_t *conn);
