// Generated by codegen.py. Do not edit.
#pragma once
#include "cuda_stream_semantics.h"
#include "gen_rpc_ids.h"
#include <cstring>
#include <cuda.h>
extern "C" CUresult CUDAAPI cuEventRecord_ptsz(CUevent hEvent,
                                               CUstream hStream);
extern "C" CUresult CUDAAPI cuEventRecordWithFlags_ptsz(CUevent hEvent,
                                                        CUstream hStream,
                                                        unsigned int flags);
extern "C" CUresult CUDAAPI cuGraphInstantiateWithParams_ptsz(
    CUgraphExec *phGraphExec, CUgraph hGraph,
    CUDA_GRAPH_INSTANTIATE_PARAMS *instantiateParams);
extern "C" CUresult CUDAAPI cuGraphLaunch_ptsz(CUgraphExec hGraphExec,
                                               CUstream hStream);
extern "C" CUresult CUDAAPI cuGraphUpload_ptsz(CUgraphExec hGraphExec,
                                               CUstream hStream);
extern "C" CUresult CUDAAPI cuGraphicsMapResources_ptsz(
    unsigned int count, CUgraphicsResource *resources, CUstream hStream);
extern "C" CUresult CUDAAPI cuGraphicsUnmapResources_ptsz(
    unsigned int count, CUgraphicsResource *resources, CUstream hStream);
extern "C" CUresult CUDAAPI cuLaunchCooperativeKernel_ptsz(
    CUfunction f, unsigned int gridDimX, unsigned int gridDimY,
    unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY,
    unsigned int blockDimZ, unsigned int sharedMemBytes, CUstream hStream,
    void **kernelParams);
extern "C" CUresult CUDAAPI cuLaunchHostFunc_ptsz(CUstream hStream, CUhostFn fn,
                                                  void *userData);
extern "C" CUresult CUDAAPI cuLaunchKernel_ptsz(
    CUfunction f, unsigned int gridDimX, unsigned int gridDimY,
    unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY,
    unsigned int blockDimZ, unsigned int sharedMemBytes, CUstream hStream,
    void **kernelParams, void **extra);
extern "C" CUresult CUDAAPI cuLaunchKernelEx_ptsz(const CUlaunchConfig *config,
                                                  CUfunction f,
                                                  void **kernelParams,
                                                  void **extra);
extern "C" CUresult CUDAAPI cuMemAllocAsync_ptsz(CUdeviceptr *dptr,
                                                 size_t bytesize,
                                                 CUstream hStream);
extern "C" CUresult CUDAAPI cuMemAllocFromPoolAsync_ptsz(CUdeviceptr *dptr,
                                                         size_t bytesize,
                                                         CUmemoryPool pool,
                                                         CUstream hStream);
extern "C" CUresult CUDAAPI cuMemFreeAsync_ptsz(CUdeviceptr dptr,
                                                CUstream hStream);
extern "C" CUresult CUDAAPI cuMemMapArrayAsync_ptsz(CUarrayMapInfo *mapInfoList,
                                                    unsigned int count,
                                                    CUstream hStream);
extern "C" CUresult CUDAAPI cuMemPrefetchAsync_ptsz(CUdeviceptr devPtr,
                                                    size_t count,
                                                    CUdevice dstDevice,
                                                    CUstream hStream);
#if CUDA_VERSION >= 12020
extern "C" CUresult CUDAAPI cuMemPrefetchAsync_v2_ptsz(CUdeviceptr devPtr,
                                                       size_t count,
                                                       CUmemLocation location,
                                                       unsigned int flags,
                                                       CUstream hStream);
#endif
extern "C" CUresult CUDAAPI cuMemcpy_ptds(CUdeviceptr dst, CUdeviceptr src,
                                          size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpy2DAsync_v2_ptsz(const CUDA_MEMCPY2D *pCopy,
                                                    CUstream hStream);
extern "C" CUresult CUDAAPI
cuMemcpy2DUnaligned_v2_ptds(const CUDA_MEMCPY2D *pCopy);
extern "C" CUresult CUDAAPI cuMemcpy2D_v2_ptds(const CUDA_MEMCPY2D *pCopy);
extern "C" CUresult CUDAAPI cuMemcpy3DAsync_v2_ptsz(const CUDA_MEMCPY3D *pCopy,
                                                    CUstream hStream);
extern "C" CUresult CUDAAPI
cuMemcpy3DPeer_ptds(const CUDA_MEMCPY3D_PEER *pCopy);
extern "C" CUresult CUDAAPI
cuMemcpy3DPeerAsync_ptsz(const CUDA_MEMCPY3D_PEER *pCopy, CUstream hStream);
extern "C" CUresult CUDAAPI cuMemcpy3D_v2_ptds(const CUDA_MEMCPY3D *pCopy);
extern "C" CUresult CUDAAPI cuMemcpyAtoA_v2_ptds(CUarray dstArray,
                                                 size_t dstOffset,
                                                 CUarray srcArray,
                                                 size_t srcOffset,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyAtoD_v2_ptds(CUdeviceptr dstDevice,
                                                 CUarray srcArray,
                                                 size_t srcOffset,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyAtoH_v2_ptds(void *dstHost,
                                                 CUarray srcArray,
                                                 size_t srcOffset,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyDtoA_v2_ptds(CUarray dstArray,
                                                 size_t dstOffset,
                                                 CUdeviceptr srcDevice,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyDtoDAsync_v2_ptsz(CUdeviceptr dstDevice,
                                                      CUdeviceptr srcDevice,
                                                      size_t ByteCount,
                                                      CUstream hStream);
extern "C" CUresult CUDAAPI cuMemcpyDtoD_v2_ptds(CUdeviceptr dstDevice,
                                                 CUdeviceptr srcDevice,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyDtoHAsync_v2_ptsz(void *dstHost,
                                                      CUdeviceptr srcDevice,
                                                      size_t ByteCount,
                                                      CUstream hStream);
extern "C" CUresult CUDAAPI cuMemcpyDtoH_v2_ptds(void *dstHost,
                                                 CUdeviceptr srcDevice,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyHtoDAsync_v2_ptsz(CUdeviceptr dstDevice,
                                                      const void *srcHost,
                                                      size_t ByteCount,
                                                      CUstream hStream);
extern "C" CUresult CUDAAPI cuMemcpyHtoD_v2_ptds(CUdeviceptr dstDevice,
                                                 const void *srcHost,
                                                 size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyPeer_ptds(CUdeviceptr dstDevice,
                                              CUcontext dstContext,
                                              CUdeviceptr srcDevice,
                                              CUcontext srcContext,
                                              size_t ByteCount);
extern "C" CUresult CUDAAPI cuMemcpyPeerAsync_ptsz(
    CUdeviceptr dstDevice, CUcontext dstContext, CUdeviceptr srcDevice,
    CUcontext srcContext, size_t ByteCount, CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD16Async_ptsz(CUdeviceptr dstDevice,
                                                  unsigned short us, size_t N,
                                                  CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD16_v2_ptds(CUdeviceptr dstDevice,
                                                unsigned short us, size_t N);
extern "C" CUresult CUDAAPI cuMemsetD2D16Async_ptsz(CUdeviceptr dstDevice,
                                                    size_t dstPitch,
                                                    unsigned short us,
                                                    size_t Width, size_t Height,
                                                    CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD2D16_v2_ptds(CUdeviceptr dstDevice,
                                                  size_t dstPitch,
                                                  unsigned short us,
                                                  size_t Width, size_t Height);
extern "C" CUresult CUDAAPI cuMemsetD2D32Async_ptsz(CUdeviceptr dstDevice,
                                                    size_t dstPitch,
                                                    unsigned int ui,
                                                    size_t Width, size_t Height,
                                                    CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD2D32_v2_ptds(CUdeviceptr dstDevice,
                                                  size_t dstPitch,
                                                  unsigned int ui, size_t Width,
                                                  size_t Height);
extern "C" CUresult CUDAAPI cuMemsetD2D8Async_ptsz(CUdeviceptr dstDevice,
                                                   size_t dstPitch,
                                                   unsigned char uc,
                                                   size_t Width, size_t Height,
                                                   CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD2D8_v2_ptds(CUdeviceptr dstDevice,
                                                 size_t dstPitch,
                                                 unsigned char uc, size_t Width,
                                                 size_t Height);
extern "C" CUresult CUDAAPI cuMemsetD32Async_ptsz(CUdeviceptr dstDevice,
                                                  unsigned int ui, size_t N,
                                                  CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD32_v2_ptds(CUdeviceptr dstDevice,
                                                unsigned int ui, size_t N);
extern "C" CUresult CUDAAPI cuMemsetD8Async_ptsz(CUdeviceptr dstDevice,
                                                 unsigned char uc, size_t N,
                                                 CUstream hStream);
extern "C" CUresult CUDAAPI cuMemsetD8_v2_ptds(CUdeviceptr dstDevice,
                                               unsigned char uc, size_t N);
extern "C" CUresult CUDAAPI cuSignalExternalSemaphoresAsync_ptsz(
    const CUexternalSemaphore *extSemArray,
    const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS *paramsArray,
    unsigned int numExtSems, CUstream stream);
extern "C" CUresult CUDAAPI cuStreamAddCallback_ptsz(CUstream hStream,
                                                     CUstreamCallback callback,
                                                     void *userData,
                                                     unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamAttachMemAsync_ptsz(CUstream hStream,
                                                        CUdeviceptr dptr,
                                                        size_t length,
                                                        unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamBatchMemOp_v2_ptsz(
    CUstream stream, unsigned int count, CUstreamBatchMemOpParams *paramArray,
    unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamBeginCapture_ptsz(CUstream hStream);
extern "C" CUresult CUDAAPI cuStreamBeginCaptureToGraph_ptsz(
    CUstream hStream, CUgraph hGraph, const CUgraphNode *dependencies,
    const CUgraphEdgeData *dependencyData, size_t numDependencies,
    CUstreamCaptureMode mode);
extern "C" CUresult CUDAAPI
cuStreamBeginCapture_v2_ptsz(CUstream hStream, CUstreamCaptureMode mode);
extern "C" CUresult CUDAAPI cuStreamCopyAttributes_ptsz(CUstream dst,
                                                        CUstream src);
extern "C" CUresult CUDAAPI cuStreamEndCapture_ptsz(CUstream hStream,
                                                    CUgraph *phGraph);
extern "C" CUresult CUDAAPI cuStreamGetAttribute_ptsz(
    CUstream hStream, CUstreamAttrID attr, CUstreamAttrValue *value_out);
extern "C" CUresult CUDAAPI cuStreamGetCaptureInfo_ptsz(
    CUstream hStream, CUstreamCaptureStatus *captureStatus_out,
    cuuint64_t *id_out);
extern "C" CUresult CUDAAPI cuStreamGetCaptureInfo_v2_ptsz(
    CUstream hStream, CUstreamCaptureStatus *captureStatus_out,
    cuuint64_t *id_out, CUgraph *graph_out,
    const CUgraphNode **dependencies_out, size_t *numDependencies_out);
extern "C" CUresult CUDAAPI cuStreamGetCaptureInfo_v3_ptsz(
    CUstream hStream, CUstreamCaptureStatus *captureStatus_out,
    cuuint64_t *id_out, CUgraph *graph_out,
    const CUgraphNode **dependencies_out, const CUgraphEdgeData **edgeData_out,
    size_t *numDependencies_out);
extern "C" CUresult CUDAAPI cuStreamGetCtx_ptsz(CUstream hStream,
                                                CUcontext *pctx);
#if CUDA_VERSION >= 13010
extern "C" CUresult CUDAAPI cuStreamGetDevResource_ptsz(CUstream hStream,
                                                        CUdevResource *resource,
                                                        CUdevResourceType type);
#endif
extern "C" CUresult CUDAAPI cuStreamGetDevice_ptsz(CUstream hStream,
                                                   CUdevice *device);
extern "C" CUresult CUDAAPI cuStreamGetFlags_ptsz(CUstream hStream,
                                                  unsigned int *flags);
extern "C" CUresult CUDAAPI cuStreamGetId_ptsz(CUstream hStream,
                                               unsigned long long *streamId);
extern "C" CUresult CUDAAPI cuStreamGetPriority_ptsz(CUstream hStream,
                                                     int *priority);
extern "C" CUresult CUDAAPI cuStreamIsCapturing_ptsz(
    CUstream hStream, CUstreamCaptureStatus *captureStatus);
extern "C" CUresult CUDAAPI cuStreamQuery_ptsz(CUstream hStream);
extern "C" CUresult CUDAAPI cuStreamSetAttribute_ptsz(
    CUstream hStream, CUstreamAttrID attr, const CUstreamAttrValue *value);
extern "C" CUresult CUDAAPI cuStreamSynchronize_ptsz(CUstream hStream);
extern "C" CUresult CUDAAPI cuStreamUpdateCaptureDependencies_ptsz(
    CUstream hStream, CUgraphNode *dependencies, size_t numDependencies,
    unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamUpdateCaptureDependencies_v2_ptsz(
    CUstream hStream, CUgraphNode *dependencies,
    const CUgraphEdgeData *dependencyData, size_t numDependencies,
    unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamWaitEvent_ptsz(CUstream hStream,
                                                   CUevent hEvent,
                                                   unsigned int Flags);
extern "C" CUresult CUDAAPI cuStreamWaitValue32_v2_ptsz(CUstream stream,
                                                        CUdeviceptr addr,
                                                        cuuint32_t value,
                                                        unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamWaitValue64_v2_ptsz(CUstream stream,
                                                        CUdeviceptr addr,
                                                        cuuint64_t value,
                                                        unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamWriteValue32_v2_ptsz(CUstream stream,
                                                         CUdeviceptr addr,
                                                         cuuint32_t value,
                                                         unsigned int flags);
extern "C" CUresult CUDAAPI cuStreamWriteValue64_v2_ptsz(CUstream stream,
                                                         CUdeviceptr addr,
                                                         cuuint64_t value,
                                                         unsigned int flags);
extern "C" CUresult CUDAAPI cuWaitExternalSemaphoresAsync_ptsz(
    const CUexternalSemaphore *extSemArray,
    const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS *paramsArray,
    unsigned int numExtSems, CUstream stream);
inline int lupine_implicit_stream_rpc(int operation) {
  if (!lupine_per_thread_default_stream)
    return operation;
  switch (operation) {
  case RPC_cuMemcpy2DUnaligned_v2:
    return RPC_cuMemcpy2DUnaligned_v2_ptds;
  case RPC_cuMemcpy2D_v2:
    return RPC_cuMemcpy2D_v2_ptds;
  case RPC_cuMemcpy3DPeer:
    return RPC_cuMemcpy3DPeer_ptds;
  case RPC_cuMemcpy3D_v2:
    return RPC_cuMemcpy3D_v2_ptds;
  case RPC_cuMemcpyAtoA_v2:
    return RPC_cuMemcpyAtoA_v2_ptds;
  case RPC_cuMemcpyAtoD_v2:
    return RPC_cuMemcpyAtoD_v2_ptds;
  case RPC_cuMemcpyAtoH_v2:
    return RPC_cuMemcpyAtoH_v2_ptds;
  case RPC_cuMemcpyDtoA_v2:
    return RPC_cuMemcpyDtoA_v2_ptds;
  case RPC_cuMemcpyDtoD_v2:
    return RPC_cuMemcpyDtoD_v2_ptds;
  case RPC_cuMemcpyDtoH_v2:
    return RPC_cuMemcpyDtoH_v2_ptds;
  case RPC_cuMemcpyHtoD_v2:
    return RPC_cuMemcpyHtoD_v2_ptds;
  case RPC_cuMemcpyPeer:
    return RPC_cuMemcpyPeer_ptds;
  case RPC_cuMemsetD16_v2:
    return RPC_cuMemsetD16_v2_ptds;
  case RPC_cuMemsetD2D16_v2:
    return RPC_cuMemsetD2D16_v2_ptds;
  case RPC_cuMemsetD2D32_v2:
    return RPC_cuMemsetD2D32_v2_ptds;
  case RPC_cuMemsetD2D8_v2:
    return RPC_cuMemsetD2D8_v2_ptds;
  case RPC_cuMemsetD32_v2:
    return RPC_cuMemsetD32_v2_ptds;
  case RPC_cuMemsetD8_v2:
    return RPC_cuMemsetD8_v2_ptds;
  default:
    return operation;
  }
}
inline const char *lupine_implicit_stream_symbol(const char *name) {
  if (!lupine_per_thread_default_stream)
    return name;
  if (strcmp(name, "cuMemcpy") == 0)
    return "cuMemcpy_ptds";
  if (strcmp(name, "cuMemcpy2DUnaligned_v2") == 0)
    return "cuMemcpy2DUnaligned_v2_ptds";
  if (strcmp(name, "cuMemcpy2D_v2") == 0)
    return "cuMemcpy2D_v2_ptds";
  if (strcmp(name, "cuMemcpy3DPeer") == 0)
    return "cuMemcpy3DPeer_ptds";
  if (strcmp(name, "cuMemcpy3D_v2") == 0)
    return "cuMemcpy3D_v2_ptds";
  if (strcmp(name, "cuMemcpyAtoA_v2") == 0)
    return "cuMemcpyAtoA_v2_ptds";
  if (strcmp(name, "cuMemcpyAtoD_v2") == 0)
    return "cuMemcpyAtoD_v2_ptds";
  if (strcmp(name, "cuMemcpyAtoH_v2") == 0)
    return "cuMemcpyAtoH_v2_ptds";
  if (strcmp(name, "cuMemcpyDtoA_v2") == 0)
    return "cuMemcpyDtoA_v2_ptds";
  if (strcmp(name, "cuMemcpyDtoD_v2") == 0)
    return "cuMemcpyDtoD_v2_ptds";
  if (strcmp(name, "cuMemcpyDtoH_v2") == 0)
    return "cuMemcpyDtoH_v2_ptds";
  if (strcmp(name, "cuMemcpyHtoD_v2") == 0)
    return "cuMemcpyHtoD_v2_ptds";
  if (strcmp(name, "cuMemcpyPeer") == 0)
    return "cuMemcpyPeer_ptds";
  if (strcmp(name, "cuMemsetD16_v2") == 0)
    return "cuMemsetD16_v2_ptds";
  if (strcmp(name, "cuMemsetD2D16_v2") == 0)
    return "cuMemsetD2D16_v2_ptds";
  if (strcmp(name, "cuMemsetD2D32_v2") == 0)
    return "cuMemsetD2D32_v2_ptds";
  if (strcmp(name, "cuMemsetD2D8_v2") == 0)
    return "cuMemsetD2D8_v2_ptds";
  if (strcmp(name, "cuMemsetD32_v2") == 0)
    return "cuMemsetD32_v2_ptds";
  if (strcmp(name, "cuMemsetD8_v2") == 0)
    return "cuMemsetD8_v2_ptds";
  return name;
}
void *lupine_stream_function(const char *name, int version, bool per_thread);
CUresult lupine_stream_add_callback_per_thread(CUstream stream,
                                               CUstreamCallback callback,
                                               void *user_data,
                                               unsigned int flags);
