// Generated by codegen.py. Do not edit by hand.

int handle_nvjpegGetProperty(conn_t *conn);
int handle_nvjpegGetCudartProperty(conn_t *conn);
int handle_nvjpegCreate(conn_t *conn);
int handle_nvjpegCreateSimple(conn_t *conn);
int handle_nvjpegCreateEx(conn_t *conn);
int handle_nvjpegCreateExV2(conn_t *conn);
int handle_nvjpegDestroy(conn_t *conn);
int handle_nvjpegSetDeviceMemoryPadding(conn_t *conn);
int handle_nvjpegGetDeviceMemoryPadding(conn_t *conn);
int handle_nvjpegSetPinnedMemoryPadding(conn_t *conn);
int handle_nvjpegGetPinnedMemoryPadding(conn_t *conn);
int handle_nvjpegGetHardwareDecoderInfo(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1204
int handle_nvjpegGetHardwareEncoderInfo(conn_t *conn);
#endif
int handle_nvjpegJpegStateCreate(conn_t *conn);
int handle_nvjpegGetImageInfo(conn_t *conn);
int handle_nvjpegDecode(conn_t *conn);
int handle_nvjpegDecodeBatchedInitialize(conn_t *conn);
int handle_nvjpegDecodeBatchedPreAllocate(conn_t *conn);
int handle_nvjpegEncoderStateCreate(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1204
int handle_nvjpegEncoderStateCreateWithBackend(conn_t *conn);
#endif
int handle_nvjpegEncoderStateDestroy(conn_t *conn);
int handle_nvjpegEncoderParamsCreate(conn_t *conn);
int handle_nvjpegEncoderParamsDestroy(conn_t *conn);
int handle_nvjpegEncoderParamsSetQuality(conn_t *conn);
int handle_nvjpegEncoderParamsSetEncoding(conn_t *conn);
int handle_nvjpegEncoderParamsSetOptimizedHuffman(conn_t *conn);
int handle_nvjpegEncoderParamsSetSamplingFactors(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1204
int handle_nvjpegEncoderParamsSetRestartInterval(conn_t *conn);
#endif
int handle_nvjpegEncodeGetBufferSize(conn_t *conn);
int handle_nvjpegEncodeYUV(conn_t *conn);
int handle_nvjpegEncodeImage(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1204
int handle_nvjpegEncode(conn_t *conn);
#endif
int handle_nvjpegEncodeRetrieveBitstreamDevice(conn_t *conn);
int handle_nvjpegEncodeRetrieveBitstream(conn_t *conn);
int handle_nvjpegBufferPinnedCreate(conn_t *conn);
int handle_nvjpegBufferPinnedCreateV2(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1203
int handle_nvjpegBufferPinnedResize(conn_t *conn);
#endif
int handle_nvjpegBufferPinnedDestroy(conn_t *conn);
int handle_nvjpegBufferDeviceCreate(conn_t *conn);
int handle_nvjpegBufferDeviceCreateV2(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1203
int handle_nvjpegBufferDeviceResize(conn_t *conn);
#endif
int handle_nvjpegBufferDeviceDestroy(conn_t *conn);
int handle_nvjpegBufferPinnedRetrieve(conn_t *conn);
int handle_nvjpegBufferDeviceRetrieve(conn_t *conn);
int handle_nvjpegStateAttachPinnedBuffer(conn_t *conn);
int handle_nvjpegStateAttachDeviceBuffer(conn_t *conn);
int handle_nvjpegJpegStreamCreate(conn_t *conn);
int handle_nvjpegJpegStreamGetJpegEncoding(conn_t *conn);
int handle_nvjpegJpegStreamGetFrameDimensions(conn_t *conn);
int handle_nvjpegJpegStreamGetComponentsNum(conn_t *conn);
int handle_nvjpegJpegStreamGetComponentDimensions(conn_t *conn);
int handle_nvjpegJpegStreamGetExifOrientation(conn_t *conn);
#if NVJPEG_VER_MAJOR * 100 + NVJPEG_VER_MINOR >= 1201
int handle_nvjpegJpegStreamGetSamplePrecision(conn_t *conn);
#endif
int handle_nvjpegJpegStreamGetChromaSubsampling(conn_t *conn);
int handle_nvjpegDecodeParamsCreate(conn_t *conn);
int handle_nvjpegDecodeParamsDestroy(conn_t *conn);
int handle_nvjpegDecodeParamsSetOutputFormat(conn_t *conn);
int handle_nvjpegDecodeParamsSetROI(conn_t *conn);
int handle_nvjpegDecodeParamsSetAllowCMYK(conn_t *conn);
int handle_nvjpegDecodeParamsSetScaleFactor(conn_t *conn);
int handle_nvjpegDecodeParamsSetExifOrientation(conn_t *conn);
int handle_nvjpegDecoderCreate(conn_t *conn);
int handle_nvjpegDecoderDestroy(conn_t *conn);
int handle_nvjpegDecoderJpegSupported(conn_t *conn);
int handle_nvjpegDecodeBatchedSupported(conn_t *conn);
int handle_nvjpegDecodeBatchedSupportedEx(conn_t *conn);
int handle_nvjpegDecoderStateCreate(conn_t *conn);
int handle_nvjpegDecodeJpeg(conn_t *conn);
int handle_nvjpegDecodeJpegHost(conn_t *conn);
int handle_nvjpegDecodeJpegTransferToDevice(conn_t *conn);
int handle_nvjpegDecodeJpegDevice(conn_t *conn);
int handle_nvjpegEncoderParamsCopyMetadata(conn_t *conn);
#if NVJPEG_VER_MAJOR < 13
int handle_nvjpegEncoderParamsCopyHuffmanTables(conn_t *conn);
#endif
int handle_nvjpegEncoderParamsCopyQuantizationTables(conn_t *conn);
