// Generated by codegen.py. Do not edit by hand.

int handle_cudnnGetVersion(conn_t *conn);
int handle_cudnnGetMaxDeviceVersion(conn_t *conn);
int handle_cudnnGetCudartVersion(conn_t *conn);
int handle_cudnnGetLastErrorString(conn_t *conn);
int handle_cudnnQueryRuntimeError(conn_t *conn);
int handle_cudnnGetProperty(conn_t *conn);
int handle_cudnnCreate(conn_t *conn);
int handle_cudnnDestroy(conn_t *conn);
int handle_cudnnSetStream(conn_t *conn);
int handle_cudnnGetStream(conn_t *conn);
int handle_cudnnGraphVersionCheck(conn_t *conn);
int handle_cudnnBackendCreateDescriptor(conn_t *conn);
int handle_cudnnBackendDestroyDescriptor(conn_t *conn);
int handle_cudnnBackendInitialize(conn_t *conn);
int handle_cudnnBackendFinalize(conn_t *conn);
#if CUDNN_VERSION >= 92300
int handle_cudnnGetExecutionPlanWorkspaceSize(conn_t *conn);
#endif
int handle_cudnnBackendExecute(conn_t *conn);
#if CUDNN_VERSION >= 90500
int handle_cudnnBackendPopulateCudaGraph(conn_t *conn);
#endif
#if CUDNN_VERSION >= 90500
int handle_cudnnBackendUpdateCudaGraph(conn_t *conn);
#endif
int handle_cudnnCreateTensorDescriptor(conn_t *conn);
int handle_cudnnSetTensor4dDescriptor(conn_t *conn);
int handle_cudnnSetTensor4dDescriptorEx(conn_t *conn);
int handle_cudnnGetTensor4dDescriptor(conn_t *conn);
int handle_cudnnSetTensorNdDescriptor(conn_t *conn);
int handle_cudnnSetTensorNdDescriptorEx(conn_t *conn);
int handle_cudnnGetTensorNdDescriptor(conn_t *conn);
int handle_cudnnGetTensorSizeInBytes(conn_t *conn);
int handle_cudnnDestroyTensorDescriptor(conn_t *conn);
int handle_cudnnInitTransformDest(conn_t *conn);
int handle_cudnnCreateTensorTransformDescriptor(conn_t *conn);
int handle_cudnnSetTensorTransformDescriptor(conn_t *conn);
int handle_cudnnGetTensorTransformDescriptor(conn_t *conn);
int handle_cudnnDestroyTensorTransformDescriptor(conn_t *conn);
int handle_cudnnTransformTensor(conn_t *conn);
int handle_cudnnTransformTensorEx(conn_t *conn);
int handle_cudnnAddTensor(conn_t *conn);
int handle_cudnnCreateOpTensorDescriptor(conn_t *conn);
int handle_cudnnSetOpTensorDescriptor(conn_t *conn);
int handle_cudnnGetOpTensorDescriptor(conn_t *conn);
int handle_cudnnDestroyOpTensorDescriptor(conn_t *conn);
int handle_cudnnOpTensor(conn_t *conn);
int handle_cudnnCreateReduceTensorDescriptor(conn_t *conn);
int handle_cudnnSetReduceTensorDescriptor(conn_t *conn);
int handle_cudnnGetReduceTensorDescriptor(conn_t *conn);
int handle_cudnnDestroyReduceTensorDescriptor(conn_t *conn);
int handle_cudnnGetReductionIndicesSize(conn_t *conn);
int handle_cudnnGetReductionWorkspaceSize(conn_t *conn);
int handle_cudnnReduceTensor(conn_t *conn);
int handle_cudnnSetTensor(conn_t *conn);
int handle_cudnnScaleTensor(conn_t *conn);
int handle_cudnnCreateFilterDescriptor(conn_t *conn);
int handle_cudnnSetFilter4dDescriptor(conn_t *conn);
int handle_cudnnGetFilter4dDescriptor(conn_t *conn);
int handle_cudnnSetFilterNdDescriptor(conn_t *conn);
int handle_cudnnGetFilterNdDescriptor(conn_t *conn);
int handle_cudnnGetFilterSizeInBytes(conn_t *conn);
int handle_cudnnTransformFilter(conn_t *conn);
int handle_cudnnDestroyFilterDescriptor(conn_t *conn);
int handle_cudnnSoftmaxForward(conn_t *conn);
int handle_cudnnCreatePoolingDescriptor(conn_t *conn);
int handle_cudnnSetPooling2dDescriptor(conn_t *conn);
int handle_cudnnGetPooling2dDescriptor(conn_t *conn);
int handle_cudnnSetPoolingNdDescriptor(conn_t *conn);
int handle_cudnnGetPoolingNdDescriptor(conn_t *conn);
int handle_cudnnGetPoolingNdForwardOutputDim(conn_t *conn);
int handle_cudnnGetPooling2dForwardOutputDim(conn_t *conn);
int handle_cudnnDestroyPoolingDescriptor(conn_t *conn);
int handle_cudnnPoolingForward(conn_t *conn);
int handle_cudnnCreateActivationDescriptor(conn_t *conn);
int handle_cudnnSetActivationDescriptor(conn_t *conn);
int handle_cudnnGetActivationDescriptor(conn_t *conn);
int handle_cudnnSetActivationDescriptorSwishBeta(conn_t *conn);
int handle_cudnnGetActivationDescriptorSwishBeta(conn_t *conn);
int handle_cudnnDestroyActivationDescriptor(conn_t *conn);
int handle_cudnnActivationForward(conn_t *conn);
int handle_cudnnCreateLRNDescriptor(conn_t *conn);
int handle_cudnnSetLRNDescriptor(conn_t *conn);
int handle_cudnnGetLRNDescriptor(conn_t *conn);
int handle_cudnnDestroyLRNDescriptor(conn_t *conn);
int handle_cudnnLRNCrossChannelForward(conn_t *conn);
int handle_cudnnDivisiveNormalizationForward(conn_t *conn);
int handle_cudnnDeriveBNTensorDescriptor(conn_t *conn);
int handle_cudnnBatchNormalizationForwardInference(conn_t *conn);
int handle_cudnnDeriveNormTensorDescriptor(conn_t *conn);
int handle_cudnnNormalizationForwardInference(conn_t *conn);
int handle_cudnnCreateSpatialTransformerDescriptor(conn_t *conn);
int handle_cudnnSetSpatialTransformerNdDescriptor(conn_t *conn);
int handle_cudnnDestroySpatialTransformerDescriptor(conn_t *conn);
int handle_cudnnSpatialTfGridGeneratorForward(conn_t *conn);
int handle_cudnnSpatialTfSamplerForward(conn_t *conn);
int handle_cudnnCreateDropoutDescriptor(conn_t *conn);
int handle_cudnnDestroyDropoutDescriptor(conn_t *conn);
int handle_cudnnDropoutGetStatesSize(conn_t *conn);
int handle_cudnnDropoutGetReserveSpaceSize(conn_t *conn);
int handle_cudnnSetDropoutDescriptor(conn_t *conn);
int handle_cudnnRestoreDropoutDescriptor(conn_t *conn);
int handle_cudnnGetDropoutDescriptor(conn_t *conn);
int handle_cudnnDropoutForward(conn_t *conn);
int handle_cudnnOpsVersionCheck(conn_t *conn);
int handle_cudnnSoftmaxBackward(conn_t *conn);
int handle_cudnnPoolingBackward(conn_t *conn);
int handle_cudnnActivationBackward(conn_t *conn);
int handle_cudnnLRNCrossChannelBackward(conn_t *conn);
int handle_cudnnDivisiveNormalizationBackward(conn_t *conn);
int handle_cudnnGetBatchNormalizationForwardTrainingExWorkspaceSize(
    conn_t *conn);
int handle_cudnnGetBatchNormalizationBackwardExWorkspaceSize(conn_t *conn);
int handle_cudnnGetBatchNormalizationTrainingExReserveSpaceSize(conn_t *conn);
int handle_cudnnBatchNormalizationForwardTraining(conn_t *conn);
int handle_cudnnBatchNormalizationForwardTrainingEx(conn_t *conn);
int handle_cudnnBatchNormalizationBackward(conn_t *conn);
int handle_cudnnBatchNormalizationBackwardEx(conn_t *conn);
int handle_cudnnGetNormalizationForwardTrainingWorkspaceSize(conn_t *conn);
int handle_cudnnGetNormalizationBackwardWorkspaceSize(conn_t *conn);
int handle_cudnnGetNormalizationTrainingReserveSpaceSize(conn_t *conn);
int handle_cudnnNormalizationForwardTraining(conn_t *conn);
int handle_cudnnNormalizationBackward(conn_t *conn);
int handle_cudnnSpatialTfGridGeneratorBackward(conn_t *conn);
int handle_cudnnSpatialTfSamplerBackward(conn_t *conn);
int handle_cudnnDropoutBackward(conn_t *conn);
int handle_cudnnCreateConvolutionDescriptor(conn_t *conn);
int handle_cudnnDestroyConvolutionDescriptor(conn_t *conn);
int handle_cudnnSetConvolutionMathType(conn_t *conn);
int handle_cudnnGetConvolutionMathType(conn_t *conn);
int handle_cudnnSetConvolutionGroupCount(conn_t *conn);
int handle_cudnnGetConvolutionGroupCount(conn_t *conn);
int handle_cudnnSetConvolutionReorderType(conn_t *conn);
int handle_cudnnGetConvolutionReorderType(conn_t *conn);
int handle_cudnnSetConvolution2dDescriptor(conn_t *conn);
int handle_cudnnGetConvolution2dDescriptor(conn_t *conn);
int handle_cudnnSetConvolutionNdDescriptor(conn_t *conn);
int handle_cudnnGetConvolutionNdDescriptor(conn_t *conn);
int handle_cudnnGetConvolution2dForwardOutputDim(conn_t *conn);
int handle_cudnnGetConvolutionNdForwardOutputDim(conn_t *conn);
int handle_cudnnGetConvolutionForwardAlgorithmMaxCount(conn_t *conn);
int handle_cudnnGetConvolutionForwardAlgorithm_v7(conn_t *conn);
int handle_cudnnFindConvolutionForwardAlgorithm(conn_t *conn);
int handle_cudnnFindConvolutionForwardAlgorithmEx(conn_t *conn);
int handle_cudnnIm2Col(conn_t *conn);
int handle_cudnnReorderFilterAndBias(conn_t *conn);
int handle_cudnnGetConvolutionForwardWorkspaceSize(conn_t *conn);
int handle_cudnnConvolutionForward(conn_t *conn);
int handle_cudnnConvolutionBiasActivationForward(conn_t *conn);
int handle_cudnnGetConvolutionBackwardDataAlgorithmMaxCount(conn_t *conn);
int handle_cudnnFindConvolutionBackwardDataAlgorithm(conn_t *conn);
int handle_cudnnFindConvolutionBackwardDataAlgorithmEx(conn_t *conn);
int handle_cudnnGetConvolutionBackwardDataAlgorithm_v7(conn_t *conn);
int handle_cudnnGetConvolutionBackwardDataWorkspaceSize(conn_t *conn);
int handle_cudnnConvolutionBackwardData(conn_t *conn);
int handle_cudnnGetFoldedConvBackwardDataDescriptors(conn_t *conn);
int handle_cudnnCnnVersionCheck(conn_t *conn);
int handle_cudnnGetConvolutionBackwardFilterAlgorithmMaxCount(conn_t *conn);
int handle_cudnnFindConvolutionBackwardFilterAlgorithm(conn_t *conn);
int handle_cudnnFindConvolutionBackwardFilterAlgorithmEx(conn_t *conn);
int handle_cudnnGetConvolutionBackwardFilterAlgorithm_v7(conn_t *conn);
int handle_cudnnGetConvolutionBackwardFilterWorkspaceSize(conn_t *conn);
int handle_cudnnConvolutionBackwardFilter(conn_t *conn);
int handle_cudnnConvolutionBackwardBias(conn_t *conn);
int handle_cudnnCreateFusedOpsConstParamPack(conn_t *conn);
int handle_cudnnDestroyFusedOpsConstParamPack(conn_t *conn);
int handle_cudnnCreateFusedOpsVariantParamPack(conn_t *conn);
int handle_cudnnDestroyFusedOpsVariantParamPack(conn_t *conn);
int handle_cudnnCreateFusedOpsPlan(conn_t *conn);
int handle_cudnnDestroyFusedOpsPlan(conn_t *conn);
int handle_cudnnMakeFusedOpsPlan(conn_t *conn);
int handle_cudnnFusedOpsExecute(conn_t *conn);
int handle_cudnnCreateRNNDescriptor(conn_t *conn);
int handle_cudnnDestroyRNNDescriptor(conn_t *conn);
int handle_cudnnSetRNNDescriptor_v8(conn_t *conn);
int handle_cudnnGetRNNDescriptor_v8(conn_t *conn);
int handle_cudnnRNNSetClip_v8(conn_t *conn);
int handle_cudnnRNNSetClip_v9(conn_t *conn);
int handle_cudnnRNNGetClip_v8(conn_t *conn);
int handle_cudnnRNNGetClip_v9(conn_t *conn);
int handle_cudnnBuildRNNDynamic(conn_t *conn);
int handle_cudnnGetRNNTempSpaceSizes(conn_t *conn);
int handle_cudnnGetRNNWeightSpaceSize(conn_t *conn);
int handle_cudnnGetRNNWeightParams(conn_t *conn);
int handle_cudnnCreateRNNDataDescriptor(conn_t *conn);
int handle_cudnnDestroyRNNDataDescriptor(conn_t *conn);
int handle_cudnnSetRNNDataDescriptor(conn_t *conn);
int handle_cudnnGetRNNDataDescriptor(conn_t *conn);
int handle_cudnnRNNForward(conn_t *conn);
int handle_cudnnCreateSeqDataDescriptor(conn_t *conn);
int handle_cudnnDestroySeqDataDescriptor(conn_t *conn);
int handle_cudnnSetSeqDataDescriptor(conn_t *conn);
int handle_cudnnGetSeqDataDescriptor(conn_t *conn);
int handle_cudnnCreateAttnDescriptor(conn_t *conn);
int handle_cudnnDestroyAttnDescriptor(conn_t *conn);
int handle_cudnnSetAttnDescriptor(conn_t *conn);
int handle_cudnnGetAttnDescriptor(conn_t *conn);
int handle_cudnnGetMultiHeadAttnBuffers(conn_t *conn);
int handle_cudnnGetMultiHeadAttnWeights(conn_t *conn);
int handle_cudnnAdvVersionCheck(conn_t *conn);
int handle_cudnnRNNBackwardData_v8(conn_t *conn);
int handle_cudnnRNNBackwardWeights_v8(conn_t *conn);
int handle_cudnnMultiHeadAttnBackwardWeights(conn_t *conn);
int handle_cudnnCreateCTCLossDescriptor(conn_t *conn);
int handle_cudnnSetCTCLossDescriptor(conn_t *conn);
int handle_cudnnSetCTCLossDescriptorEx(conn_t *conn);
int handle_cudnnSetCTCLossDescriptor_v8(conn_t *conn);
int handle_cudnnSetCTCLossDescriptor_v9(conn_t *conn);
int handle_cudnnGetCTCLossDescriptor(conn_t *conn);
int handle_cudnnGetCTCLossDescriptorEx(conn_t *conn);
int handle_cudnnGetCTCLossDescriptor_v8(conn_t *conn);
int handle_cudnnGetCTCLossDescriptor_v9(conn_t *conn);
int handle_cudnnDestroyCTCLossDescriptor(conn_t *conn);
int handle_cudnnCTCLoss_v8(conn_t *conn);
int handle_cudnnGetCTCLossWorkspaceSize_v8(conn_t *conn);
#if CUDNN_VERSION >= 92200
int handle_cudnnSubquadraticOpsVersionCheck(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92200
int handle_cudnnCausalConv1dForward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92200
int handle_cudnnCausalConv1dBackward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92400
int handle_cudnnCausalConv1dNwhForward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92400
int handle_cudnnCausalConv1dNwhBackward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92400
int handle_cudnnB2BCausalConv1dForward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92400
int handle_cudnnB2BCausalConv1dBackward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnFFTCausalConv1dForward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnFFTCausalConv1dBackward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnLongFFTCausalConv1dGetBufferSizes(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnLongFFTCausalConv1dForward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnLongFFTCausalConv1dBackward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnGnnAggSimpleForward(conn_t *conn);
#endif
#if CUDNN_VERSION >= 92600
int handle_cudnnGnnAggSimpleBackward(conn_t *conn);
#endif
