// Generated by codegen.py. Do not edit by hand.

int handle_nppiDilate_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_8u_C1R(conn_t *conn);
#endif
int handle_nppiDilate_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_8u_C3R(conn_t *conn);
#endif
int handle_nppiDilate_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_8u_C4R(conn_t *conn);
#endif
int handle_nppiDilate_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_8u_AC4R(conn_t *conn);
#endif
int handle_nppiDilate_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_16u_C1R(conn_t *conn);
#endif
int handle_nppiDilate_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_16u_C3R(conn_t *conn);
#endif
int handle_nppiDilate_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_16u_C4R(conn_t *conn);
#endif
int handle_nppiDilate_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_16u_AC4R(conn_t *conn);
#endif
int handle_nppiDilate_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_32f_C1R(conn_t *conn);
#endif
int handle_nppiDilate_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_32f_C3R(conn_t *conn);
#endif
int handle_nppiDilate_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_32f_C4R(conn_t *conn);
#endif
int handle_nppiDilate_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate_32f_AC4R(conn_t *conn);
#endif
int handle_nppiDilateBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiDilateBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiDilateBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiDilateBorder_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_8u_AC4R(conn_t *conn);
#endif
int handle_nppiDilateBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiDilateBorder_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_16u_C3R(conn_t *conn);
#endif
int handle_nppiDilateBorder_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_16u_C4R(conn_t *conn);
#endif
int handle_nppiDilateBorder_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_16u_AC4R(conn_t *conn);
#endif
int handle_nppiDilateBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiDilateBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiDilateBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiDilateBorder_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilateBorder_32f_AC4R(conn_t *conn);
#endif
int handle_nppiGrayDilateBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGrayDilateBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiGrayDilateBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGrayDilateBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_8u_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_8u_C3R(conn_t *conn);
#endif
int handle_nppiDilate3x3_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_8u_C4R(conn_t *conn);
#endif
int handle_nppiDilate3x3_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_8u_AC4R(conn_t *conn);
#endif
int handle_nppiDilate3x3_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_16u_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_16u_C3R(conn_t *conn);
#endif
int handle_nppiDilate3x3_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_16u_C4R(conn_t *conn);
#endif
int handle_nppiDilate3x3_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_16u_AC4R(conn_t *conn);
#endif
int handle_nppiDilate3x3_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_32f_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_32f_C3R(conn_t *conn);
#endif
int handle_nppiDilate3x3_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_32f_C4R(conn_t *conn);
#endif
int handle_nppiDilate3x3_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_32f_AC4R(conn_t *conn);
#endif
int handle_nppiDilate3x3_64f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3_64f_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_8u_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_8u_C3R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_8u_C4R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_8u_AC4R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_16u_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_16u_C3R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_16u_C4R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_16u_AC4R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_32f_C1R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_32f_C3R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_32f_C4R(conn_t *conn);
#endif
int handle_nppiDilate3x3Border_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiDilate3x3Border_32f_AC4R(conn_t *conn);
#endif
int handle_nppiErode_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_8u_C1R(conn_t *conn);
#endif
int handle_nppiErode_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_8u_C3R(conn_t *conn);
#endif
int handle_nppiErode_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_8u_C4R(conn_t *conn);
#endif
int handle_nppiErode_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_8u_AC4R(conn_t *conn);
#endif
int handle_nppiErode_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_16u_C1R(conn_t *conn);
#endif
int handle_nppiErode_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_16u_C3R(conn_t *conn);
#endif
int handle_nppiErode_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_16u_C4R(conn_t *conn);
#endif
int handle_nppiErode_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_16u_AC4R(conn_t *conn);
#endif
int handle_nppiErode_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_32f_C1R(conn_t *conn);
#endif
int handle_nppiErode_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_32f_C3R(conn_t *conn);
#endif
int handle_nppiErode_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_32f_C4R(conn_t *conn);
#endif
int handle_nppiErode_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode_32f_AC4R(conn_t *conn);
#endif
int handle_nppiErodeBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiErodeBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiErodeBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiErodeBorder_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_8u_AC4R(conn_t *conn);
#endif
int handle_nppiErodeBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiErodeBorder_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_16u_C3R(conn_t *conn);
#endif
int handle_nppiErodeBorder_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_16u_C4R(conn_t *conn);
#endif
int handle_nppiErodeBorder_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_16u_AC4R(conn_t *conn);
#endif
int handle_nppiErodeBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiErodeBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiErodeBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiErodeBorder_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErodeBorder_32f_AC4R(conn_t *conn);
#endif
int handle_nppiGrayErodeBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGrayErodeBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiGrayErodeBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiGrayErodeBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_8u_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_8u_C3R(conn_t *conn);
#endif
int handle_nppiErode3x3_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_8u_C4R(conn_t *conn);
#endif
int handle_nppiErode3x3_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_8u_AC4R(conn_t *conn);
#endif
int handle_nppiErode3x3_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_16u_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_16u_C3R(conn_t *conn);
#endif
int handle_nppiErode3x3_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_16u_C4R(conn_t *conn);
#endif
int handle_nppiErode3x3_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_16u_AC4R(conn_t *conn);
#endif
int handle_nppiErode3x3_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_32f_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_32f_C3R(conn_t *conn);
#endif
int handle_nppiErode3x3_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_32f_C4R(conn_t *conn);
#endif
int handle_nppiErode3x3_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_32f_AC4R(conn_t *conn);
#endif
int handle_nppiErode3x3_64f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3_64f_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_8u_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_8u_C3R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_8u_C4R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_8u_AC4R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_16u_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_16u_C3R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_16u_C4R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_16u_AC4R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_32f_C1R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_32f_C3R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_32f_C4R(conn_t *conn);
#endif
int handle_nppiErode3x3Border_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiErode3x3Border_32f_AC4R(conn_t *conn);
#endif
int handle_nppiMorphGetBufferSize_8u_C1R(conn_t *conn);
int handle_nppiMorphGetBufferSize_8u_C3R(conn_t *conn);
int handle_nppiMorphGetBufferSize_8u_C4R(conn_t *conn);
int handle_nppiMorphGetBufferSize_16u_C1R(conn_t *conn);
int handle_nppiMorphGetBufferSize_16s_C1R(conn_t *conn);
int handle_nppiMorphGetBufferSize_32f_C1R(conn_t *conn);
int handle_nppiMorphGetBufferSize_32f_C3R(conn_t *conn);
int handle_nppiMorphGetBufferSize_32f_C4R(conn_t *conn);
int handle_nppiMorphCloseBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiMorphCloseBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphCloseBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiMorphOpenBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphOpenBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiMorphTopHatBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphTopHatBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiMorphBlackHatBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphBlackHatBorder_32f_C4R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_8u_C1R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_8u_C3R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_8u_C4R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_16u_C1R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_16s_C1R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_32f_C1R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_32f_C3R(conn_t *conn);
#endif
int handle_nppiMorphGradientBorder_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMorphGradientBorder_32f_C4R(conn_t *conn);
#endif
