// Generated by codegen.py. Do not edit by hand.

int handle_cublasLtCreate(conn_t *conn);
int handle_cublasLtDestroy(conn_t *conn);
#if CUBLAS_VERSION >= 120900
int handle_cublasLtDisableCpuInstructionsSetMask(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasLtEmulationDescGetAttribute(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasLtEmulationDescInit_internal(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasLtEmulationDescSetAttribute(conn_t *conn);
#endif

int handle_cublasLtGetCudartVersion(conn_t *conn);
int handle_cublasLtGetProperty(conn_t *conn);
int handle_cublasLtGetVersion(conn_t *conn);
int handle_cublasLtHeuristicsCacheGetCapacity(conn_t *conn);
int handle_cublasLtHeuristicsCacheSetCapacity(conn_t *conn);
int handle_cublasLtLoggerForceDisable(conn_t *conn);
int handle_cublasLtLoggerOpenFile(conn_t *conn);
int handle_cublasLtLoggerSetLevel(conn_t *conn);
int handle_cublasLtLoggerSetMask(conn_t *conn);
int handle_cublasLtMatmul(conn_t *conn);
int handle_cublasLtMatmulAlgoCapGetAttribute(conn_t *conn);
int handle_cublasLtMatmulAlgoCheck(conn_t *conn);
#if CUBLAS_VERSION >= 130300
int handle_cublasLtMatmulAlgoCheckForStream(conn_t *conn);
#endif

int handle_cublasLtMatmulAlgoConfigGetAttribute(conn_t *conn);
int handle_cublasLtMatmulAlgoConfigSetAttribute(conn_t *conn);
int handle_cublasLtMatmulAlgoGetHeuristic(conn_t *conn);
#if CUBLAS_VERSION >= 130300
int handle_cublasLtMatmulAlgoGetHeuristicForStream(conn_t *conn);
#endif

int handle_cublasLtMatmulAlgoGetIds(conn_t *conn);
int handle_cublasLtMatmulAlgoInit(conn_t *conn);
int handle_cublasLtMatmulDescGetAttribute(conn_t *conn);
int handle_cublasLtMatmulDescInit_internal(conn_t *conn);
int handle_cublasLtMatmulDescSetAttribute(conn_t *conn);
int handle_cublasLtMatmulPreferenceGetAttribute(conn_t *conn);
int handle_cublasLtMatmulPreferenceInit_internal(conn_t *conn);
int handle_cublasLtMatmulPreferenceSetAttribute(conn_t *conn);
int handle_cublasLtMatrixLayoutGetAttribute(conn_t *conn);
int handle_cublasLtMatrixLayoutInit_internal(conn_t *conn);
int handle_cublasLtMatrixLayoutSetAttribute(conn_t *conn);
int handle_cublasLtMatrixTransform(conn_t *conn);
int handle_cublasLtMatrixTransformDescGetAttribute(conn_t *conn);
int handle_cublasLtMatrixTransformDescInit_internal(conn_t *conn);
int handle_cublasLtMatrixTransformDescSetAttribute(conn_t *conn);
