// Generated by codegen.py. Do not edit.
#pragma once
#include "cuda_stream_semantics.h"
extern "C" CUresult CUDAAPI cuMemcpy_ptds(CUdeviceptr dst, CUdeviceptr src,
                                          size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpy(CUdeviceptr dst, CUdeviceptr src,
                                         size_t ByteCount) {
  return lupine_per_thread_default_stream ? cuMemcpy_ptds(dst, src, ByteCount)
                                          : cuMemcpy(dst, src, ByteCount);
}
extern "C" CUresult CUDAAPI
cuMemcpy2DUnaligned_v2_ptds(const CUDA_MEMCPY2D *pCopy);
inline CUresult
lupine_implicit_cuMemcpy2DUnaligned_v2(const CUDA_MEMCPY2D *pCopy) {
  return lupine_per_thread_default_stream ? cuMemcpy2DUnaligned_v2_ptds(pCopy)
                                          : cuMemcpy2DUnaligned_v2(pCopy);
}
extern "C" CUresult CUDAAPI cuMemcpy2D_v2_ptds(const CUDA_MEMCPY2D *pCopy);
inline CUresult lupine_implicit_cuMemcpy2D_v2(const CUDA_MEMCPY2D *pCopy) {
  return lupine_per_thread_default_stream ? cuMemcpy2D_v2_ptds(pCopy)
                                          : cuMemcpy2D_v2(pCopy);
}
extern "C" CUresult CUDAAPI
cuMemcpy3DPeer_ptds(const CUDA_MEMCPY3D_PEER *pCopy);
inline CUresult
lupine_implicit_cuMemcpy3DPeer(const CUDA_MEMCPY3D_PEER *pCopy) {
  return lupine_per_thread_default_stream ? cuMemcpy3DPeer_ptds(pCopy)
                                          : cuMemcpy3DPeer(pCopy);
}
extern "C" CUresult CUDAAPI cuMemcpy3D_v2_ptds(const CUDA_MEMCPY3D *pCopy);
inline CUresult lupine_implicit_cuMemcpy3D_v2(const CUDA_MEMCPY3D *pCopy) {
  return lupine_per_thread_default_stream ? cuMemcpy3D_v2_ptds(pCopy)
                                          : cuMemcpy3D_v2(pCopy);
}
extern "C" CUresult CUDAAPI cuMemcpyAtoA_v2_ptds(CUarray dstArray,
                                                 size_t dstOffset,
                                                 CUarray srcArray,
                                                 size_t srcOffset,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyAtoA_v2(CUarray dstArray,
                                                size_t dstOffset,
                                                CUarray srcArray,
                                                size_t srcOffset,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyAtoA_v2_ptds(dstArray, dstOffset, srcArray, srcOffset,
                                    ByteCount)
             : cuMemcpyAtoA_v2(dstArray, dstOffset, srcArray, srcOffset,
                               ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyAtoD_v2_ptds(CUdeviceptr dstDevice,
                                                 CUarray srcArray,
                                                 size_t srcOffset,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyAtoD_v2(CUdeviceptr dstDevice,
                                                CUarray srcArray,
                                                size_t srcOffset,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyAtoD_v2_ptds(dstDevice, srcArray, srcOffset, ByteCount)
             : cuMemcpyAtoD_v2(dstDevice, srcArray, srcOffset, ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyAtoH_v2_ptds(void *dstHost,
                                                 CUarray srcArray,
                                                 size_t srcOffset,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyAtoH_v2(void *dstHost, CUarray srcArray,
                                                size_t srcOffset,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyAtoH_v2_ptds(dstHost, srcArray, srcOffset, ByteCount)
             : cuMemcpyAtoH_v2(dstHost, srcArray, srcOffset, ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyDtoA_v2_ptds(CUarray dstArray,
                                                 size_t dstOffset,
                                                 CUdeviceptr srcDevice,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyDtoA_v2(CUarray dstArray,
                                                size_t dstOffset,
                                                CUdeviceptr srcDevice,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyDtoA_v2_ptds(dstArray, dstOffset, srcDevice, ByteCount)
             : cuMemcpyDtoA_v2(dstArray, dstOffset, srcDevice, ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyDtoD_v2_ptds(CUdeviceptr dstDevice,
                                                 CUdeviceptr srcDevice,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyDtoD_v2(CUdeviceptr dstDevice,
                                                CUdeviceptr srcDevice,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyDtoD_v2_ptds(dstDevice, srcDevice, ByteCount)
             : cuMemcpyDtoD_v2(dstDevice, srcDevice, ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyDtoH_v2_ptds(void *dstHost,
                                                 CUdeviceptr srcDevice,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyDtoH_v2(void *dstHost,
                                                CUdeviceptr srcDevice,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyDtoH_v2_ptds(dstHost, srcDevice, ByteCount)
             : cuMemcpyDtoH_v2(dstHost, srcDevice, ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyHtoD_v2_ptds(CUdeviceptr dstDevice,
                                                 const void *srcHost,
                                                 size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyHtoD_v2(CUdeviceptr dstDevice,
                                                const void *srcHost,
                                                size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyHtoD_v2_ptds(dstDevice, srcHost, ByteCount)
             : cuMemcpyHtoD_v2(dstDevice, srcHost, ByteCount);
}
extern "C" CUresult CUDAAPI cuMemcpyPeer_ptds(CUdeviceptr dstDevice,
                                              CUcontext dstContext,
                                              CUdeviceptr srcDevice,
                                              CUcontext srcContext,
                                              size_t ByteCount);
inline CUresult lupine_implicit_cuMemcpyPeer(CUdeviceptr dstDevice,
                                             CUcontext dstContext,
                                             CUdeviceptr srcDevice,
                                             CUcontext srcContext,
                                             size_t ByteCount) {
  return lupine_per_thread_default_stream
             ? cuMemcpyPeer_ptds(dstDevice, dstContext, srcDevice, srcContext,
                                 ByteCount)
             : cuMemcpyPeer(dstDevice, dstContext, srcDevice, srcContext,
                            ByteCount);
}
extern "C" CUresult CUDAAPI cuMemsetD16_v2_ptds(CUdeviceptr dstDevice,
                                                unsigned short us, size_t N);
inline CUresult lupine_implicit_cuMemsetD16_v2(CUdeviceptr dstDevice,
                                               unsigned short us, size_t N) {
  return lupine_per_thread_default_stream
             ? cuMemsetD16_v2_ptds(dstDevice, us, N)
             : cuMemsetD16_v2(dstDevice, us, N);
}
extern "C" CUresult CUDAAPI cuMemsetD2D16_v2_ptds(CUdeviceptr dstDevice,
                                                  size_t dstPitch,
                                                  unsigned short us,
                                                  size_t Width, size_t Height);
inline CUresult lupine_implicit_cuMemsetD2D16_v2(CUdeviceptr dstDevice,
                                                 size_t dstPitch,
                                                 unsigned short us,
                                                 size_t Width, size_t Height) {
  return lupine_per_thread_default_stream
             ? cuMemsetD2D16_v2_ptds(dstDevice, dstPitch, us, Width, Height)
             : cuMemsetD2D16_v2(dstDevice, dstPitch, us, Width, Height);
}
extern "C" CUresult CUDAAPI cuMemsetD2D32_v2_ptds(CUdeviceptr dstDevice,
                                                  size_t dstPitch,
                                                  unsigned int ui, size_t Width,
                                                  size_t Height);
inline CUresult lupine_implicit_cuMemsetD2D32_v2(CUdeviceptr dstDevice,
                                                 size_t dstPitch,
                                                 unsigned int ui, size_t Width,
                                                 size_t Height) {
  return lupine_per_thread_default_stream
             ? cuMemsetD2D32_v2_ptds(dstDevice, dstPitch, ui, Width, Height)
             : cuMemsetD2D32_v2(dstDevice, dstPitch, ui, Width, Height);
}
extern "C" CUresult CUDAAPI cuMemsetD2D8_v2_ptds(CUdeviceptr dstDevice,
                                                 size_t dstPitch,
                                                 unsigned char uc, size_t Width,
                                                 size_t Height);
inline CUresult lupine_implicit_cuMemsetD2D8_v2(CUdeviceptr dstDevice,
                                                size_t dstPitch,
                                                unsigned char uc, size_t Width,
                                                size_t Height) {
  return lupine_per_thread_default_stream
             ? cuMemsetD2D8_v2_ptds(dstDevice, dstPitch, uc, Width, Height)
             : cuMemsetD2D8_v2(dstDevice, dstPitch, uc, Width, Height);
}
extern "C" CUresult CUDAAPI cuMemsetD32_v2_ptds(CUdeviceptr dstDevice,
                                                unsigned int ui, size_t N);
inline CUresult lupine_implicit_cuMemsetD32_v2(CUdeviceptr dstDevice,
                                               unsigned int ui, size_t N) {
  return lupine_per_thread_default_stream
             ? cuMemsetD32_v2_ptds(dstDevice, ui, N)
             : cuMemsetD32_v2(dstDevice, ui, N);
}
extern "C" CUresult CUDAAPI cuMemsetD8_v2_ptds(CUdeviceptr dstDevice,
                                               unsigned char uc, size_t N);
inline CUresult lupine_implicit_cuMemsetD8_v2(CUdeviceptr dstDevice,
                                              unsigned char uc, size_t N) {
  return lupine_per_thread_default_stream ? cuMemsetD8_v2_ptds(dstDevice, uc, N)
                                          : cuMemsetD8_v2(dstDevice, uc, N);
}
