// Generated by codegen.py. Do not edit by hand.

int handle_cublasAsumEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasAsumEx_64(conn_t *conn);
#endif

int handle_cublasAxpyEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasAxpyEx_64(conn_t *conn);
#endif

int handle_cublasCaxpy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCaxpy_v2_64(conn_t *conn);
#endif

int handle_cublasCcopy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCcopy_v2_64(conn_t *conn);
#endif

int handle_cublasCdgmm(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCdgmm_64(conn_t *conn);
#endif

int handle_cublasCdotc_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCdotc_v2_64(conn_t *conn);
#endif

int handle_cublasCdotu_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCdotu_v2_64(conn_t *conn);
#endif

int handle_cublasCgbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgbmv_v2_64(conn_t *conn);
#endif

int handle_cublasCgeam(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgeam_64(conn_t *conn);
#endif

int handle_cublasCgelsBatched(conn_t *conn);
int handle_cublasCgemm3m(conn_t *conn);
int handle_cublasCgemm3mBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemm3mBatched_64(conn_t *conn);
#endif

int handle_cublasCgemm3mEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemm3mEx_64(conn_t *conn);
#endif

int handle_cublasCgemm3mStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemm3mStridedBatched_64(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120000
int handle_cublasCgemm3m_64(conn_t *conn);
#endif

int handle_cublasCgemmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemmBatched_64(conn_t *conn);
#endif

int handle_cublasCgemmEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemmEx_64(conn_t *conn);
#endif

int handle_cublasCgemmStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemmStridedBatched_64(conn_t *conn);
#endif

int handle_cublasCgemm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemm_v2_64(conn_t *conn);
#endif

int handle_cublasCgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemvBatched_64(conn_t *conn);
#endif

int handle_cublasCgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasCgemv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgemv_v2_64(conn_t *conn);
#endif

int handle_cublasCgeqrfBatched(conn_t *conn);
int handle_cublasCgerc_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgerc_v2_64(conn_t *conn);
#endif

int handle_cublasCgeru_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCgeru_v2_64(conn_t *conn);
#endif

int handle_cublasCgetrfBatched(conn_t *conn);
int handle_cublasCgetriBatched(conn_t *conn);
int handle_cublasCgetrsBatched(conn_t *conn);
int handle_cublasChbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasChbmv_v2_64(conn_t *conn);
#endif

int handle_cublasChemm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasChemm_v2_64(conn_t *conn);
#endif

int handle_cublasChemv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasChemv_v2_64(conn_t *conn);
#endif

int handle_cublasCher2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCher2_v2_64(conn_t *conn);
#endif

int handle_cublasCher2k_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCher2k_v2_64(conn_t *conn);
#endif

int handle_cublasCher_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCher_v2_64(conn_t *conn);
#endif

int handle_cublasCherk3mEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCherk3mEx_64(conn_t *conn);
#endif

int handle_cublasCherkEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCherkEx_64(conn_t *conn);
#endif

int handle_cublasCherk_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCherk_v2_64(conn_t *conn);
#endif

int handle_cublasCherkx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCherkx_64(conn_t *conn);
#endif

int handle_cublasChpmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasChpmv_v2_64(conn_t *conn);
#endif

int handle_cublasChpr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasChpr2_v2_64(conn_t *conn);
#endif

int handle_cublasChpr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasChpr_v2_64(conn_t *conn);
#endif

int handle_cublasCmatinvBatched(conn_t *conn);
int handle_cublasCopyEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCopyEx_64(conn_t *conn);
#endif

int handle_cublasCreate_v2(conn_t *conn);
int handle_cublasCrot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCrot_v2_64(conn_t *conn);
#endif

int handle_cublasCrotg_v2(conn_t *conn);
int handle_cublasCscal_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCscal_v2_64(conn_t *conn);
#endif

int handle_cublasCsrot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsrot_v2_64(conn_t *conn);
#endif

int handle_cublasCsscal_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsscal_v2_64(conn_t *conn);
#endif

int handle_cublasCswap_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCswap_v2_64(conn_t *conn);
#endif

int handle_cublasCsymm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsymm_v2_64(conn_t *conn);
#endif

int handle_cublasCsymv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsymv_v2_64(conn_t *conn);
#endif

int handle_cublasCsyr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyr2_v2_64(conn_t *conn);
#endif

int handle_cublasCsyr2k_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyr2k_v2_64(conn_t *conn);
#endif

int handle_cublasCsyr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyr_v2_64(conn_t *conn);
#endif

int handle_cublasCsyrk3mEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyrk3mEx_64(conn_t *conn);
#endif

int handle_cublasCsyrkEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyrkEx_64(conn_t *conn);
#endif

int handle_cublasCsyrk_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyrk_v2_64(conn_t *conn);
#endif

int handle_cublasCsyrkx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCsyrkx_64(conn_t *conn);
#endif

int handle_cublasCtbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtbmv_v2_64(conn_t *conn);
#endif

int handle_cublasCtbsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtbsv_v2_64(conn_t *conn);
#endif

int handle_cublasCtpmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtpmv_v2_64(conn_t *conn);
#endif

int handle_cublasCtpsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtpsv_v2_64(conn_t *conn);
#endif

int handle_cublasCtpttr(conn_t *conn);
int handle_cublasCtrmm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtrmm_v2_64(conn_t *conn);
#endif

int handle_cublasCtrmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtrmv_v2_64(conn_t *conn);
#endif

int handle_cublasCtrsmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtrsmBatched_64(conn_t *conn);
#endif

int handle_cublasCtrsm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtrsm_v2_64(conn_t *conn);
#endif

int handle_cublasCtrsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasCtrsv_v2_64(conn_t *conn);
#endif

int handle_cublasCtrttp(conn_t *conn);
int handle_cublasDasum_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDasum_v2_64(conn_t *conn);
#endif

int handle_cublasDaxpy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDaxpy_v2_64(conn_t *conn);
#endif

int handle_cublasDcopy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDcopy_v2_64(conn_t *conn);
#endif

int handle_cublasDdgmm(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDdgmm_64(conn_t *conn);
#endif

int handle_cublasDdot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDdot_v2_64(conn_t *conn);
#endif

int handle_cublasDestroy_v2(conn_t *conn);
int handle_cublasDgbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgbmv_v2_64(conn_t *conn);
#endif

int handle_cublasDgeam(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgeam_64(conn_t *conn);
#endif

int handle_cublasDgelsBatched(conn_t *conn);
int handle_cublasDgemmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgemmBatched_64(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120500
int handle_cublasDgemmGroupedBatched(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120500
int handle_cublasDgemmGroupedBatched_64(conn_t *conn);
#endif

int handle_cublasDgemmStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgemmStridedBatched_64(conn_t *conn);
#endif

int handle_cublasDgemm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgemm_v2_64(conn_t *conn);
#endif

int handle_cublasDgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgemvBatched_64(conn_t *conn);
#endif

int handle_cublasDgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasDgemv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDgemv_v2_64(conn_t *conn);
#endif

int handle_cublasDgeqrfBatched(conn_t *conn);
int handle_cublasDger_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDger_v2_64(conn_t *conn);
#endif

int handle_cublasDgetrfBatched(conn_t *conn);
int handle_cublasDgetriBatched(conn_t *conn);
int handle_cublasDgetrsBatched(conn_t *conn);
int handle_cublasDmatinvBatched(conn_t *conn);
int handle_cublasDnrm2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDnrm2_v2_64(conn_t *conn);
#endif

int handle_cublasDotEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDotEx_64(conn_t *conn);
#endif

int handle_cublasDotcEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDotcEx_64(conn_t *conn);
#endif

int handle_cublasDrot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDrot_v2_64(conn_t *conn);
#endif

int handle_cublasDrotg_v2(conn_t *conn);
int handle_cublasDrotm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDrotm_v2_64(conn_t *conn);
#endif

int handle_cublasDrotmg_v2(conn_t *conn);
int handle_cublasDsbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsbmv_v2_64(conn_t *conn);
#endif

int handle_cublasDscal_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDscal_v2_64(conn_t *conn);
#endif

int handle_cublasDspmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDspmv_v2_64(conn_t *conn);
#endif

int handle_cublasDspr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDspr2_v2_64(conn_t *conn);
#endif

int handle_cublasDspr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDspr_v2_64(conn_t *conn);
#endif

int handle_cublasDswap_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDswap_v2_64(conn_t *conn);
#endif

int handle_cublasDsymm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsymm_v2_64(conn_t *conn);
#endif

int handle_cublasDsymv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsymv_v2_64(conn_t *conn);
#endif

int handle_cublasDsyr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsyr2_v2_64(conn_t *conn);
#endif

int handle_cublasDsyr2k_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsyr2k_v2_64(conn_t *conn);
#endif

int handle_cublasDsyr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsyr_v2_64(conn_t *conn);
#endif

int handle_cublasDsyrk_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsyrk_v2_64(conn_t *conn);
#endif

int handle_cublasDsyrkx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDsyrkx_64(conn_t *conn);
#endif

int handle_cublasDtbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtbmv_v2_64(conn_t *conn);
#endif

int handle_cublasDtbsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtbsv_v2_64(conn_t *conn);
#endif

int handle_cublasDtpmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtpmv_v2_64(conn_t *conn);
#endif

int handle_cublasDtpsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtpsv_v2_64(conn_t *conn);
#endif

int handle_cublasDtpttr(conn_t *conn);
int handle_cublasDtrmm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtrmm_v2_64(conn_t *conn);
#endif

int handle_cublasDtrmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtrmv_v2_64(conn_t *conn);
#endif

int handle_cublasDtrsmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtrsmBatched_64(conn_t *conn);
#endif

int handle_cublasDtrsm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtrsm_v2_64(conn_t *conn);
#endif

int handle_cublasDtrsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDtrsv_v2_64(conn_t *conn);
#endif

int handle_cublasDtrttp(conn_t *conn);
int handle_cublasDzasum_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDzasum_v2_64(conn_t *conn);
#endif

int handle_cublasDznrm2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasDznrm2_v2_64(conn_t *conn);
#endif

int handle_cublasGemmBatchedEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasGemmBatchedEx_64(conn_t *conn);
#endif

int handle_cublasGemmEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasGemmEx_64(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120500
int handle_cublasGemmGroupedBatchedEx(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120500
int handle_cublasGemmGroupedBatchedEx_64(conn_t *conn);
#endif

int handle_cublasGemmStridedBatchedEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasGemmStridedBatchedEx_64(conn_t *conn);
#endif

int handle_cublasGetAtomicsMode(conn_t *conn);
int handle_cublasGetCudartVersion(conn_t *conn);
#if CUBLAS_VERSION >= 130100
int handle_cublasGetEmulationSpecialValuesSupport(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120900
int handle_cublasGetEmulationStrategy(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasGetFixedPointEmulationMantissaBitCountPointer(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasGetFixedPointEmulationMantissaBitOffset(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasGetFixedPointEmulationMantissaControl(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasGetFixedPointEmulationMaxMantissaBitCount(conn_t *conn);
#endif

int handle_cublasGetMathMode(conn_t *conn);
int handle_cublasGetPointerMode_v2(conn_t *conn);
int handle_cublasGetProperty(conn_t *conn);
int handle_cublasGetSmCountTarget(conn_t *conn);
int handle_cublasGetStream_v2(conn_t *conn);
int handle_cublasGetVersion_v2(conn_t *conn);
int handle_cublasHSHgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasHSHgemvBatched_64(conn_t *conn);
#endif

int handle_cublasHSHgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasHSHgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasHSSgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasHSSgemvBatched_64(conn_t *conn);
#endif

int handle_cublasHSSgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasHSSgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasHgemm(conn_t *conn);
int handle_cublasHgemmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasHgemmBatched_64(conn_t *conn);
#endif

int handle_cublasHgemmStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasHgemmStridedBatched_64(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120000
int handle_cublasHgemm_64(conn_t *conn);
#endif

int handle_cublasIamaxEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIamaxEx_64(conn_t *conn);
#endif

int handle_cublasIaminEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIaminEx_64(conn_t *conn);
#endif

int handle_cublasIcamax_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIcamax_v2_64(conn_t *conn);
#endif

int handle_cublasIcamin_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIcamin_v2_64(conn_t *conn);
#endif

int handle_cublasIdamax_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIdamax_v2_64(conn_t *conn);
#endif

int handle_cublasIdamin_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIdamin_v2_64(conn_t *conn);
#endif

int handle_cublasIsamax_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIsamax_v2_64(conn_t *conn);
#endif

int handle_cublasIsamin_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIsamin_v2_64(conn_t *conn);
#endif

int handle_cublasIzamax_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIzamax_v2_64(conn_t *conn);
#endif

int handle_cublasIzamin_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasIzamin_v2_64(conn_t *conn);
#endif

int handle_cublasNrm2Ex(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasNrm2Ex_64(conn_t *conn);
#endif

int handle_cublasRotEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasRotEx_64(conn_t *conn);
#endif

int handle_cublasRotgEx(conn_t *conn);
int handle_cublasRotmEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasRotmEx_64(conn_t *conn);
#endif

int handle_cublasRotmgEx(conn_t *conn);
int handle_cublasSasum_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSasum_v2_64(conn_t *conn);
#endif

int handle_cublasSaxpy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSaxpy_v2_64(conn_t *conn);
#endif

int handle_cublasScalEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasScalEx_64(conn_t *conn);
#endif

int handle_cublasScasum_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasScasum_v2_64(conn_t *conn);
#endif

int handle_cublasScnrm2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasScnrm2_v2_64(conn_t *conn);
#endif

int handle_cublasScopy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasScopy_v2_64(conn_t *conn);
#endif

int handle_cublasSdgmm(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSdgmm_64(conn_t *conn);
#endif

int handle_cublasSdot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSdot_v2_64(conn_t *conn);
#endif

int handle_cublasSetAtomicsMode(conn_t *conn);
#if CUBLAS_VERSION >= 130100
int handle_cublasSetEmulationSpecialValuesSupport(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120900
int handle_cublasSetEmulationStrategy(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasSetFixedPointEmulationMantissaBitCountPointer(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasSetFixedPointEmulationMantissaBitOffset(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasSetFixedPointEmulationMantissaControl(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 130100
int handle_cublasSetFixedPointEmulationMaxMantissaBitCount(conn_t *conn);
#endif

int handle_cublasSetMathMode(conn_t *conn);
int handle_cublasSetPointerMode_v2(conn_t *conn);
int handle_cublasSetSmCountTarget(conn_t *conn);
int handle_cublasSetStream_v2(conn_t *conn);
int handle_cublasSetWorkspace_v2(conn_t *conn);
int handle_cublasSgbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgbmv_v2_64(conn_t *conn);
#endif

int handle_cublasSgeam(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgeam_64(conn_t *conn);
#endif

int handle_cublasSgelsBatched(conn_t *conn);
int handle_cublasSgemmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemmBatched_64(conn_t *conn);
#endif

int handle_cublasSgemmEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemmEx_64(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120500
int handle_cublasSgemmGroupedBatched(conn_t *conn);
#endif

#if CUBLAS_VERSION >= 120500
int handle_cublasSgemmGroupedBatched_64(conn_t *conn);
#endif

int handle_cublasSgemmStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemmStridedBatched_64(conn_t *conn);
#endif

int handle_cublasSgemm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemm_v2_64(conn_t *conn);
#endif

int handle_cublasSgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemvBatched_64(conn_t *conn);
#endif

int handle_cublasSgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasSgemv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSgemv_v2_64(conn_t *conn);
#endif

int handle_cublasSgeqrfBatched(conn_t *conn);
int handle_cublasSger_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSger_v2_64(conn_t *conn);
#endif

int handle_cublasSgetrfBatched(conn_t *conn);
int handle_cublasSgetriBatched(conn_t *conn);
int handle_cublasSgetrsBatched(conn_t *conn);
int handle_cublasSmatinvBatched(conn_t *conn);
int handle_cublasSnrm2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSnrm2_v2_64(conn_t *conn);
#endif

int handle_cublasSrot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSrot_v2_64(conn_t *conn);
#endif

int handle_cublasSrotg_v2(conn_t *conn);
int handle_cublasSrotm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSrotm_v2_64(conn_t *conn);
#endif

int handle_cublasSrotmg_v2(conn_t *conn);
int handle_cublasSsbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsbmv_v2_64(conn_t *conn);
#endif

int handle_cublasSscal_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSscal_v2_64(conn_t *conn);
#endif

int handle_cublasSspmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSspmv_v2_64(conn_t *conn);
#endif

int handle_cublasSspr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSspr2_v2_64(conn_t *conn);
#endif

int handle_cublasSspr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSspr_v2_64(conn_t *conn);
#endif

int handle_cublasSswap_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSswap_v2_64(conn_t *conn);
#endif

int handle_cublasSsymm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsymm_v2_64(conn_t *conn);
#endif

int handle_cublasSsymv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsymv_v2_64(conn_t *conn);
#endif

int handle_cublasSsyr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsyr2_v2_64(conn_t *conn);
#endif

int handle_cublasSsyr2k_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsyr2k_v2_64(conn_t *conn);
#endif

int handle_cublasSsyr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsyr_v2_64(conn_t *conn);
#endif

int handle_cublasSsyrk_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsyrk_v2_64(conn_t *conn);
#endif

int handle_cublasSsyrkx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSsyrkx_64(conn_t *conn);
#endif

int handle_cublasStbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStbmv_v2_64(conn_t *conn);
#endif

int handle_cublasStbsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStbsv_v2_64(conn_t *conn);
#endif

int handle_cublasStpmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStpmv_v2_64(conn_t *conn);
#endif

int handle_cublasStpsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStpsv_v2_64(conn_t *conn);
#endif

int handle_cublasStpttr(conn_t *conn);
int handle_cublasStrmm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStrmm_v2_64(conn_t *conn);
#endif

int handle_cublasStrmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStrmv_v2_64(conn_t *conn);
#endif

int handle_cublasStrsmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStrsmBatched_64(conn_t *conn);
#endif

int handle_cublasStrsm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStrsm_v2_64(conn_t *conn);
#endif

int handle_cublasStrsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasStrsv_v2_64(conn_t *conn);
#endif

int handle_cublasStrttp(conn_t *conn);
int handle_cublasSwapEx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasSwapEx_64(conn_t *conn);
#endif

int handle_cublasTSSgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasTSSgemvBatched_64(conn_t *conn);
#endif

int handle_cublasTSSgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasTSSgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasTSTgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasTSTgemvBatched_64(conn_t *conn);
#endif

int handle_cublasTSTgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasTSTgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasUint8gemmBias(conn_t *conn);
int handle_cublasZaxpy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZaxpy_v2_64(conn_t *conn);
#endif

int handle_cublasZcopy_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZcopy_v2_64(conn_t *conn);
#endif

int handle_cublasZdgmm(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZdgmm_64(conn_t *conn);
#endif

int handle_cublasZdotc_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZdotc_v2_64(conn_t *conn);
#endif

int handle_cublasZdotu_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZdotu_v2_64(conn_t *conn);
#endif

int handle_cublasZdrot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZdrot_v2_64(conn_t *conn);
#endif

int handle_cublasZdscal_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZdscal_v2_64(conn_t *conn);
#endif

int handle_cublasZgbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgbmv_v2_64(conn_t *conn);
#endif

int handle_cublasZgeam(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgeam_64(conn_t *conn);
#endif

int handle_cublasZgelsBatched(conn_t *conn);
int handle_cublasZgemm3m(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemm3m_64(conn_t *conn);
#endif

int handle_cublasZgemmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemmBatched_64(conn_t *conn);
#endif

int handle_cublasZgemmStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemmStridedBatched_64(conn_t *conn);
#endif

int handle_cublasZgemm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemm_v2_64(conn_t *conn);
#endif

int handle_cublasZgemvBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemvBatched_64(conn_t *conn);
#endif

int handle_cublasZgemvStridedBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemvStridedBatched_64(conn_t *conn);
#endif

int handle_cublasZgemv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgemv_v2_64(conn_t *conn);
#endif

int handle_cublasZgeqrfBatched(conn_t *conn);
int handle_cublasZgerc_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgerc_v2_64(conn_t *conn);
#endif

int handle_cublasZgeru_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZgeru_v2_64(conn_t *conn);
#endif

int handle_cublasZgetrfBatched(conn_t *conn);
int handle_cublasZgetriBatched(conn_t *conn);
int handle_cublasZgetrsBatched(conn_t *conn);
int handle_cublasZhbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZhbmv_v2_64(conn_t *conn);
#endif

int handle_cublasZhemm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZhemm_v2_64(conn_t *conn);
#endif

int handle_cublasZhemv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZhemv_v2_64(conn_t *conn);
#endif

int handle_cublasZher2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZher2_v2_64(conn_t *conn);
#endif

int handle_cublasZher2k_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZher2k_v2_64(conn_t *conn);
#endif

int handle_cublasZher_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZher_v2_64(conn_t *conn);
#endif

int handle_cublasZherk_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZherk_v2_64(conn_t *conn);
#endif

int handle_cublasZherkx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZherkx_64(conn_t *conn);
#endif

int handle_cublasZhpmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZhpmv_v2_64(conn_t *conn);
#endif

int handle_cublasZhpr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZhpr2_v2_64(conn_t *conn);
#endif

int handle_cublasZhpr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZhpr_v2_64(conn_t *conn);
#endif

int handle_cublasZmatinvBatched(conn_t *conn);
int handle_cublasZrot_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZrot_v2_64(conn_t *conn);
#endif

int handle_cublasZrotg_v2(conn_t *conn);
int handle_cublasZscal_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZscal_v2_64(conn_t *conn);
#endif

int handle_cublasZswap_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZswap_v2_64(conn_t *conn);
#endif

int handle_cublasZsymm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsymm_v2_64(conn_t *conn);
#endif

int handle_cublasZsymv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsymv_v2_64(conn_t *conn);
#endif

int handle_cublasZsyr2_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsyr2_v2_64(conn_t *conn);
#endif

int handle_cublasZsyr2k_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsyr2k_v2_64(conn_t *conn);
#endif

int handle_cublasZsyr_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsyr_v2_64(conn_t *conn);
#endif

int handle_cublasZsyrk_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsyrk_v2_64(conn_t *conn);
#endif

int handle_cublasZsyrkx(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZsyrkx_64(conn_t *conn);
#endif

int handle_cublasZtbmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtbmv_v2_64(conn_t *conn);
#endif

int handle_cublasZtbsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtbsv_v2_64(conn_t *conn);
#endif

int handle_cublasZtpmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtpmv_v2_64(conn_t *conn);
#endif

int handle_cublasZtpsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtpsv_v2_64(conn_t *conn);
#endif

int handle_cublasZtpttr(conn_t *conn);
int handle_cublasZtrmm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtrmm_v2_64(conn_t *conn);
#endif

int handle_cublasZtrmv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtrmv_v2_64(conn_t *conn);
#endif

int handle_cublasZtrsmBatched(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtrsmBatched_64(conn_t *conn);
#endif

int handle_cublasZtrsm_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtrsm_v2_64(conn_t *conn);
#endif

int handle_cublasZtrsv_v2(conn_t *conn);
#if CUBLAS_VERSION >= 120000
int handle_cublasZtrsv_v2_64(conn_t *conn);
#endif

int handle_cublasZtrttp(conn_t *conn);
