// Generated by codegen.py. Do not edit by hand.

int handle_nppiGetResizeRect(conn_t *conn);
int handle_nppiResizeSqrPixel_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_C1R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_C3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_C4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_AC4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_P3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_P4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16u_C1R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16u_C3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16u_C4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16u_AC4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16u_P3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16u_P4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16s_C1R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16s_C3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16s_C4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16s_AC4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16s_P3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_16s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_16s_P4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_32f_C1R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_32f_C3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_32f_C4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_32f_AC4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_32f_P3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_32f_P4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_64f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_64f_C1R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_64f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_64f_C3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_64f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_64f_C4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_64f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_64f_AC4R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_64f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_64f_P3R(conn_t *conn);
#endif
int handle_nppiResizeSqrPixel_64f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_64f_P4R(conn_t *conn);
#endif
int handle_nppiResizeAdvancedGetBufferHostSize_8u_C1R(conn_t *conn);
int handle_nppiResizeSqrPixel_8u_C1R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeSqrPixel_8u_C1R_Advanced(conn_t *conn);
#endif
int handle_nppiGetResizeTiledSourceOffset(conn_t *conn);
int handle_nppiResize_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_8u_C1R(conn_t *conn);
#endif
int handle_nppiResize_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_8u_C3R(conn_t *conn);
#endif
int handle_nppiResize_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_8u_C4R(conn_t *conn);
#endif
int handle_nppiResize_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_8u_AC4R(conn_t *conn);
#endif
int handle_nppiResize_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_8u_P3R(conn_t *conn);
#endif
int handle_nppiResize_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_8u_P4R(conn_t *conn);
#endif
int handle_nppiResize_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16u_C1R(conn_t *conn);
#endif
int handle_nppiResize_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16u_C3R(conn_t *conn);
#endif
int handle_nppiResize_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16u_C4R(conn_t *conn);
#endif
int handle_nppiResize_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16u_AC4R(conn_t *conn);
#endif
int handle_nppiResize_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16u_P3R(conn_t *conn);
#endif
int handle_nppiResize_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16u_P4R(conn_t *conn);
#endif
int handle_nppiResize_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16s_C1R(conn_t *conn);
#endif
int handle_nppiResize_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16s_C3R(conn_t *conn);
#endif
int handle_nppiResize_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16s_C4R(conn_t *conn);
#endif
int handle_nppiResize_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16s_AC4R(conn_t *conn);
#endif
int handle_nppiResize_16s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16s_P3R(conn_t *conn);
#endif
int handle_nppiResize_16s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16s_P4R(conn_t *conn);
#endif
int handle_nppiResize_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16f_C1R(conn_t *conn);
#endif
int handle_nppiResize_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16f_C3R(conn_t *conn);
#endif
int handle_nppiResize_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_16f_C4R(conn_t *conn);
#endif
int handle_nppiResize_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_32f_C1R(conn_t *conn);
#endif
int handle_nppiResize_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_32f_C3R(conn_t *conn);
#endif
int handle_nppiResize_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_32f_C4R(conn_t *conn);
#endif
int handle_nppiResize_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_32f_AC4R(conn_t *conn);
#endif
int handle_nppiResize_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_32f_P3R(conn_t *conn);
#endif
int handle_nppiResize_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResize_32f_P4R(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_C1R(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_C4R(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_AC4R(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_C1R(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_C3R(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_C4R(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_AC4R(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_C1R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_C1R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_C4R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_C4R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_8u_AC4R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_8u_AC4R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_16f_C1R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_16f_C1R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_16f_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_16f_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_16f_C4R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_16f_C4R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_C1R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_C1R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_C3R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_C3R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_C4R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_C4R_Advanced(conn_t *conn);
#endif
int handle_nppiResizeBatch_32f_AC4R_Advanced_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiResizeBatch_32f_AC4R_Advanced(conn_t *conn);
#endif
int handle_nppiRemap_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_8u_C1R(conn_t *conn);
#endif
int handle_nppiRemap_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_8u_C3R(conn_t *conn);
#endif
int handle_nppiRemap_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_8u_C4R(conn_t *conn);
#endif
int handle_nppiRemap_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_8u_AC4R(conn_t *conn);
#endif
int handle_nppiRemap_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_8u_P3R(conn_t *conn);
#endif
int handle_nppiRemap_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_8u_P4R(conn_t *conn);
#endif
int handle_nppiRemap_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16u_C1R(conn_t *conn);
#endif
int handle_nppiRemap_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16u_C3R(conn_t *conn);
#endif
int handle_nppiRemap_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16u_C4R(conn_t *conn);
#endif
int handle_nppiRemap_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16u_AC4R(conn_t *conn);
#endif
int handle_nppiRemap_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16u_P3R(conn_t *conn);
#endif
int handle_nppiRemap_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16u_P4R(conn_t *conn);
#endif
int handle_nppiRemap_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16s_C1R(conn_t *conn);
#endif
int handle_nppiRemap_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16s_C3R(conn_t *conn);
#endif
int handle_nppiRemap_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16s_C4R(conn_t *conn);
#endif
int handle_nppiRemap_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16s_AC4R(conn_t *conn);
#endif
int handle_nppiRemap_16s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16s_P3R(conn_t *conn);
#endif
int handle_nppiRemap_16s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_16s_P4R(conn_t *conn);
#endif
int handle_nppiRemap_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_32f_C1R(conn_t *conn);
#endif
int handle_nppiRemap_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_32f_C3R(conn_t *conn);
#endif
int handle_nppiRemap_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_32f_C4R(conn_t *conn);
#endif
int handle_nppiRemap_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_32f_AC4R(conn_t *conn);
#endif
int handle_nppiRemap_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_32f_P3R(conn_t *conn);
#endif
int handle_nppiRemap_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_32f_P4R(conn_t *conn);
#endif
int handle_nppiRemap_64f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_64f_C1R(conn_t *conn);
#endif
int handle_nppiRemap_64f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_64f_C3R(conn_t *conn);
#endif
int handle_nppiRemap_64f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_64f_C4R(conn_t *conn);
#endif
int handle_nppiRemap_64f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_64f_AC4R(conn_t *conn);
#endif
int handle_nppiRemap_64f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_64f_P3R(conn_t *conn);
#endif
int handle_nppiRemap_64f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRemap_64f_P4R(conn_t *conn);
#endif
int handle_nppiGetRotateQuad(conn_t *conn);
int handle_nppiGetRotateBound(conn_t *conn);
int handle_nppiRotate_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_8u_C1R(conn_t *conn);
#endif
int handle_nppiRotate_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_8u_C3R(conn_t *conn);
#endif
int handle_nppiRotate_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_8u_C4R(conn_t *conn);
#endif
int handle_nppiRotate_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_8u_AC4R(conn_t *conn);
#endif
int handle_nppiRotate_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_16u_C1R(conn_t *conn);
#endif
int handle_nppiRotate_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_16u_C3R(conn_t *conn);
#endif
int handle_nppiRotate_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_16u_C4R(conn_t *conn);
#endif
int handle_nppiRotate_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_16u_AC4R(conn_t *conn);
#endif
int handle_nppiRotate_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_32f_C1R(conn_t *conn);
#endif
int handle_nppiRotate_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_32f_C3R(conn_t *conn);
#endif
int handle_nppiRotate_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_32f_C4R(conn_t *conn);
#endif
int handle_nppiRotate_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiRotate_32f_AC4R(conn_t *conn);
#endif
int handle_nppiMirror_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_C1R(conn_t *conn);
#endif
int handle_nppiMirror_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_C1IR(conn_t *conn);
#endif
int handle_nppiMirror_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_C3R(conn_t *conn);
#endif
int handle_nppiMirror_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_C3IR(conn_t *conn);
#endif
int handle_nppiMirror_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_C4R(conn_t *conn);
#endif
int handle_nppiMirror_8u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_C4IR(conn_t *conn);
#endif
int handle_nppiMirror_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_AC4R(conn_t *conn);
#endif
int handle_nppiMirror_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiMirror_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_C1R(conn_t *conn);
#endif
int handle_nppiMirror_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_C1IR(conn_t *conn);
#endif
int handle_nppiMirror_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_C3R(conn_t *conn);
#endif
int handle_nppiMirror_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_C3IR(conn_t *conn);
#endif
int handle_nppiMirror_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_C4R(conn_t *conn);
#endif
int handle_nppiMirror_16u_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_C4IR(conn_t *conn);
#endif
int handle_nppiMirror_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_AC4R(conn_t *conn);
#endif
int handle_nppiMirror_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiMirror_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_C1R(conn_t *conn);
#endif
int handle_nppiMirror_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_C1IR(conn_t *conn);
#endif
int handle_nppiMirror_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_C3R(conn_t *conn);
#endif
int handle_nppiMirror_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_C3IR(conn_t *conn);
#endif
int handle_nppiMirror_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_C4R(conn_t *conn);
#endif
int handle_nppiMirror_16s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_C4IR(conn_t *conn);
#endif
int handle_nppiMirror_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_AC4R(conn_t *conn);
#endif
int handle_nppiMirror_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiMirror_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_C1R(conn_t *conn);
#endif
int handle_nppiMirror_32s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_C1IR(conn_t *conn);
#endif
int handle_nppiMirror_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_C3R(conn_t *conn);
#endif
int handle_nppiMirror_32s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_C3IR(conn_t *conn);
#endif
int handle_nppiMirror_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_C4R(conn_t *conn);
#endif
int handle_nppiMirror_32s_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_C4IR(conn_t *conn);
#endif
int handle_nppiMirror_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_AC4R(conn_t *conn);
#endif
int handle_nppiMirror_32s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32s_AC4IR(conn_t *conn);
#endif
int handle_nppiMirror_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_C1R(conn_t *conn);
#endif
int handle_nppiMirror_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_C1IR(conn_t *conn);
#endif
int handle_nppiMirror_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_C3R(conn_t *conn);
#endif
int handle_nppiMirror_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_C3IR(conn_t *conn);
#endif
int handle_nppiMirror_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_C4R(conn_t *conn);
#endif
int handle_nppiMirror_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_C4IR(conn_t *conn);
#endif
int handle_nppiMirror_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_AC4R(conn_t *conn);
#endif
int handle_nppiMirror_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirror_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_C1R(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_C1IR(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_C3R(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_C3IR(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_C4R(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_C4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_C4IR(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_AC4R(conn_t *conn);
#endif
int handle_nppiMirrorBatch_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiMirrorBatch_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiGetAffineTransform(conn_t *conn);
int handle_nppiGetAffineQuad(conn_t *conn);
int handle_nppiGetAffineBound(conn_t *conn);
int handle_nppiWarpAffine_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffine_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_8u_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_8u_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16u_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16u_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32s_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32s_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32s_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32s_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32s_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32s_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_16f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32f_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_32f_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_64f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_64f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffine_64f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_64f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_64f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_64f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_64f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_64f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffine_64f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_64f_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffine_64f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffine_64f_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatchInit_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatchInit(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_16f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_16f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_16f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBatch_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBatch_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_8u_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_8u_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_16u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_16u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_16u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_16u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_16u_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_16u_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32s_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32s_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32s_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32s_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32s_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32s_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32f_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineBack_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineBack_32f_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_8u_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_8u_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_16u_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_16u_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_16u_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_16u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_16u_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_16u_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32s_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32s_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32s_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32s_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32s_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32s_P4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32f_P3R(conn_t *conn);
#endif
int handle_nppiWarpAffineQuad_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpAffineQuad_32f_P4R(conn_t *conn);
#endif
int handle_nppiGetPerspectiveTransform(conn_t *conn);
int handle_nppiGetPerspectiveQuad(conn_t *conn);
int handle_nppiGetPerspectiveBound(conn_t *conn);
int handle_nppiWarpPerspective_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_8u_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_8u_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16u_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16u_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32s_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32s_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32s_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32s_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32s_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32s_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16f_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16f_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_16f_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32f_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspective_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspective_32f_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatchInit_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatchInit(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_16f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_16f_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_16f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_16f_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_16f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_16f_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBatch_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBatch_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_8u_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_8u_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_16u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_16u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_16u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_16u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_16u_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_16u_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32s_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32s_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32s_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32s_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32s_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32s_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32f_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveBack_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveBack_32f_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_8u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_8u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_8u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_8u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_8u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_8u_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_8u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_8u_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_16u_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_16u_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_16u_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_16u_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_16u_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_16u_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_16u_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_16u_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32s_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32s_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32s_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32s_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32s_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32s_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32s_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32s_P4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32f_C1R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32f_C3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32f_C4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32f_AC4R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32f_P3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32f_P3R(conn_t *conn);
#endif
int handle_nppiWarpPerspectiveQuad_32f_P4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiWarpPerspectiveQuad_32f_P4R(conn_t *conn);
#endif
