// Generated by codegen.py. Do not edit by hand.

int handle_cusolverMgCreate(conn_t *conn);
int handle_cusolverMgDestroy(conn_t *conn);
int handle_cusolverMgDeviceSelect(conn_t *conn);
int handle_cusolverMgCreateDeviceGrid(conn_t *conn);
int handle_cusolverMgDestroyGrid(conn_t *conn);
int handle_cusolverMgCreateMatrixDesc(conn_t *conn);
int handle_cusolverMgDestroyMatrixDesc(conn_t *conn);
int handle_cusolverMgSyevd_bufferSize(conn_t *conn);
int handle_cusolverMgSyevd(conn_t *conn);
int handle_cusolverMgGetrf_bufferSize(conn_t *conn);
int handle_cusolverMgGetrf(conn_t *conn);
int handle_cusolverMgGetrs_bufferSize(conn_t *conn);
int handle_cusolverMgGetrs(conn_t *conn);
int handle_cusolverMgPotrf_bufferSize(conn_t *conn);
int handle_cusolverMgPotrf(conn_t *conn);
int handle_cusolverMgPotrs_bufferSize(conn_t *conn);
int handle_cusolverMgPotrs(conn_t *conn);
int handle_cusolverMgPotri_bufferSize(conn_t *conn);
int handle_cusolverMgPotri(conn_t *conn);
