// Generated by codegen.py. Do not edit by hand.

#if NCCL_VERSION_CODE >= 21903
int handle_ncclMemAlloc(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 21903
int handle_ncclMemFree(conn_t *conn);
#endif
int handle_ncclGetVersion(conn_t *conn);
int handle_ncclGetUniqueId(conn_t *conn);
int handle_ncclCommInitRankConfig(conn_t *conn);
int handle_ncclCommInitRank(conn_t *conn);
int handle_ncclCommInitAll(conn_t *conn);
int handle_ncclCommFinalize(conn_t *conn);
int handle_ncclCommDestroy(conn_t *conn);
int handle_ncclCommAbort(conn_t *conn);
#if NCCL_VERSION_CODE >= 22807
int handle_ncclCommRevoke(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 21801
int handle_ncclCommSplit(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22703
int handle_ncclCommShrink(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22902
int handle_ncclCommGetUniqueId(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22902
int handle_ncclCommGrow(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22304
int handle_ncclCommInitRankScalable(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22403
int handle_ncclResetDebugInit(conn_t *conn);
#endif
int handle_ncclCommGetAsyncError(conn_t *conn);
int handle_ncclCommCount(conn_t *conn);
int handle_ncclCommCuDevice(conn_t *conn);
int handle_ncclCommUserRank(conn_t *conn);
#if NCCL_VERSION_CODE >= 21903
int handle_ncclCommRegister(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 21903
int handle_ncclCommDeregister(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22907
int handle_ncclCommSuspend(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22907
int handle_ncclCommResume(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22907
int handle_ncclCommMemStats(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22703
int handle_ncclCommWindowRegister(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22703
int handle_ncclCommWindowDeregister(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22902
int handle_ncclWinGetUserPtr(conn_t *conn);
#endif
int handle_ncclRedOpCreatePreMulSum(conn_t *conn);
int handle_ncclRedOpDestroy(conn_t *conn);
int handle_ncclReduce(conn_t *conn);
int handle_ncclBcast(conn_t *conn);
int handle_ncclBroadcast(conn_t *conn);
int handle_ncclAllReduce(conn_t *conn);
int handle_ncclReduceScatter(conn_t *conn);
int handle_ncclAllGather(conn_t *conn);
#if NCCL_VERSION_CODE >= 22803
int handle_ncclAlltoAll(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22803
int handle_ncclGather(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22803
int handle_ncclScatter(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclAllReduceConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclBroadcastConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclReduceConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclAllGatherConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclReduceScatterConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclAlltoAllConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclGatherConfig(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23102
int handle_ncclScatterConfig(conn_t *conn);
#endif
int handle_ncclSend(conn_t *conn);
int handle_ncclRecv(conn_t *conn);
#if NCCL_VERSION_CODE >= 22902
int handle_ncclPutSignal(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22902
int handle_ncclSignal(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 22902
int handle_ncclWaitSignal(conn_t *conn);
#endif
int handle_ncclGroupStart(conn_t *conn);
int handle_ncclGroupEnd(conn_t *conn);
#if NCCL_VERSION_CODE >= 22203
int handle_ncclGroupSimulateEnd(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamBind(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetI8(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetI16(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetI32(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetI64(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetU8(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetU16(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetU32(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGetU64(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamGet(conn_t *conn);
#endif
#if NCCL_VERSION_CODE >= 23007
int handle_ncclParamDumpAll(conn_t *conn);
#endif
