// Generated by codegen.py. Do not edit by hand.

int handle_nppGetGpuNumSMs(conn_t *conn);
int handle_nppGetMaxThreadsPerBlock(conn_t *conn);
int handle_nppGetMaxThreadsPerSM(conn_t *conn);
int handle_nppGetGpuDeviceProperties(conn_t *conn);
int handle_nppGetStream(conn_t *conn);
int handle_nppGetStreamContext(conn_t *conn);
int handle_nppGetStreamNumSMs(conn_t *conn);
int handle_nppGetStreamMaxThreadsPerSM(conn_t *conn);
int handle_nppSetStream(conn_t *conn);
