// Generated by codegen.py. Do not edit by hand.

int handle_cusparseLtInit(conn_t *conn);
int handle_cusparseLtGetVersion(conn_t *conn);
int handle_cusparseLtGetProperty(conn_t *conn);
int handle_cusparseLtDenseDescriptorInit(conn_t *conn);
int handle_cusparseLtStructuredDescriptorInit(conn_t *conn);
int handle_cusparseLtMatDescSetAttribute(conn_t *conn);
int handle_cusparseLtMatDescGetAttribute(conn_t *conn);
int handle_cusparseLtMatmulDescriptorInit(conn_t *conn);
int handle_cusparseLtMatmulDescSetAttribute(conn_t *conn);
int handle_cusparseLtMatmulDescGetAttribute(conn_t *conn);
int handle_cusparseLtMatmulAlgSelectionInit(conn_t *conn);
int handle_cusparseLtMatmulAlgSetAttribute(conn_t *conn);
int handle_cusparseLtMatmulAlgGetAttribute(conn_t *conn);
int handle_cusparseLtMatmulGetWorkspace(conn_t *conn);
int handle_cusparseLtMatmulPlanInit(conn_t *conn);
int handle_cusparseLtMatmul(conn_t *conn);
int handle_cusparseLtMatmulSearch(conn_t *conn);
int handle_cusparseLtSpMMAPrune(conn_t *conn);
int handle_cusparseLtSpMMAPruneCheck(conn_t *conn);
int handle_cusparseLtSpMMAPrune2(conn_t *conn);
int handle_cusparseLtSpMMAPruneCheck2(conn_t *conn);
int handle_cusparseLtSpMMACompressedSize(conn_t *conn);
int handle_cusparseLtSpMMACompress(conn_t *conn);
int handle_cusparseLtSpMMACompressedSize2(conn_t *conn);
int handle_cusparseLtSpMMACompress2(conn_t *conn);
