// Generated by codegen.py. Do not edit by hand.

int handle_nvrtcVersion(conn_t *conn);
int handle_nvrtcGetNumSupportedArchs(conn_t *conn);
int handle_nvrtcDestroyProgram(conn_t *conn);
int handle_nvrtcGetPTXSize(conn_t *conn);
int handle_nvrtcGetCUBINSize(conn_t *conn);
#if CUDA_VERSION >= 12000
int handle_nvrtcGetLTOIRSize(conn_t *conn);
#endif
#if CUDA_VERSION >= 12000
int handle_nvrtcGetOptiXIRSize(conn_t *conn);
#endif
#if CUDA_VERSION < 13000
int handle_nvrtcGetNVVMSize(conn_t *conn);
#endif
int handle_nvrtcGetProgramLogSize(conn_t *conn);
int handle_nvrtcAddNameExpression(conn_t *conn);
#if CUDA_VERSION >= 12080
int handle_nvrtcGetPCHHeapSize(conn_t *conn);
#endif
#if CUDA_VERSION >= 12080
int handle_nvrtcSetPCHHeapSize(conn_t *conn);
#endif
#if CUDA_VERSION >= 12080
int handle_nvrtcGetPCHCreateStatus(conn_t *conn);
#endif
#if CUDA_VERSION >= 12080
int handle_nvrtcGetPCHHeapSizeRequired(conn_t *conn);
#endif
#if CUDA_VERSION >= 13020
int handle_nvrtcGetTileIRSize(conn_t *conn);
#endif
