// Generated by codegen.py. Do not edit by hand.

int handle_nppiThreshold_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GT_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GT_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GT_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LT_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LT_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LT_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_Val_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_Val_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_Val_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_GTVal_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_GTVal_32f_AC4IR(conn_t *conn);
#endif
#if NPP_VERSION >= 12002
int handle_nppiFusedAbsDiff_Threshold_GTVal_Ctx(conn_t *conn);
#endif
#if NPP_VERSION >= 12002
int handle_nppiFusedAbsDiff_Threshold_GTVal_I_Ctx(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTVal_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTVal_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_8u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_8u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_8u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16u_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16u_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16u_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16s_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16s_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16s_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_32f_C1R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_32f_C1IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_32f_C1IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_8u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_8u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_8u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16u_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16u_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16u_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16s_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16s_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16s_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_32f_C3R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_32f_C3IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_32f_C3IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_8u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_8u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_8u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16u_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16u_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16u_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16s_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_16s_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_16s_AC4IR(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_32f_AC4R(conn_t *conn);
#endif
int handle_nppiThreshold_LTValGTVal_32f_AC4IR_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiThreshold_LTValGTVal_32f_AC4IR(conn_t *conn);
#endif
int handle_nppiCompare_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_8u_C1R(conn_t *conn);
#endif
int handle_nppiCompare_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_8u_C3R(conn_t *conn);
#endif
int handle_nppiCompare_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_8u_C4R(conn_t *conn);
#endif
int handle_nppiCompare_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCompare_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16u_C1R(conn_t *conn);
#endif
int handle_nppiCompare_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16u_C3R(conn_t *conn);
#endif
int handle_nppiCompare_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16u_C4R(conn_t *conn);
#endif
int handle_nppiCompare_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCompare_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16s_C1R(conn_t *conn);
#endif
int handle_nppiCompare_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16s_C3R(conn_t *conn);
#endif
int handle_nppiCompare_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16s_C4R(conn_t *conn);
#endif
int handle_nppiCompare_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCompare_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_32f_C1R(conn_t *conn);
#endif
int handle_nppiCompare_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_32f_C3R(conn_t *conn);
#endif
int handle_nppiCompare_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_32f_C4R(conn_t *conn);
#endif
int handle_nppiCompare_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompare_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCompareC_8u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_8u_C1R(conn_t *conn);
#endif
int handle_nppiCompareC_8u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_8u_C3R(conn_t *conn);
#endif
int handle_nppiCompareC_8u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_8u_C4R(conn_t *conn);
#endif
int handle_nppiCompareC_8u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_8u_AC4R(conn_t *conn);
#endif
int handle_nppiCompareC_16u_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16u_C1R(conn_t *conn);
#endif
int handle_nppiCompareC_16u_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16u_C3R(conn_t *conn);
#endif
int handle_nppiCompareC_16u_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16u_C4R(conn_t *conn);
#endif
int handle_nppiCompareC_16u_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16u_AC4R(conn_t *conn);
#endif
int handle_nppiCompareC_16s_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16s_C1R(conn_t *conn);
#endif
int handle_nppiCompareC_16s_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16s_C3R(conn_t *conn);
#endif
int handle_nppiCompareC_16s_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16s_C4R(conn_t *conn);
#endif
int handle_nppiCompareC_16s_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_16s_AC4R(conn_t *conn);
#endif
int handle_nppiCompareC_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_32f_C1R(conn_t *conn);
#endif
int handle_nppiCompareC_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_32f_C3R(conn_t *conn);
#endif
int handle_nppiCompareC_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_32f_C4R(conn_t *conn);
#endif
int handle_nppiCompareC_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareC_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCompareEqualEps_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEps_32f_C1R(conn_t *conn);
#endif
int handle_nppiCompareEqualEps_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEps_32f_C3R(conn_t *conn);
#endif
int handle_nppiCompareEqualEps_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEps_32f_C4R(conn_t *conn);
#endif
int handle_nppiCompareEqualEps_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEps_32f_AC4R(conn_t *conn);
#endif
int handle_nppiCompareEqualEpsC_32f_C1R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEpsC_32f_C1R(conn_t *conn);
#endif
int handle_nppiCompareEqualEpsC_32f_C3R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEpsC_32f_C3R(conn_t *conn);
#endif
int handle_nppiCompareEqualEpsC_32f_C4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEpsC_32f_C4R(conn_t *conn);
#endif
int handle_nppiCompareEqualEpsC_32f_AC4R_Ctx(conn_t *conn);
#if NPP_VERSION < 13000
int handle_nppiCompareEqualEpsC_32f_AC4R(conn_t *conn);
#endif
