#include "rpc_server.h"

#include "copy_pipeline.h"
#include "cuda_server.h"
#include "gen_api.h"
#include "nvml_server.h"

// clang-format off
#define LUPINE_RPC_HANDLERS(HANDLER) \
  HANDLER(RPC_cuGetErrorString, handle_cuGetErrorString, lupine_cuda_backend) \
  HANDLER(RPC_cuGetErrorName, handle_cuGetErrorName, lupine_cuda_backend) \
  HANDLER(RPC_cuDevicePrimaryCtxRetain, handle_cuDevicePrimaryCtxRetain, lupine_cuda_backend) \
  HANDLER(RPC_cuDevicePrimaryCtxRelease_v2, handle_cuDevicePrimaryCtxRelease_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuDevicePrimaryCtxReset_v2, handle_cuDevicePrimaryCtxReset_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxCreate_v2, handle_cuCtxCreate_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxDestroy_v2, handle_cuCtxDestroy_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxSynchronize, handle_cuCtxSynchronize, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxAttach, handle_cuCtxAttach, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxDetach, handle_cuCtxDetach, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleLoad, handle_cuModuleLoad, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleLoadData, handle_cuModuleLoadData, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleGetGlobal_v2, handle_cuModuleGetGlobal_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuLinkCreate_v2, handle_cuLinkCreate_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuLinkAddData_v2, handle_cuLinkAddData_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuLinkAddFile_v2, handle_cuLinkAddFile_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuLinkComplete, handle_cuLinkComplete, lupine_cuda_backend) \
  HANDLER(RPC_cuLinkDestroy, handle_cuLinkDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryLoadData, handle_cuLibraryLoadData, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryUnload, handle_cuLibraryUnload, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryGetModule, handle_cuLibraryGetModule, lupine_cuda_backend) \
  HANDLER(RPC_cuMemHostAlloc, handle_cuMemHostAlloc, lupine_cuda_backend) \
  HANDLER(RPC_cuMemHostGetFlags, handle_cuMemHostGetFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyHtoD_v2, handle_cuMemcpyHtoD_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyDtoH_v2, handle_cuMemcpyDtoH_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyAtoH_v2, handle_cuMemcpyAtoH_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpy2D_v2, handle_cuMemcpy2D_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpy2DUnaligned_v2, handle_cuMemcpy2DUnaligned_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpy3D_v2, handle_cuMemcpy3D_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyHtoDAsync_v2, handle_cuMemcpyHtoDAsync_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyDtoHAsync_v2, handle_cuMemcpyDtoHAsync_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpy2DAsync_v2, handle_cuMemcpy2DAsync_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemExportToShareableHandle, handle_cuMemExportToShareableHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuMemImportFromShareableHandle, handle_cuMemImportFromShareableHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolSetAttribute, handle_cuMemPoolSetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolGetAttribute, handle_cuMemPoolGetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolExportToShareableHandle, handle_cuMemPoolExportToShareableHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolImportFromShareableHandle, handle_cuMemPoolImportFromShareableHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuPointerGetAttribute, handle_cuPointerGetAttribute, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuMemPrefetchAsync, handle_cuMemPrefetchAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuPointerSetAttribute, handle_cuPointerSetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuPointerGetAttributes, handle_cuPointerGetAttributes, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamWaitEvent, handle_cuStreamWaitEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamAddCallback, handle_cuStreamAddCallback, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamBeginCapture_v2, handle_cuStreamBeginCapture, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamEndCapture, handle_cuStreamEndCapture, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamSynchronize, handle_cuStreamSynchronize, lupine_cuda_backend) \
  HANDLER(RPC_cuEventRecord, handle_cuEventRecord, lupine_cuda_backend) \
  HANDLER(RPC_cuEventRecordWithFlags, handle_cuEventRecordWithFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuEventQuery, handle_cuEventQuery, lupine_cuda_backend) \
  HANDLER(RPC_cuEventSynchronize, handle_cuEventSynchronize, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchKernel, handle_cuLaunchKernel, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchKernelEx, handle_cuLaunchKernelEx, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchCooperativeKernel, handle_cuLaunchCooperativeKernel, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchHostFunc, handle_cuLaunchHostFunc, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddKernelNode_v2, handle_cuGraphAddKernelNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphKernelNodeGetParams_v2, handle_cuGraphKernelNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphKernelNodeSetParams_v2, handle_cuGraphKernelNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddMemcpyNode, handle_cuGraphAddMemcpyNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddMemsetNode, handle_cuGraphAddMemsetNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddHostNode, handle_cuGraphAddHostNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphHostNodeGetParams, handle_cuGraphHostNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphHostNodeSetParams, handle_cuGraphHostNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetGraphMemAttribute, handle_cuDeviceGetGraphMemAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceSetGraphMemAttribute, handle_cuDeviceSetGraphMemAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphClone, handle_cuGraphClone, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphInstantiateWithFlags, handle_cuGraphInstantiateWithFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphInstantiateWithParams, handle_cuGraphInstantiateWithParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecKernelNodeSetParams_v2, handle_cuGraphExecKernelNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecHostNodeSetParams, handle_cuGraphExecHostNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphLaunch, handle_cuGraphLaunch, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecDestroy, handle_cuGraphExecDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphDestroy, handle_cuGraphDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyMaxPotentialBlockSize, handle_cuOccupancyMaxPotentialBlockSize, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyMaxPotentialBlockSizeWithFlags, handle_cuOccupancyMaxPotentialBlockSizeWithFlags, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuGetExportTableMetadata, handle_cuGetExportTableMetadata, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuPrivateGetModuleNode, handle_cuPrivateGetModuleNode, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineFunctionParamLayoutSnapshot, handle_lupineFunctionParamLayoutSnapshot, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineFunctionAttributeSnapshot, handle_lupineFunctionAttributeSnapshot, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineLibrarySnapshot, handle_lupineLibrarySnapshot, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineLibraryAttributeSnapshot, handle_lupineLibraryAttributeSnapshot, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuGraphConditionalHandleCreate, handle_cuGraphConditionalHandleCreate, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuGraphAddNode_v2, handle_cuGraphAddNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphGetEdges_v2, handle_cuGraphGetEdges, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphNodeGetDependencies_v2, handle_cuGraphNodeGetDependencies, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphNodeGetDependentNodes_v2, handle_cuGraphNodeGetDependentNodes, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineEventQueryBatch, handle_lupineEventQueryBatch, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuStreamBeginCaptureToGraph, handle_cuStreamBeginCaptureToGraph, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamUpdateCaptureDependencies_v2, handle_cuStreamUpdateCaptureDependencies, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_cuStreamGetCaptureInfo_v3, handle_cuStreamGetCaptureInfo, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineManagedHostFlush, handle_lupineManagedHostFlush, lupine_cuda_backend) \
  HANDLER(LUPINE_RPC_lupineDeviceSnapshot, handle_lupineDeviceSnapshot, lupine_cuda_backend) \
  HANDLER(RPC_nvmlDeviceGetComputeRunningProcesses, handle_nvmlDeviceGetComputeRunningProcesses, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetComputeRunningProcesses_v2, handle_nvmlDeviceGetComputeRunningProcesses_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetGraphicsRunningProcesses, handle_nvmlDeviceGetGraphicsRunningProcesses, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetGraphicsRunningProcesses_v2, handle_nvmlDeviceGetGraphicsRunningProcesses_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMPSComputeRunningProcesses, handle_nvmlDeviceGetMPSComputeRunningProcesses, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMPSComputeRunningProcesses_v2, handle_nvmlDeviceGetMPSComputeRunningProcesses_v2, lupine_nvml_backend) \
  HANDLER(RPC_cuInit, handle_cuInit, lupine_cuda_backend) \
  HANDLER(RPC_cuDriverGetVersion, handle_cuDriverGetVersion, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGet, handle_cuDeviceGet, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetCount, handle_cuDeviceGetCount, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetName, handle_cuDeviceGetName, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetUuid_v2, handle_cuDeviceGetUuid_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetLuid, handle_cuDeviceGetLuid, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceTotalMem_v2, handle_cuDeviceTotalMem_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetTexture1DLinearMaxWidth, handle_cuDeviceGetTexture1DLinearMaxWidth, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetAttribute, handle_cuDeviceGetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceSetMemPool, handle_cuDeviceSetMemPool, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetMemPool, handle_cuDeviceGetMemPool, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetDefaultMemPool, handle_cuDeviceGetDefaultMemPool, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetExecAffinitySupport, handle_cuDeviceGetExecAffinitySupport, lupine_cuda_backend) \
  HANDLER(RPC_cuFlushGPUDirectRDMAWrites, handle_cuFlushGPUDirectRDMAWrites, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetProperties, handle_cuDeviceGetProperties, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceComputeCapability, handle_cuDeviceComputeCapability, lupine_cuda_backend) \
  HANDLER(RPC_cuDevicePrimaryCtxSetFlags_v2, handle_cuDevicePrimaryCtxSetFlags_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuDevicePrimaryCtxGetState, handle_cuDevicePrimaryCtxGetState, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxPushCurrent_v2, handle_cuCtxPushCurrent_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxPopCurrent_v2, handle_cuCtxPopCurrent_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxSetCurrent, handle_cuCtxSetCurrent, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetCurrent, handle_cuCtxGetCurrent, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetDevice, handle_cuCtxGetDevice, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetFlags, handle_cuCtxGetFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetId, handle_cuCtxGetId, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxSetLimit, handle_cuCtxSetLimit, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetLimit, handle_cuCtxGetLimit, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetCacheConfig, handle_cuCtxGetCacheConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxSetCacheConfig, handle_cuCtxSetCacheConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetApiVersion, handle_cuCtxGetApiVersion, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetStreamPriorityRange, handle_cuCtxGetStreamPriorityRange, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxResetPersistingL2Cache, handle_cuCtxResetPersistingL2Cache, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetExecAffinity, handle_cuCtxGetExecAffinity, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxGetSharedMemConfig, handle_cuCtxGetSharedMemConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxSetSharedMemConfig, handle_cuCtxSetSharedMemConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleUnload, handle_cuModuleUnload, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleGetLoadingMode, handle_cuModuleGetLoadingMode, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleGetFunction, handle_cuModuleGetFunction, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleGetTexRef, handle_cuModuleGetTexRef, lupine_cuda_backend) \
  HANDLER(RPC_cuModuleGetSurfRef, handle_cuModuleGetSurfRef, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryLoadFromFile, handle_cuLibraryLoadFromFile, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryGetKernel, handle_cuLibraryGetKernel, lupine_cuda_backend) \
  HANDLER(RPC_cuKernelGetFunction, handle_cuKernelGetFunction, lupine_cuda_backend) \
  HANDLER(RPC_cuKernelGetLibrary, handle_cuKernelGetLibrary, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryGetGlobal, handle_cuLibraryGetGlobal, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryGetManaged, handle_cuLibraryGetManaged, lupine_cuda_backend) \
  HANDLER(RPC_cuLibraryGetUnifiedFunction, handle_cuLibraryGetUnifiedFunction, lupine_cuda_backend) \
  HANDLER(RPC_cuKernelGetAttribute, handle_cuKernelGetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuKernelSetAttribute, handle_cuKernelSetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuKernelSetCacheConfig, handle_cuKernelSetCacheConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuKernelGetParamInfo, handle_cuKernelGetParamInfo, lupine_cuda_backend) \
  HANDLER(RPC_cuMemGetInfo_v2, handle_cuMemGetInfo_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAlloc_v2, handle_cuMemAlloc_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAllocPitch_v2, handle_cuMemAllocPitch_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemFree_v2, handle_cuMemFree_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemGetAddressRange_v2, handle_cuMemGetAddressRange_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAllocHost_v2, handle_cuMemAllocHost_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemFreeHost, handle_cuMemFreeHost, lupine_cuda_backend) \
  HANDLER(RPC_cuMemHostGetDevicePointer_v2, handle_cuMemHostGetDevicePointer_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAllocManaged, handle_cuMemAllocManaged, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetByPCIBusId, handle_cuDeviceGetByPCIBusId, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetPCIBusId, handle_cuDeviceGetPCIBusId, lupine_cuda_backend) \
  HANDLER(RPC_cuIpcGetEventHandle, handle_cuIpcGetEventHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuIpcOpenEventHandle, handle_cuIpcOpenEventHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuIpcGetMemHandle, handle_cuIpcGetMemHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuIpcOpenMemHandle_v2, handle_cuIpcOpenMemHandle_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuIpcCloseMemHandle, handle_cuIpcCloseMemHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpy, handle_cuMemcpy, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyPeer, handle_cuMemcpyPeer, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyDtoD_v2, handle_cuMemcpyDtoD_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyDtoA_v2, handle_cuMemcpyDtoA_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyAtoD_v2, handle_cuMemcpyAtoD_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyAtoA_v2, handle_cuMemcpyAtoA_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyPeerAsync, handle_cuMemcpyPeerAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuMemcpyDtoDAsync_v2, handle_cuMemcpyDtoDAsync_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD8_v2, handle_cuMemsetD8_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD16_v2, handle_cuMemsetD16_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD32_v2, handle_cuMemsetD32_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD2D8_v2, handle_cuMemsetD2D8_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD2D16_v2, handle_cuMemsetD2D16_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD2D32_v2, handle_cuMemsetD2D32_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD8Async, handle_cuMemsetD8Async, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD16Async, handle_cuMemsetD16Async, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD32Async, handle_cuMemsetD32Async, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD2D8Async, handle_cuMemsetD2D8Async, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD2D16Async, handle_cuMemsetD2D16Async, lupine_cuda_backend) \
  HANDLER(RPC_cuMemsetD2D32Async, handle_cuMemsetD2D32Async, lupine_cuda_backend) \
  HANDLER(RPC_cuArrayCreate_v2, handle_cuArrayCreate_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuArrayGetDescriptor_v2, handle_cuArrayGetDescriptor_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuArrayGetSparseProperties, handle_cuArrayGetSparseProperties, lupine_cuda_backend) \
  HANDLER(RPC_cuMipmappedArrayGetSparseProperties, handle_cuMipmappedArrayGetSparseProperties, lupine_cuda_backend) \
  HANDLER(RPC_cuArrayGetMemoryRequirements, handle_cuArrayGetMemoryRequirements, lupine_cuda_backend) \
  HANDLER(RPC_cuMipmappedArrayGetMemoryRequirements, handle_cuMipmappedArrayGetMemoryRequirements, lupine_cuda_backend) \
  HANDLER(RPC_cuArrayGetPlane, handle_cuArrayGetPlane, lupine_cuda_backend) \
  HANDLER(RPC_cuArrayDestroy, handle_cuArrayDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuArray3DCreate_v2, handle_cuArray3DCreate_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuArray3DGetDescriptor_v2, handle_cuArray3DGetDescriptor_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuMipmappedArrayCreate, handle_cuMipmappedArrayCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuMipmappedArrayGetLevel, handle_cuMipmappedArrayGetLevel, lupine_cuda_backend) \
  HANDLER(RPC_cuMipmappedArrayDestroy, handle_cuMipmappedArrayDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAddressReserve, handle_cuMemAddressReserve, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAddressFree, handle_cuMemAddressFree, lupine_cuda_backend) \
  HANDLER(RPC_cuMemCreate, handle_cuMemCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuMemRelease, handle_cuMemRelease, lupine_cuda_backend) \
  HANDLER(RPC_cuMemMap, handle_cuMemMap, lupine_cuda_backend) \
  HANDLER(RPC_cuMemMapArrayAsync, handle_cuMemMapArrayAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuMemUnmap, handle_cuMemUnmap, lupine_cuda_backend) \
  HANDLER(RPC_cuMemSetAccess, handle_cuMemSetAccess, lupine_cuda_backend) \
  HANDLER(RPC_cuMemGetAccess, handle_cuMemGetAccess, lupine_cuda_backend) \
  HANDLER(RPC_cuMemGetAllocationGranularity, handle_cuMemGetAllocationGranularity, lupine_cuda_backend) \
  HANDLER(RPC_cuMemGetAllocationPropertiesFromHandle, handle_cuMemGetAllocationPropertiesFromHandle, lupine_cuda_backend) \
  HANDLER(RPC_cuMemFreeAsync, handle_cuMemFreeAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAllocAsync, handle_cuMemAllocAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolTrimTo, handle_cuMemPoolTrimTo, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolSetAccess, handle_cuMemPoolSetAccess, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolGetAccess, handle_cuMemPoolGetAccess, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolCreate, handle_cuMemPoolCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolDestroy, handle_cuMemPoolDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuMemAllocFromPoolAsync, handle_cuMemAllocFromPoolAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolExportPointer, handle_cuMemPoolExportPointer, lupine_cuda_backend) \
  HANDLER(RPC_cuMemPoolImportPointer, handle_cuMemPoolImportPointer, lupine_cuda_backend) \
  HANDLER(RPC_cuMemRangeGetAttributes, handle_cuMemRangeGetAttributes, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamCreate, handle_cuStreamCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamCreateWithPriority, handle_cuStreamCreateWithPriority, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamGetPriority, handle_cuStreamGetPriority, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamGetFlags, handle_cuStreamGetFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamGetId, handle_cuStreamGetId, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamGetCtx, handle_cuStreamGetCtx, lupine_cuda_backend) \
  HANDLER(RPC_cuThreadExchangeStreamCaptureMode, handle_cuThreadExchangeStreamCaptureMode, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamIsCapturing, handle_cuStreamIsCapturing, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamAttachMemAsync, handle_cuStreamAttachMemAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamQuery, handle_cuStreamQuery, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamDestroy_v2, handle_cuStreamDestroy_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamCopyAttributes, handle_cuStreamCopyAttributes, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamGetAttribute, handle_cuStreamGetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamSetAttribute, handle_cuStreamSetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuEventCreate, handle_cuEventCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuEventDestroy_v2, handle_cuEventDestroy_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuEventElapsedTime_v2, handle_cuEventElapsedTime_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuImportExternalMemory, handle_cuImportExternalMemory, lupine_cuda_backend) \
  HANDLER(RPC_cuExternalMemoryGetMappedBuffer, handle_cuExternalMemoryGetMappedBuffer, lupine_cuda_backend) \
  HANDLER(RPC_cuExternalMemoryGetMappedMipmappedArray, handle_cuExternalMemoryGetMappedMipmappedArray, lupine_cuda_backend) \
  HANDLER(RPC_cuDestroyExternalMemory, handle_cuDestroyExternalMemory, lupine_cuda_backend) \
  HANDLER(RPC_cuImportExternalSemaphore, handle_cuImportExternalSemaphore, lupine_cuda_backend) \
  HANDLER(RPC_cuSignalExternalSemaphoresAsync, handle_cuSignalExternalSemaphoresAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuWaitExternalSemaphoresAsync, handle_cuWaitExternalSemaphoresAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuDestroyExternalSemaphore, handle_cuDestroyExternalSemaphore, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamWaitValue32_v2, handle_cuStreamWaitValue32_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamWaitValue64_v2, handle_cuStreamWaitValue64_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamWriteValue32_v2, handle_cuStreamWriteValue32_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamWriteValue64_v2, handle_cuStreamWriteValue64_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuStreamBatchMemOp_v2, handle_cuStreamBatchMemOp_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncGetAttribute, handle_cuFuncGetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncSetAttribute, handle_cuFuncSetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncSetCacheConfig, handle_cuFuncSetCacheConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncGetModule, handle_cuFuncGetModule, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncGetParamInfo, handle_cuFuncGetParamInfo, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchCooperativeKernelMultiDevice, handle_cuLaunchCooperativeKernelMultiDevice, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncSetBlockShape, handle_cuFuncSetBlockShape, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncSetSharedSize, handle_cuFuncSetSharedSize, lupine_cuda_backend) \
  HANDLER(RPC_cuParamSetSize, handle_cuParamSetSize, lupine_cuda_backend) \
  HANDLER(RPC_cuParamSeti, handle_cuParamSeti, lupine_cuda_backend) \
  HANDLER(RPC_cuParamSetf, handle_cuParamSetf, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunch, handle_cuLaunch, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchGrid, handle_cuLaunchGrid, lupine_cuda_backend) \
  HANDLER(RPC_cuLaunchGridAsync, handle_cuLaunchGridAsync, lupine_cuda_backend) \
  HANDLER(RPC_cuParamSetTexRef, handle_cuParamSetTexRef, lupine_cuda_backend) \
  HANDLER(RPC_cuFuncSetSharedMemConfig, handle_cuFuncSetSharedMemConfig, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphCreate, handle_cuGraphCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphMemcpyNodeGetParams, handle_cuGraphMemcpyNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphMemcpyNodeSetParams, handle_cuGraphMemcpyNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphMemsetNodeGetParams, handle_cuGraphMemsetNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphMemsetNodeSetParams, handle_cuGraphMemsetNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddChildGraphNode, handle_cuGraphAddChildGraphNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphChildGraphNodeGetGraph, handle_cuGraphChildGraphNodeGetGraph, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddEmptyNode, handle_cuGraphAddEmptyNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddEventRecordNode, handle_cuGraphAddEventRecordNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphEventRecordNodeGetEvent, handle_cuGraphEventRecordNodeGetEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphEventRecordNodeSetEvent, handle_cuGraphEventRecordNodeSetEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddEventWaitNode, handle_cuGraphAddEventWaitNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphEventWaitNodeGetEvent, handle_cuGraphEventWaitNodeGetEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphEventWaitNodeSetEvent, handle_cuGraphEventWaitNodeSetEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddExternalSemaphoresSignalNode, handle_cuGraphAddExternalSemaphoresSignalNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExternalSemaphoresSignalNodeGetParams, handle_cuGraphExternalSemaphoresSignalNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExternalSemaphoresSignalNodeSetParams, handle_cuGraphExternalSemaphoresSignalNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddExternalSemaphoresWaitNode, handle_cuGraphAddExternalSemaphoresWaitNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExternalSemaphoresWaitNodeGetParams, handle_cuGraphExternalSemaphoresWaitNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExternalSemaphoresWaitNodeSetParams, handle_cuGraphExternalSemaphoresWaitNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddBatchMemOpNode, handle_cuGraphAddBatchMemOpNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphBatchMemOpNodeGetParams, handle_cuGraphBatchMemOpNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphBatchMemOpNodeSetParams, handle_cuGraphBatchMemOpNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecBatchMemOpNodeSetParams, handle_cuGraphExecBatchMemOpNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddMemAllocNode, handle_cuGraphAddMemAllocNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphMemAllocNodeGetParams, handle_cuGraphMemAllocNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphAddMemFreeNode, handle_cuGraphAddMemFreeNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphMemFreeNodeGetParams, handle_cuGraphMemFreeNodeGetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGraphMemTrim, handle_cuDeviceGraphMemTrim, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphNodeFindInClone, handle_cuGraphNodeFindInClone, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphNodeGetType, handle_cuGraphNodeGetType, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphGetNodes, handle_cuGraphGetNodes, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphGetRootNodes, handle_cuGraphGetRootNodes, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphDestroyNode, handle_cuGraphDestroyNode, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecGetFlags, handle_cuGraphExecGetFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecMemcpyNodeSetParams, handle_cuGraphExecMemcpyNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecMemsetNodeSetParams, handle_cuGraphExecMemsetNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecChildGraphNodeSetParams, handle_cuGraphExecChildGraphNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecEventRecordNodeSetEvent, handle_cuGraphExecEventRecordNodeSetEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecEventWaitNodeSetEvent, handle_cuGraphExecEventWaitNodeSetEvent, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecExternalSemaphoresSignalNodeSetParams, handle_cuGraphExecExternalSemaphoresSignalNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecExternalSemaphoresWaitNodeSetParams, handle_cuGraphExecExternalSemaphoresWaitNodeSetParams, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphNodeSetEnabled, handle_cuGraphNodeSetEnabled, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphNodeGetEnabled, handle_cuGraphNodeGetEnabled, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphUpload, handle_cuGraphUpload, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphExecUpdate_v2, handle_cuGraphExecUpdate_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphKernelNodeCopyAttributes, handle_cuGraphKernelNodeCopyAttributes, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphKernelNodeGetAttribute, handle_cuGraphKernelNodeGetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphKernelNodeSetAttribute, handle_cuGraphKernelNodeSetAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphDebugDotPrint, handle_cuGraphDebugDotPrint, lupine_cuda_backend) \
  HANDLER(RPC_cuUserObjectRetain, handle_cuUserObjectRetain, lupine_cuda_backend) \
  HANDLER(RPC_cuUserObjectRelease, handle_cuUserObjectRelease, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphRetainUserObject, handle_cuGraphRetainUserObject, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphReleaseUserObject, handle_cuGraphReleaseUserObject, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyMaxActiveBlocksPerMultiprocessor, handle_cuOccupancyMaxActiveBlocksPerMultiprocessor, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags, handle_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyAvailableDynamicSMemPerBlock, handle_cuOccupancyAvailableDynamicSMemPerBlock, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyMaxPotentialClusterSize, handle_cuOccupancyMaxPotentialClusterSize, lupine_cuda_backend) \
  HANDLER(RPC_cuOccupancyMaxActiveClusters, handle_cuOccupancyMaxActiveClusters, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetArray, handle_cuTexRefSetArray, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetMipmappedArray, handle_cuTexRefSetMipmappedArray, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetAddress_v2, handle_cuTexRefSetAddress_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetAddress2D_v3, handle_cuTexRefSetAddress2D_v3, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetFormat, handle_cuTexRefSetFormat, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetAddressMode, handle_cuTexRefSetAddressMode, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetFilterMode, handle_cuTexRefSetFilterMode, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetMipmapFilterMode, handle_cuTexRefSetMipmapFilterMode, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetMipmapLevelBias, handle_cuTexRefSetMipmapLevelBias, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetMipmapLevelClamp, handle_cuTexRefSetMipmapLevelClamp, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetMaxAnisotropy, handle_cuTexRefSetMaxAnisotropy, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetBorderColor, handle_cuTexRefSetBorderColor, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefSetFlags, handle_cuTexRefSetFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetAddress_v2, handle_cuTexRefGetAddress_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetArray, handle_cuTexRefGetArray, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetMipmappedArray, handle_cuTexRefGetMipmappedArray, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetAddressMode, handle_cuTexRefGetAddressMode, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetFilterMode, handle_cuTexRefGetFilterMode, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetFormat, handle_cuTexRefGetFormat, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetMipmapFilterMode, handle_cuTexRefGetMipmapFilterMode, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetMipmapLevelBias, handle_cuTexRefGetMipmapLevelBias, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetMipmapLevelClamp, handle_cuTexRefGetMipmapLevelClamp, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetMaxAnisotropy, handle_cuTexRefGetMaxAnisotropy, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetBorderColor, handle_cuTexRefGetBorderColor, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefGetFlags, handle_cuTexRefGetFlags, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefCreate, handle_cuTexRefCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuTexRefDestroy, handle_cuTexRefDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuSurfRefSetArray, handle_cuSurfRefSetArray, lupine_cuda_backend) \
  HANDLER(RPC_cuSurfRefGetArray, handle_cuSurfRefGetArray, lupine_cuda_backend) \
  HANDLER(RPC_cuTexObjectCreate, handle_cuTexObjectCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuTexObjectDestroy, handle_cuTexObjectDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuTexObjectGetResourceDesc, handle_cuTexObjectGetResourceDesc, lupine_cuda_backend) \
  HANDLER(RPC_cuTexObjectGetTextureDesc, handle_cuTexObjectGetTextureDesc, lupine_cuda_backend) \
  HANDLER(RPC_cuTexObjectGetResourceViewDesc, handle_cuTexObjectGetResourceViewDesc, lupine_cuda_backend) \
  HANDLER(RPC_cuSurfObjectCreate, handle_cuSurfObjectCreate, lupine_cuda_backend) \
  HANDLER(RPC_cuSurfObjectDestroy, handle_cuSurfObjectDestroy, lupine_cuda_backend) \
  HANDLER(RPC_cuSurfObjectGetResourceDesc, handle_cuSurfObjectGetResourceDesc, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceCanAccessPeer, handle_cuDeviceCanAccessPeer, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxEnablePeerAccess, handle_cuCtxEnablePeerAccess, lupine_cuda_backend) \
  HANDLER(RPC_cuCtxDisablePeerAccess, handle_cuCtxDisablePeerAccess, lupine_cuda_backend) \
  HANDLER(RPC_cuDeviceGetP2PAttribute, handle_cuDeviceGetP2PAttribute, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsUnregisterResource, handle_cuGraphicsUnregisterResource, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsSubResourceGetMappedArray, handle_cuGraphicsSubResourceGetMappedArray, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsResourceGetMappedMipmappedArray, handle_cuGraphicsResourceGetMappedMipmappedArray, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsResourceGetMappedPointer_v2, handle_cuGraphicsResourceGetMappedPointer_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsResourceSetMapFlags_v2, handle_cuGraphicsResourceSetMapFlags_v2, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsMapResources, handle_cuGraphicsMapResources, lupine_cuda_backend) \
  HANDLER(RPC_cuGraphicsUnmapResources, handle_cuGraphicsUnmapResources, lupine_cuda_backend) \
  HANDLER(RPC_nvmlInit_v2, handle_nvmlInit_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlInitWithFlags, handle_nvmlInitWithFlags, lupine_nvml_backend) \
  HANDLER(RPC_nvmlShutdown, handle_nvmlShutdown, lupine_nvml_backend) \
  HANDLER(RPC_nvmlSystemGetDriverVersion, handle_nvmlSystemGetDriverVersion, lupine_nvml_backend) \
  HANDLER(RPC_nvmlSystemGetNVMLVersion, handle_nvmlSystemGetNVMLVersion, lupine_nvml_backend) \
  HANDLER(RPC_nvmlSystemGetCudaDriverVersion, handle_nvmlSystemGetCudaDriverVersion, lupine_nvml_backend) \
  HANDLER(RPC_nvmlSystemGetCudaDriverVersion_v2, handle_nvmlSystemGetCudaDriverVersion_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetCount_v2, handle_nvmlDeviceGetCount_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetHandleByIndex_v2, handle_nvmlDeviceGetHandleByIndex_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetHandleByUUID, handle_nvmlDeviceGetHandleByUUID, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetHandleByPciBusId_v2, handle_nvmlDeviceGetHandleByPciBusId_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetName, handle_nvmlDeviceGetName, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetUUID, handle_nvmlDeviceGetUUID, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetIndex, handle_nvmlDeviceGetIndex, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMinorNumber, handle_nvmlDeviceGetMinorNumber, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPciInfo_v3, handle_nvmlDeviceGetPciInfo_v3, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMemoryInfo, handle_nvmlDeviceGetMemoryInfo, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetUtilizationRates, handle_nvmlDeviceGetUtilizationRates, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetTemperature, handle_nvmlDeviceGetTemperature, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPowerUsage, handle_nvmlDeviceGetPowerUsage, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPowerManagementLimit, handle_nvmlDeviceGetPowerManagementLimit, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetClockInfo, handle_nvmlDeviceGetClockInfo, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMaxClockInfo, handle_nvmlDeviceGetMaxClockInfo, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPerformanceState, handle_nvmlDeviceGetPerformanceState, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetComputeMode, handle_nvmlDeviceGetComputeMode, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPersistenceMode, handle_nvmlDeviceGetPersistenceMode, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetFanSpeed, handle_nvmlDeviceGetFanSpeed, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetBrand, handle_nvmlDeviceGetBrand, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetVbiosVersion, handle_nvmlDeviceGetVbiosVersion, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetSerial, handle_nvmlDeviceGetSerial, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetBoardPartNumber, handle_nvmlDeviceGetBoardPartNumber, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetDisplayMode, handle_nvmlDeviceGetDisplayMode, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetDisplayActive, handle_nvmlDeviceGetDisplayActive, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetCurrPcieLinkGeneration, handle_nvmlDeviceGetCurrPcieLinkGeneration, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetCurrPcieLinkWidth, handle_nvmlDeviceGetCurrPcieLinkWidth, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMaxPcieLinkGeneration, handle_nvmlDeviceGetMaxPcieLinkGeneration, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMaxPcieLinkWidth, handle_nvmlDeviceGetMaxPcieLinkWidth, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPcieThroughput, handle_nvmlDeviceGetPcieThroughput, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetPcieReplayCounter, handle_nvmlDeviceGetPcieReplayCounter, lupine_nvml_backend) \
  HANDLER(RPC_nvmlEventSetCreate, handle_nvmlEventSetCreate, lupine_nvml_backend) \
  HANDLER(RPC_nvmlEventSetFree, handle_nvmlEventSetFree, lupine_nvml_backend) \
  HANDLER(RPC_nvmlEventSetWait_v2, handle_nvmlEventSetWait_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceRegisterEvents, handle_nvmlDeviceRegisterEvents, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMaxMigDeviceCount, handle_nvmlDeviceGetMaxMigDeviceCount, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetTotalEccErrors, handle_nvmlDeviceGetTotalEccErrors, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetDetailedEccErrors, handle_nvmlDeviceGetDetailedEccErrors, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMemoryErrorCounter, handle_nvmlDeviceGetMemoryErrorCounter, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetEccMode, handle_nvmlDeviceGetEccMode, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetTemperatureV, handle_nvmlDeviceGetTemperatureV, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetEnforcedPowerLimit, handle_nvmlDeviceGetEnforcedPowerLimit, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMemoryInfo_v2, handle_nvmlDeviceGetMemoryInfo_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetMigMode, handle_nvmlDeviceGetMigMode, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetVirtualizationMode, handle_nvmlDeviceGetVirtualizationMode, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceIsMigDeviceHandle, handle_nvmlDeviceIsMigDeviceHandle, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetNvLinkRemoteDeviceType, handle_nvmlDeviceGetNvLinkRemoteDeviceType, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetNvLinkRemotePciInfo_v2, handle_nvmlDeviceGetNvLinkRemotePciInfo_v2, lupine_nvml_backend) \
  HANDLER(RPC_nvmlDeviceGetCudaComputeCapability, handle_nvmlDeviceGetCudaComputeCapability, lupine_nvml_backend)
// clang-format on

#define LUPINE_DECLARE_HANDLER(operation, handler, backend)                    \
  int handler(conn_t *conn);
LUPINE_RPC_HANDLERS(LUPINE_DECLARE_HANDLER)
#undef LUPINE_DECLARE_HANDLER

const rpc_handler_registry &lupine_rpc_handlers() {
#define LUPINE_REGISTER_HANDLER(operation, handler, backend)                   \
  {operation, {handler, &backend}},
  static const rpc_handler_registry handlers = {
      LUPINE_RPC_HANDLERS(LUPINE_REGISTER_HANDLER)
#if CUDA_VERSION >= 12000
          LUPINE_REGISTER_HANDLER(RPC_cuTensorMapEncodeTiled,
                                  handle_cuTensorMapEncodeTiled,
                                  lupine_cuda_backend)
#endif
  };
#undef LUPINE_REGISTER_HANDLER
  return handlers;
}

#undef LUPINE_RPC_HANDLERS
