#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# ///

import base64
import hashlib
import json
import stat
import sys
import zipfile
from pathlib import Path


input_dir, archive_path, platforms, symbol, output_path, *files = sys.argv[1:]
input_dir = Path(input_dir)
archive_path = Path(archive_path)
output_path = Path(output_path)
archive_path.parent.mkdir(parents=True, exist_ok=True)

manifest = {
    "files": [
        {
            "mode": "0755",
            "path": name,
            "sha256": hashlib.sha256((input_dir / name).read_bytes()).hexdigest(),
        }
        for name in files
    ],
    "platforms": platforms.split(";"),
    "schema": 1,
}


def zip_info(name: str, mode: int) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
    info.compress_type = zipfile.ZIP_DEFLATED
    info.create_system = 3
    info.external_attr = (stat.S_IFREG | mode) << 16
    return info


with zipfile.ZipFile(
    archive_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9
) as archive:
    archive.writestr(
        zip_info("manifest.json", 0o644),
        json.dumps(manifest, separators=(",", ":")),
    )
    for name in files:
        archive.writestr(zip_info(name, 0o755), (input_dir / name).read_bytes())

chunk_sizes = []
digest = hashlib.sha256()
with output_path.open("w", newline="\n") as output, archive_path.open("rb") as archive:
    output.write(
        "// Generated by bundle_codegen.py; do not edit.\n"
        '#include "client_bundle.h"\n\nnamespace {\n'
    )
    while chunk := archive.read(4096):
        digest.update(chunk)
        output.write(f"const char kChunk{len(chunk_sizes)}[] =\n")
        for offset in range(0, len(chunk), 64):
            octets = "".join(f"\\{byte:03o}" for byte in chunk[offset : offset + 64])
            output.write(f'    "{octets}"\n')
        output.write(";\n")
        chunk_sizes.append(len(chunk))

    output.write("\nconst lupine_client_bundle_chunk kChunks[] = {\n")
    for index, size in enumerate(chunk_sizes):
        output.write(f"    {{kChunk{index}, {size}}},\n")
    hexdigest = digest.hexdigest()
    content_digest = base64.b64encode(digest.digest()).decode()
    output.write(
        "};\n} // namespace\n\n"
        f"extern const lupine_client_bundle_payload {symbol} = {{\n"
        f'    "\\"sha256:{hexdigest}\\"",\n'
        f'    "sha-256=:{content_digest}:",\n'
        "    kChunks,\n"
        "    sizeof(kChunks) / sizeof(kChunks[0]),\n"
        f"    {sum(chunk_sizes)},\n"
        "};\n"
    )
